bytecodealliance/cranelift

README.rst

First things first; while this is pretty obvious when you are acquainted with Rust, it won't hurt to be overly explicit here. @stoklund, can you have a look, please?

Add build instructions to the README

---

README.rst

I added this link because I've never heard of nasal demons. I figured there might be other folks out there who also have never heard of it and might like the link.

Added link to README about nasal demons.

---

lib/cretonne/meta/base/instructions.py
lib/cretonne/meta/cdsl/instructions.py
lib/cretonne/meta/gen_instr.py

generate `is_branch`, `is_terminator`, `can_trap` methods for `enum
Opcode`.

added Opcode flags methods

---

lib/cretonne/meta/base/instructions.py

Documentation fix for what appears to be a minor copy-paste mistake.

---

lib/reader/src/lexer.rs

#24 
Not complete yet, I want to add some tests, just putting this here so you can see what it looks like so far.

Lexer can now scan names, hex sequences, brackets and minus signs.

---

lib/cretonne/meta/gen_settings.py
lib/cretonne/src/ir/funcname.rs
lib/cretonne/src/ir/immediates.rs
lib/cretonne/src/ir/instructions.rs
lib/cretonne/src/ir/jumptable.rs
lib/cretonne/src/settings.rs
lib/cretonne/src/verifier.rs
lib/cretonne/src/write.rs
lib/filecheck/src/checker.rs
lib/filecheck/src/explain.rs
lib/filecheck/src/pattern.rs
lib/reader/src/parser.rs
lib/reader/src/sourcemap.rs
lib/reader/src/testcommand.rs
src/cat.rs
src/filetest/legalizer.rs
src/filetest/regalloc.rs
src/filetest/runone.rs
src/filetest/subtest.rs
src/print_cfg.rs
src/rsfilecheck.rs
src/utils.rs

Converts all try! macros to ? syntax.

---

lib/cretonne/src/entity_list.rs

Stumbled upon this while reading the entity list code.

[EntityList] Fix typo. No functional change.

---

lib/cretonne/src/btree.rs

Initial B-tree interface.

---

docs/langref.rst
lib/cretonne/meta/base/instructions.py

Issue #22 
As far as I can tell, this was all the work needed to define them? Even test-wise it seems any tests I could write on these would just be checking the general Python mechanisms are working properly.

Define boolean conversion instructions.

---

lib/cretonne/src/cfg.rs

Issue #10 
Pretty happy with this other than the ugly temporary ownership thanks to borrowck, but I can't think of a nicer solution bar splitting ControlFlowGraph::data out into separate successor and predecessor lists.

Added ControlFlowGraph::recompute_ebb for incremental CFG updates.

---

lib/cretonne/src/entity_list.rs
lib/cretonne/src/ir/dfg.rs
lib/cretonne/src/verifier.rs

Issue #3 
This is still a work-in-progress currently, just wanting to know if I'm going about it the right way?

Verifier now checks integrity of instruction's results and references

---

lib/cretonne/src/ir/dfg.rs
lib/reader/src/parser.rs

This is a WIP PR, making this for some feedback about whether the general direction is correct.
Things that still need to be done:
* Tests to ensure parsing value aliases work;
* Verification that repeated value aliasing statements are aliasing to the same value;
* Rewriting aliased values as they are defined in the source code
Fixes #23.

Parse value alias

---

lib/cretonne/src/ir/entities.rs
lib/cretonne/src/verifier.rs

Verify integrity of the existing control flow graph of the context.

---

lib/cretonne/meta/cdsl/instructions.py

Per review comment in #79, this adds a check for unknown instruction attributes.

Check for unknown instruction attributes.

---

docs/testing.rst
filetests/simple_gvn/basic.cton
lib/cretonne/meta/base/instructions.py
lib/cretonne/meta/cdsl/instructions.py
lib/cretonne/meta/gen_instr.py
lib/cretonne/src/context.rs
lib/cretonne/src/entity_list.rs
lib/cretonne/src/ir/condcodes.rs
lib/cretonne/src/ir/dfg.rs
lib/cretonne/src/ir/immediates.rs
lib/cretonne/src/ir/instructions.rs
lib/cretonne/src/ir/memflags.rs
lib/cretonne/src/lib.rs
lib/cretonne/src/simple_gvn.rs
src/filetest/mod.rs
src/filetest/simple_gvn.rs

This is a really experimental pass that I put together as a way to start exploring the code. It's pretty incomplete right now, but it does implement enough to replace a redundant instruction in a simple testcase :-).
I'm still quite new to Rust, and Cretonne, so I'd be very interested in better ways to do any of the things the code is doing.

Start a very simple GVN pass

---

lib/filecheck/Cargo.toml
lib/filecheck/src/checker.rs
lib/filecheck/src/pattern.rs

Hi,
This should hopefully resolve #88, the tests are passing.
Please let me know if I missed something.
Thanks

Updated the regex crate to 0.2.2 as per issue #88

---

lib/cretonne/src/licm.rs

The review is here: https://github.com/stoklund/cretonne/pull/87.

LICM pass: small changes after code review

---

lib/cretonne/src/entity_list.rs
lib/cretonne/src/ir/dfg.rs

Added `remove_ebb_args` and `append_branch_argument`. `remove_ebb_args` has `Vec::swap_remove` semantics.

Improved DFG API

---

lib/cretonne/src/context.rs
lib/cretonne/src/ir/condcodes.rs
lib/cretonne/src/ir/dfg.rs
lib/cretonne/src/ir/extfunc.rs
lib/cretonne/src/ir/immediates.rs
lib/cretonne/src/ir/instructions.rs
lib/cretonne/src/ir/jumptable.rs
lib/cretonne/src/ir/valueloc.rs
lib/cretonne/src/isa/intel/binemit.rs
lib/cretonne/src/licm.rs
lib/cretonne/src/regalloc/allocatable_set.rs
lib/cretonne/src/regalloc/pressure.rs
lib/cretonne/src/regalloc/reload.rs
lib/cretonne/src/regalloc/spilling.rs
lib/cretonne/src/result.rs
lib/cretonne/src/simple_gvn.rs
lib/cretonne/src/topo_order.rs
lib/cretonne/src/verifier/mod.rs
lib/filecheck/src/checker.rs
lib/filecheck/src/lib.rs
lib/reader/src/isaspec.rs
lib/reader/src/lexer.rs
lib/reader/src/parser.rs
lib/reader/src/sourcemap.rs

I was curious about [clippy](https://github.com/Manishearth/rust-clippy), a "lint" for Rust. Some its suggestions are fairly subjective, so I didn't try to address everything, but I did fix some that seemed interesting. Here's a PR with the fixes I made, in case you're interested. The patches are orthogonal, so it'd be easy to drop individual patches, if desired (I did end up including a few subjective things). If nothing else, I learned some things about Rust along the way :-).

Lint fixes

---

filetests/verifier/unreachable_code.cton
lib/cretonne/src/verifier/mod.rs

Does not check variable def for unreachable code.
Fixes https://github.com/stoklund/cretonne/issues/108.

Fixed bug in verifier

---

lib/cretonne/meta/cdsl/test_ti.py
lib/cretonne/meta/cdsl/ti.py

Handle bound instructions in pattern type inference

---

lib/cretonne/build.rs
lib/cretonne/src/isa/mod.rs
lib/cretonne/src/regalloc/pressure.rs
lib/cretonne/src/regalloc/solver.rs
lib/reader/src/parser.rs

Eventually will close #13 
This is partially based on work of @dinfuehr  in #32. I've addressed some code review comments, but I need help to figure out how to skip unsupported isa targets in filecheck runner.

[WIP] Conditional compilation of isa targets

---

lib/frontend/src/frontend.rs
lib/frontend/src/ssa.rs

In addition to efficiency, this change also eliminates some nondeterminsm resulting from HashMap key ordering.
However, it does cause the SSA module to require its users to deduplicate predecessors manually.

Change EbbHeaderBlockData's predecessors list from a HashMap to a Vec.

---

lib/wasm/src/code_translator.rs

This entailed reorganizing surrounding code to minimize the extent of
mutable borrows of the control-flow stack.

Use TranslationState's popn/peekn functions.

---

Cargo.toml
lib/native/.gitignore
lib/native/Cargo.toml
lib/native/src/lib.rs

Add a "host" crate for autodetecting the host.

---

README.rst

Add another link to the documentation.

---

docs/langref.rst
lib/cretonne/meta/base/instructions.py

This fixes https://github.com/stoklund/cretonne/issues/20.

Document NaN behavior

---

lib/cretonne/src/isa/arm32/mod.rs
lib/cretonne/src/isa/arm64/mod.rs
lib/cretonne/src/isa/intel/mod.rs
lib/cretonne/src/isa/mod.rs
lib/cretonne/src/isa/riscv/mod.rs

TargetIsa implies a Display of shared and isa-specific flags

---

rustc.rst

This is a start in addressing the feedback [here](https://users.rust-lang.org/t/proposal-rllvm-rust-implementation-of-llvm/16021): it spells out some rustc goals for Cretonne in more detail. I've made an attempt to clarify that the project has some well-scoped goals to keep things realistic in the present, while also having a long-term vision to inspire the future.

Elaborate on Cretonne's rustc backend goals.

---

filetests/isa/intel/binary32-float.cton
filetests/isa/intel/binary32.cton
filetests/isa/intel/binary64-float.cton
filetests/isa/intel/binary64.cton
lib/cretonne/meta/isa/intel/recipes.py
lib/cretonne/src/binemit/memorysink.rs
lib/cretonne/src/binemit/mod.rs
lib/cretonne/src/context.rs
lib/cretonne/src/isa/intel/binemit.rs
lib/filetests/src/test_binemit.rs
lib/filetests/src/test_compile.rs
src/compile.rs

This is a start to implementing a mechanism to allow users to track Trap sites. I'm not totally sure what else folks would want for this, so I figured I'd push early. Feedback welcome.
Let me know if this is a reasonable direction, and I'll clean it up, add tests and so on.
Thanks!

[WIP] Add a Trap sink to code generation

---

lib/native/src/lib.rs

Add support for target_os = "nebulet".

---

lib/codegen/meta/cdsl/types.py

I couldn't figure out how to get docs on the arithmetic functions, but I got it on the type!

document that low bitsize integers don't have complete arithmetic support

---

lib/codegen/meta/base/settings.py
lib/codegen/src/context.rs
lib/codegen/src/lib.rs
lib/codegen/src/nan_canonicalization.rs
lib/codegen/src/settings.rs
lib/codegen/src/timing.rs

This PR intends to fix #311. I have marked some lines that I was unsure about with 'FIXUP' comments, which I would not mind fixing if you have opinions about them. Otherwise, I can simply remove the comments and squash the commits down :)
This passes all of the existing test cases in the `codegen` crate, as well as the top-level crate. I can add more tests if you think that is warranted, but might need some guidance on that front.
Thanks again to @sunfishcode for the guidance, I had a lot of fun doing this!

Issue 311 - Add a pass to make NaN bits deterministic.

---

filetests/isa/x86/optimized-zero-constants-32bit.cton
filetests/isa/x86/optimized-zero-constants.cton
lib/codegen/meta/cdsl/predicates.py
lib/codegen/meta/isa/x86/encodings.py
lib/codegen/meta/isa/x86/recipes.py
lib/codegen/src/predicates.rs

Continuing on from #334, to solve #317. This is rebased off of the current master branch, and squashed the various development commits down.

Optimize 0.0 floating point constants.

---

docs/langref.rst
filetests/isa/x86/legalize-memory.cton
filetests/parser/preamble.cton
lib/codegen/meta/base/instructions.py
lib/codegen/meta/base/legalize.py
lib/codegen/src/context.rs
lib/codegen/src/ir/function.rs
lib/codegen/src/legalizer/mod.rs
lib/codegen/src/write.rs
lib/reader/src/parser.rs

Stack limit checking

---

filetests/isa/x86/binary64.cton
lib/codegen/meta/isa/x86/encodings.py
lib/codegen/meta/isa/x86/recipes.py

bnot encoding for x86

---

Cargo.toml
src/compile.rs
src/cton-util.rs

The `disas` Cargo feature was also introduced, to optionally enable disassembly.

Made Capstone an optional dependency (fixes #382)

---

lib/codegen/meta/base/instructions.py

Two of them were noticed by @angusholder in #160

s/uextend/sextend/ for sload*

---

check-clippy.sh
lib/codegen/meta/check.sh
lib/codegen/meta/gen_instr.py
lib/codegen/src/fx.rs
lib/codegen/src/ir/extname.rs
lib/codegen/src/timing.rs
lib/codegen/src/verifier/locations.rs
lib/module/src/module.rs
lib/reader/src/parser.rs
lib/wasm/src/code_translator.rs
lib/wasm/src/sections_translator.rs
lib/wasm/src/translation_utils.rs

I misread the Clippy report yesterday, and there are actually many more issues to fix. I've got a few ones done, and I'll switch to something else now, to let easy work for other beginners :slightly_smiling_face: .

Moar Clippy fixes

---

lib/entity/src/list.rs

This allocates the entire list at once, rather than pushing one element at a time as is done in `extend`.

Add EntityList::from_slice to build a list from an existing slice

---

lib/wasm/src/code_translator.rs
lib/wasm/src/environ/dummy.rs
lib/wasm/src/environ/spec.rs

... to make it more apparent it's a type that's being returned.

Rename native_pointer() to pointer_type()

---

lib/reader/src/parser.rs

Correctly handle duplicate definitions

---

Cargo.toml
lib/wasm/Cargo.toml
lib/wasm/src/code_translator.rs
lib/wasm/src/environ/dummy.rs
lib/wasm/src/environ/spec.rs
lib/wasm/src/lib.rs
lib/wasm/src/sections_translator.rs
lib/wasm/src/state.rs
lib/wasm/src/translation_utils.rs
lib/wasm/tests/wasm_testsuite.rs
src/clif-util.rs
src/wasm.rs

This fixes https://github.com/CraneStation/cranelift/issues/343.

Use types to distinguish between wasm function body indices and wasm function indices.

---

lib/serde/src/clif-json.rs
lib/serde/src/serde_clif_json.rs

The serde lib needs better documentation in docs.rs in order to be able to update the Cranelift documents and website.

Update serde comments for better documentation.

---

lib/simplejit/src/backend.rs

Allows for host programs to directly expose symbols to jitted code without
needing to deal with platform-specific linker arguments, or dynamic
dispatch.
I've tried this out with my scripting language, and it makes the process for wiring in a function pretty simple.  A call to `SimpleJITBuilder::symbol`, and a call to `Module::declare_function` for one-time setup.  Then, a call to `Module::declare_func_in_func` to introduce the symbol for a given function, and the resulting `FuncRef` can be used during code generation.

Add SimpleJIT internal symbol table.

---

filetests/isa/x86/legalize-br-icmp.clif
lib/codegen/meta-python/base/legalize.py
lib/codegen/src/legalizer/mod.rs

Fixes #448 
I couldn't get this working using regular legalize.
I am not sure whether I should use brz or brnz.

Legalize br_icmp

---

docs/ir.rst

This adds documentation to ir.rst for the newly added table feature, and for special parameters.

Document tables, and special parameters

---

lib/frontend/Cargo.toml
lib/frontend/src/lib.rs
lib/frontend/src/switch.rs

fixes #438
I will add docs tomorrow.

Add a sparse Switch usable instead of JumpTable to cranelift-frontend

---

lib/codegen/src/dominator_tree.rs
lib/codegen/src/flowgraph.rs
lib/codegen/src/ir/dfg.rs
lib/codegen/src/ir/function.rs
lib/codegen/src/ir/layout.rs
lib/codegen/src/ir/mod.rs
lib/codegen/src/loop_analysis.rs
lib/codegen/src/print_errors.rs
lib/codegen/src/regalloc/virtregs.rs
lib/codegen/src/verifier/flags.rs
lib/codegen/src/write.rs
lib/entity/README.md
lib/entity/src/lib.rs
lib/entity/src/map.rs
lib/entity/src/set.rs
lib/entity/src/sparse.rs
lib/frontend/src/frontend.rs
lib/frontend/src/ssa.rs

Rename `EntityMap` to `SecondaryMap`

---

README.md
lib/codegen/Cargo.toml
lib/codegen/meta/src/cdsl/mod.rs
lib/codegen/src/isa/registers.rs
lib/frontend/Cargo.toml
lib/module/Cargo.toml
lib/wasm/Cargo.toml

Remove logging levels restrictions

---

lib/frontend/src/frontend.rs
lib/simplejit/tests/basic.rs

Declare br_table otherwise ebb as predecessor

---

docs/ir.rst
filetests/simple_gvn/readonly.clif
lib/codegen/src/ir/globalvalue.rs
lib/codegen/src/ir/memflags.rs
lib/codegen/src/legalizer/globalvalue.rs
lib/codegen/src/simple_gvn.rs
lib/codegen/src/verifier/mod.rs
lib/reader/src/parser.rs
lib/wasm/src/environ/dummy.rs

Add a `readonly` flag for loads

---

.travis.yml
lib/codegen/meta-python/cdsl/ti.py

Fixes #558 - No more warnings running check.sh with mypy 0.641

Errors reported by mypy 0.641 #558

---

lib/codegen/src/regalloc/virtregs.rs

Eliminate call stack recursion in VirtRegs::find

---

lib/frontend/src/frontend.rs

Also moved creating the `int_type` in `emit_small_memcpy` from outside the loop.

Fix bit count bug in emit_small_{memcpy, memset}.

---

lib/faerie/Cargo.toml
lib/faerie/src/backend.rs

fixes #610 using m4b/faerie#56.

Bump faerie to 0.7.0

---

lib/codegen/src/divconst_magic_numbers.rs
lib/codegen/src/simple_preopt.rs

Just a small cleanup that was sitting silently on my machine. There's no good reason to not use snake case here, so let's do that.

Use snake case for magic numbers computation

---

cranelift-codegen/meta-python/base/instructions.py

From comments in
https://github.com/CraneStation/cranelift/issues/101#issuecomment-461284555

Clarify `br_table`

---

cranelift-module/src/module.rs

This adds an `isa` method and returns the code size from `define_function`. This is a nicer way than #651.

Remove define_function_peek_compiled

---

.travis.yml
Cargo.toml
README.md
cranelift-codegen/Cargo.toml
cranelift-faerie/Cargo.toml
cranelift-frontend/Cargo.toml
cranelift-native/Cargo.toml
cranelift-reader/Cargo.toml
cranelift-simplejit/Cargo.toml
cranelift-wasm/Cargo.toml
fuzz/Cargo.toml

Also update `target-lexicon` to 0.3.0.

Update faerie to 0.9.1

---

cranelift-frontend/src/switch.rs

Optimize switch codegen and improve docs

---

cranelift-codegen/Cargo.toml
cranelift-codegen/meta/Cargo.toml

Work around Cargo #4866.

---

cranelift-codegen/meta-python/base/entities.py
cranelift-codegen/meta-python/cdsl/instructions.py
cranelift-codegen/meta-python/gen_instr.py
cranelift-codegen/meta/src/cdsl/formats.rs
cranelift-codegen/meta/src/cdsl/mod.rs
cranelift-codegen/meta/src/cdsl/operands.rs
cranelift-codegen/meta/src/cdsl/types.rs
cranelift-codegen/meta/src/cdsl/typevar.rs
cranelift-codegen/meta/src/gen_registers.rs
cranelift-codegen/meta/src/gen_settings.rs
cranelift-codegen/meta/src/lib.rs
cranelift-codegen/meta/src/shared/entities.rs
cranelift-codegen/meta/src/shared/formats.rs
cranelift-codegen/meta/src/shared/immediates.rs
cranelift-codegen/meta/src/shared/mod.rs
cranelift-codegen/meta/src/shared/settings.rs
cranelift-codegen/meta/src/shared/types.rs
cranelift-codegen/meta/src/srcgen.rs
cranelift-codegen/meta/src/unique_table.rs

Based off https://github.com/CraneStation/cranelift/pull/705

Port Instructions to meta crate : part 2, typevar and operands

---

cranelift-codegen/meta/src/cdsl/inst.rs
cranelift-codegen/meta/src/cdsl/isa.rs
cranelift-codegen/meta/src/cdsl/mod.rs
cranelift-codegen/meta/src/cdsl/type_inference.rs
cranelift-codegen/meta/src/isa/arm32/mod.rs
cranelift-codegen/meta/src/isa/arm64/mod.rs
cranelift-codegen/meta/src/isa/mod.rs
cranelift-codegen/meta/src/isa/riscv/mod.rs
cranelift-codegen/meta/src/isa/x86/instructions.rs
cranelift-codegen/meta/src/isa/x86/mod.rs
cranelift-codegen/meta/src/lib.rs
cranelift-codegen/meta/src/shared/instructions.rs
cranelift-codegen/meta/src/shared/mod.rs

Based off https://github.com/CraneStation/cranelift/pull/706

Port Instructions to meta ; part 3, Instruction/InstructionGroup + definitions

---

cranelift-codegen/src/isa/arm32/abi.rs
cranelift-codegen/src/isa/arm32/mod.rs

Initial PR of ARM32 so that the unimplemented() call no longer happens and development can begin.

Beginnings of arm32.

---

cranelift-codegen/src/simple_preopt.rs

- don't use camel case but snake casing;
- longer variable names;
- more whitespace;
- add/wrap comments;

Refactor simple-preopt to make it slightly simpler to read;

---

cranelift-preopt/src/constant_folding.rs
filetests/preopt/branch.clif
filetests/preopt/constant_fold.clif

Fix cranelift_preopt panic

---

cranelift-faerie/src/backend.rs
cranelift-module/src/backend.rs
cranelift-module/src/lib.rs
cranelift-simplejit/examples/simplejit-minimal.rs
cranelift-simplejit/src/backend.rs
cranelift-simplejit/tests/basic.rs

Fix #688 by using a similar approach to #321.

cranelift-simplejit: add a translation mechanism for LibCalls

---

cranelift-codegen/src/divconst_magic_numbers.rs

Courtesy of @julian-seward1, thanks for the patch.

Fixes #607: Use a wrapping multiply when computing div/rem magic numbers

---

cranelift-faerie/src/backend.rs
cranelift-module/src/backend.rs
cranelift-module/src/module.rs
cranelift-simplejit/src/backend.rs
cranelift-simplejit/src/memory.rs

This is necessary to fix (some text to prevent auto close) bjorn3/rustc_codegen_cranelift#348

Make it possible to define data alignment

---

cranelift-codegen/meta-python/base/legalize.py
cranelift-codegen/meta/src/cdsl/inst.rs
cranelift-codegen/meta/src/shared/legalize.rs
filetests/isa/x86/legalize-fcvt_from_usint-i16.clif

Legalize fcvt from sint (cont'd)

---

cranelift-codegen/Cargo.toml
cranelift-codegen/src/binemit/mod.rs
cranelift-codegen/src/ir/entities.rs
cranelift-codegen/src/ir/libcall.rs
cranelift-codegen/src/ir/sourceloc.rs
cranelift-entity/src/map.rs
cranelift-wasm/Cargo.toml
cranelift-wasm/src/translation_utils.rs

Needed for wasmtime compilation cache.

Add support for some serde serialization

---

cranelift-entity/Cargo.toml
cranelift-entity/src/primary.rs

Required by module caching code for wasmtime.

Add serde derive to PrimaryMap

---

cranelift-codegen/src/ir/types.rs

Add a unit test for ir::Type::lane_type() for a vector type

---

Cargo.toml
src/bugpoint.rs
src/bugpoint_test.clif
src/clif-util.rs

You should probably run this in release mode, as it is even more slow otherwise.
Fixes #532 
* remove instruction
* replace instruction with single ret val with iconst
* replace instruction with trap
* remove ebb
Edit: added additional shrinking passes

Add bugpoint command

---

cranelift-codegen/src/simple_preopt.rs

It can actually only replace one result; don't try to make it generic
yet, since there's no point in doing so right now, and make it do the
dumb thing so it's not surprising to use.

[codegen] Simplify replace_with_alias' contract and rename it

---

cranelift-codegen/src/binemit/relaxation.rs

Temporarily disable `fold_redundant_jumps`.

---

filetests/isa/x86/binary64.clif
filetests/isa/x86/legalize-br-table.clif

In 1169dc520815fa4a6b1285914748408729a28caa, I forgot to git add the
test file changes.

Revert the test changes too.

---

cranelift-codegen/src/binemit/relaxation.rs

There are bugs in `fold_redundant_jumps` (https://bugzilla.mozilla.org/show_bug.cgi?id=1573792). They don't seem easy to address, because they involve rewriting instructions after register allocation.
Because `fold_redundant_jumps()` really only exists to clean up regalloc cruft for the `basic-blocks` feature, we can feature-gate it on `basic-blocks` to unblock the rest of the team.

Make fold_redundant_jumps() feature-gated on basic-blocks

---

cranelift-module/src/module.rs

Fix documentation typo

---

cranelift-codegen/meta/src/isa/x86/encodings.rs
cranelift-codegen/meta/src/isa/x86/settings.rs
filetests/isa/x86/binary32-float.clif
filetests/isa/x86/binary64-float.clif

Fixes: https://github.com/CraneStation/cranelift/issues/908
/cc @bnjbvr @wingo @caitp

Use roundss/roundsd when available for Ceil/Floor/Trunc/Nearest

---

cranelift-codegen/meta/src/gen_binemit.rs
cranelift-codegen/meta/src/gen_encodings.rs

A simple PR to explain in doc comments what some of the encodings generated code does.

[meta] Generate doc comments for the encodings tables;

---

cranelift-codegen/meta/src/cdsl/formats.rs
cranelift-codegen/meta/src/cdsl/instructions.rs
cranelift-codegen/meta/src/isa/x86/encodings.rs
cranelift-codegen/meta/src/shared/formats.rs
cranelift-codegen/src/binemit/mod.rs
cranelift-codegen/src/binemit/relaxation.rs
cranelift-codegen/src/ir/constant.rs
cranelift-codegen/src/ir/immediates.rs
cranelift-reader/src/parser.rs

[meta] Some random refactorings

---

cranelift-frontend/src/switch.rs

Generate basic-blocks instead of Ebb in frontend::switch.

---

cranelift-frontend/src/frontend.rs
cranelift-frontend/src/lib.rs
cranelift-frontend/src/ssa.rs
cranelift-frontend/src/switch.rs
cranelift-frontend/src/variable.rs
cranelift-simplejit/examples/simplejit-minimal.rs
cranelift-simplejit/tests/basic.rs
cranelift-umbrella/src/lib.rs
cranelift-wasm/src/code_translator.rs
cranelift-wasm/src/environ/dummy.rs
cranelift-wasm/src/func_translator.rs

Removed FunctionBuilderContext from public API.

---

Cargo.toml
cranelift-codegen/src/ir/libcall.rs
cranelift-faerie/src/backend.rs
cranelift-module/src/backend.rs
cranelift-module/src/module.rs
cranelift-object/Cargo.toml
cranelift-object/LICENSE
cranelift-object/README.md
cranelift-object/src/backend.rs
cranelift-object/src/lib.rs
cranelift-object/src/traps.rs
cranelift-simplejit/src/backend.rs

Add cranelift-object

---

cranelift-filetests/src/function_runner.rs

Ref: issue #941 
I will work on simple-jit in a follow-up PR.

Replace region::protect by make_exec in cranelift-filetests

---

cranelift-codegen/src/legalizer/split.rs

This function is responsible for 2.2% of all heap allocation (calls) in CL.
This change avoids most of them (90%, maybe) by using a SmallVec::<[Value;
16]> instead.  The fixed size of 16 was arrived at after profiling with fixed
sizes of 1, 2, 4, 8, 16, 32 and 64.

legalizer/split.rs: split_ebb_params: use SmallVec instead of Vec

---

cranelift-frontend/src/frontend.rs
cranelift-frontend/src/lib.rs
cranelift-frontend/src/ssa.rs
cranelift-frontend/src/switch.rs
cranelift-frontend/src/variable.rs
cranelift-simplejit/examples/simplejit-minimal.rs
cranelift-simplejit/tests/basic.rs
cranelift-umbrella/src/lib.rs
cranelift-wasm/src/code_translator.rs
cranelift-wasm/src/environ/dummy.rs
cranelift-wasm/src/func_translator.rs

As shown in #1018 , #671 caused significant regressions. This PR reverts that change (39e638af99dbe6537bc935bfb1a74669b62877b3).
resolves #1018 #1021

Revert #671

---

.azure-pipelines.yml
README.md
ci/fuzzit.sh
fuzz/fuzz_reader_parse_test.rs

Integrates with [Fuzzit](https://fuzzit.dev/) for automated fuzzing.
Uses the existing fuzz targets:
* translate-module - Fuzz valid WebAssembly modules.
* reader-parse - Fuzz IR text format parsing.
Replaces #944.

Continuous fuzzing

---

cranelift-codegen/src/verifier/mod.rs

Check for types::INVALID in the function signature

---

cranelift-codegen/src/ir/immediates.rs

(Following #1061)
edit: fixes #1064

Remove unused core::mem import in ir::immediates

---

cranelift-bforest/src/pool.rs
cranelift-codegen/src/topo_order.rs
cranelift-codegen/src/verifier/flags.rs
cranelift-entity/src/set.rs

Replaced instances of SparseSet with EntitySet

---

cranelift-codegen/src/ir/trapcode.rs

This PR and version bump is needed for https://github.com/CraneStation/wasmtime/pull/357.

Derive serde traits for TrapCode

---

cranelift-codegen/meta/src/shared/instructions.rs
cranelift-codegen/src/isa/arm32/mod.rs
cranelift-codegen/src/isa/arm64/mod.rs
cranelift-codegen/src/isa/mod.rs
cranelift-codegen/src/isa/riscv/mod.rs
cranelift-codegen/src/isa/x86/mod.rs
cranelift-codegen/src/legalizer/heap.rs

Add conditions to IntCC for checking the carry flag (Carry, NotCarry).
Fixes: https://github.com/CraneStation/cranelift/issues/980
/cc @bnjbvr @wingo @caitp

[codegen] add intcc conditions for reading carry flag

---

cranelift-codegen/meta/src/isa/x86/recipes.rs
cranelift-codegen/meta/src/shared/immediates.rs
cranelift-codegen/meta/src/shared/instructions.rs
cranelift-codegen/shared/src/condcodes.rs
cranelift-codegen/src/isa/x86/binemit.rs
filetests/isa/x86/binary32.clif
filetests/isa/x86/binary64.clif

Add conditions to IntCC for checking the overflow flag (Overflow,
NotOverflow).
/cc @bnjbvr @wingo @caitp @bjorn3

[codegen] add intcc conditions for reading overflow flag

---

cranelift-codegen/src/ir/layout.rs
cranelift-codegen/src/regalloc/coalescing.rs
cranelift-codegen/src/regalloc/coloring.rs
cranelift-codegen/src/regalloc/live_value_tracker.rs
cranelift-codegen/src/regalloc/liveness.rs
cranelift-codegen/src/regalloc/liverange.rs
cranelift-codegen/src/regalloc/spilling.rs
cranelift-codegen/src/value_label.rs
cranelift-codegen/src/verifier/cssa.rs
cranelift-codegen/src/verifier/liveness.rs
cranelift-codegen/src/verifier/locations.rs

This is a set of improvements for LiveRanges, updating comments, trying to make things simpler to understand, etc. Each commit does only one thing, so you can look at it commit per commit. No change in functionality here.

Some LiveRange improvements

---

cranelift-codegen/Cargo.toml
cranelift-codegen/src/binemit/memorysink.rs
cranelift-codegen/src/binemit/stackmap.rs
cranelift-codegen/src/divconst_magic_numbers.rs
cranelift-codegen/src/ir/constant.rs
cranelift-codegen/src/ir/dfg.rs
cranelift-codegen/src/lib.rs
cranelift-codegen/src/scoped_hash_map.rs
cranelift-codegen/src/value_label.rs
cranelift-codegen/src/write.rs
cranelift-entity/src/map.rs
cranelift-frontend/Cargo.toml
cranelift-frontend/src/frontend.rs
cranelift-frontend/src/lib.rs
cranelift-module/Cargo.toml
cranelift-module/src/lib.rs
cranelift-wasm/Cargo.toml
cranelift-wasm/src/lib.rs

Allow building without std

---

cranelift-codegen/meta/src/isa/mod.rs

Addresses https://github.com/CraneStation/cranelift/issues/1082

Change signature of all() function

---

cranelift-codegen/src/regalloc/coalescing.rs
cranelift-codegen/src/regalloc/coloring.rs
cranelift-codegen/src/regalloc/live_value_tracker.rs
cranelift-codegen/src/regalloc/liveness.rs
cranelift-codegen/src/regalloc/liverange.rs
cranelift-codegen/src/regalloc/spilling.rs
cranelift-codegen/src/value_label.rs
cranelift-codegen/src/verifier/cssa.rs
cranelift-codegen/src/verifier/liveness.rs
cranelift-codegen/src/verifier/locations.rs

Explanations are in #1084. @julian-seward1 please take a look!

Use a sorted array for (Ebb, Inst) interval again

---

cranelift-codegen/meta/src/isa/x86/encodings.rs

This avoids Hashmap allocations in the meta crate, and is also more straightforward. Note the cute `let (opcodes, isa_predicate): (&[_], _)` type annotations so that Rustc doesn't infer a fixed-length array type as the first member's type.
@abrown PTAL!

Fixes #1091: Use match statements instead of HashMaps in x86 encodings

---

cranelift-codegen/meta/src/shared/legalize.rs
filetests/isa/x86/br-i128.clif

Fix brz.i128

---

filetests/isa/x86/br-i128-run.clif

Write a run test for brz.i128

---

cranelift-codegen/meta/src/isa/x86/encodings.rs
cranelift-codegen/meta/src/isa/x86/instructions.rs
cranelift-codegen/meta/src/isa/x86/legalize.rs
cranelift-codegen/meta/src/isa/x86/opcodes.rs
cranelift-wasm/src/code_translator.rs
filetests/isa/x86/simd-bitwise-binemit.clif
filetests/isa/x86/simd-bitwise-legalize.clif
filetests/isa/x86/simd-bitwise-run.clif

This depends on some commits from #1104.

Add SIMD shift operators for x86

---

cranelift-frontend/src/ssa.rs

I read through the SSABuilder to learn how it works. While doing so I updated comments to make things more dead-obvious.
The major point of contention is just that `temp_arg_val` is not some arbitrary temporary value, but a local Ebb parameter inserted for purposes of cycle detection.
There's no corresponding issue: this is just a legibility patch.

Increase legibility of the SSABuilder

---

cranelift-codegen/meta/src/cdsl/instructions.rs

Add allow(dead_code) for Immediate until it's used

---

cranelift-codegen/meta/src/cdsl/ast.rs
src/bugpoint.rs
src/cat.rs
src/disasm.rs
src/print_cfg.rs
src/run.rs
src/utils.rs

I find there're so many warnings.

Fix clippy warnings 

---

cranelift-codegen/build.rs

This helps https://github.com/rust-lang/rust/pull/65819

Use slice::iter

---

publish-all.sh

here: discussed internally after agreeing to push #1151.

Update publish-all so it commits on a different branch

---

.azure-pipelines.yml
cranelift-codegen/meta/Cargo.toml
cranelift-codegen/meta/src/cdsl/ast.rs
cranelift-codegen/meta/src/cdsl/mod.rs
cranelift-codegen/meta/src/default_map.rs
cranelift-codegen/meta/src/error.rs
cranelift-codegen/meta/src/gen_inst.rs
cranelift-codegen/meta/src/gen_legalizer.rs
cranelift-codegen/meta/src/gen_registers.rs
cranelift-codegen/meta/src/gen_settings.rs
cranelift-codegen/meta/src/isa/mod.rs
cranelift-codegen/meta/src/lib.rs
cranelift-codegen/meta/src/unique_table.rs
cranelift-codegen/src/ir/constant.rs
test-all.sh

Make cranelift-codegen/meta documentation visible

---

cranelift-frontend/src/variable.rs

There don't seem to be generic parameters for `Variable` anymore

Update outdated documentation

---

cranelift-codegen/meta/src/isa/x86/encodings.rs
cranelift-codegen/meta/src/isa/x86/instructions.rs
cranelift-codegen/meta/src/isa/x86/legalize.rs
cranelift-codegen/meta/src/isa/x86/opcodes.rs
cranelift-reader/src/parser.rs
cranelift-wasm/src/code_translator.rs
filetests/isa/x86/simd-comparison-binemit.clif
filetests/isa/x86/simd-comparison-legalize.clif
filetests/isa/x86/simd-comparison-run.clif

here: _this is part of an ongoing effort to add SIMD support to Cranelift_.
first: _see title._

Add SIMD integer comparisons on x86

---

Cargo.toml
cranelift-bforest/Cargo.toml
cranelift-codegen/Cargo.toml
cranelift-codegen/meta/Cargo.toml
cranelift-codegen/shared/Cargo.toml
cranelift-entity/Cargo.toml
cranelift-faerie/Cargo.toml
cranelift-filetests/Cargo.toml
cranelift-frontend/Cargo.toml
cranelift-module/Cargo.toml
cranelift-native/Cargo.toml
cranelift-object/Cargo.toml
cranelift-preopt/Cargo.toml
cranelift-reader/Cargo.toml
cranelift-serde/Cargo.toml
cranelift-simplejit/Cargo.toml
cranelift-umbrella/Cargo.toml
cranelift-wasm/Cargo.toml
publish-all.sh

This also bumps faerie to 0.12.0 to get past the semver bug in 0.11.1.

Bump version to 0.49.0

---

cranelift-codegen/meta/src/isa/x86/encodings.rs
cranelift-codegen/meta/src/isa/x86/opcodes.rs
cranelift-wasm/src/code_translator.rs
filetests/isa/x86/simd-arithmetic-binemit.clif
filetests/isa/x86/simd-arithmetic-run.clif

This builds on work in #1181; wait to review until that is merged.
here: _no issue, continued SIMD implementation_
first: _see title_

Add x86 SIMD float arithmetic

---

cranelift-filetests/src/test_unwind.rs

This commit removes the dependency on `byteorder::ReadBytesExt`, which can't be
used from `no_std`, which is how we're building the `byteorder` crate.
The fix is to simply offset into the slice as needed rather than using a
`std::io::Cursor`.
Fixes #1225.

Fix the cranelift-filetests build.

---

cranelift-codegen/src/isa/x86/abi.rs

Small refactoring.
I'll repeat a chat comment to @peterhuene about the possibility of not adding the shadow stack space on Win64 fastcall convention if the current function is a leaf function:
> When we're generating the function's prologue/epilogue, it's for the current function, not for a function we're calling as part of generated code. So I assume it would require synchronizing with all the callers of this function; we control direct callers (cranelift -> cranelift calls), but not external callers into cranelift code. For one thing, it would be an issue for Spidermonkey which always generates the shadow stack space when calling into a wasm callee from C++ / JIT code. In general for wasm, knowing the callee is a leaf function would imply having seen the body of the callee, thus …

Hoist the stack alignment and Windows64 fastcall shadow stack space constants

---

cranelift-wasm/src/code_translator.rs

Merges the code for scalar and simd logical operators
Closes #1139 
cc @bnjbvr for review

Merged scalar and simd logical operator

---

cranelift-codegen/meta/src/shared/settings.rs

Fix the doc comment observed in #1247. @iximeow PTAL, thanks!

Fix #1247: Tweak enable_verifier doc comment so it's true

---

cranelift-filetests/src/test_binemit.rs

Hi, This PR resolves #814
r? @bnjbvr

Fix report when output register anontation is missing

---

cranelift-wasm/Cargo.toml
cranelift-wasm/src/code_translator.rs
cranelift-wasm/src/sections_translator.rs

Adds many new operators and a few API changes.

Update wasmparser to 0.45.0

---

filetests/isa/x86/relax_branch.clif
filetests/regalloc/coloring-227.clif

here.
first. PR #1308 was merged with failing tests. This PR fixes those tests by updating them to the new recipe they should use.
`bnjbvr`. The list of suggested reviewers on the right can help you. r? @bnjbvr

Fix master tests

---

Cargo.toml
cranelift-codegen/Cargo.toml
cranelift-faerie/Cargo.toml
cranelift-faerie/src/backend.rs
cranelift-frontend/Cargo.toml
cranelift-native/Cargo.toml
cranelift-object/Cargo.toml
cranelift-object/src/backend.rs
cranelift-reader/Cargo.toml
cranelift-simplejit/Cargo.toml
cranelift-wasm/Cargo.toml
fuzz/Cargo.toml

Update target-lexicon to 0.10

---

cranelift-wasm/src/code_translator.rs

Fix V128AndNot mapping

---

cranelift-wasm/Cargo.toml
cranelift-wasm/src/code_translator.rs
cranelift-wasm/src/sections_translator.rs

This is just a simple dependency version bump plus adjustments for some API changes.

Update to wasmparser 0.47.

---

Cargo.toml
cranelift-bforest/Cargo.toml
cranelift-codegen/Cargo.toml
cranelift-codegen/meta/Cargo.toml
cranelift-codegen/shared/Cargo.toml
cranelift-entity/Cargo.toml
cranelift-faerie/Cargo.toml
cranelift-filetests/Cargo.toml
cranelift-frontend/Cargo.toml
cranelift-module/Cargo.toml
cranelift-native/Cargo.toml
cranelift-object/Cargo.toml
cranelift-preopt/Cargo.toml
cranelift-reader/Cargo.toml
cranelift-serde/Cargo.toml
cranelift-simplejit/Cargo.toml
cranelift-umbrella/Cargo.toml
cranelift-wasm/Cargo.toml
publish-all.sh

Bump version to 0.56.0

---

cranelift-codegen/src/ir/entities.rs

here. Small change
first. This is necessary to store them in `BTreeMap` and `BTreeSet`.

Derive Ord for all entities

---

cranelift-codegen/Cargo.toml
cranelift-filetests/Cargo.toml

here. Small change
first. This updates the gimli dependency to the latest version. This removes a duplicate dependency from cg_clif.

Update gimli to 0.20

---

cranelift-filetests/src/runone.rs

Remove unused import; fixes #1367

---

cranelift-wasm/src/sections_translator.rs
cranelift-wasm/src/translation_utils.rs
wasmtests/ref-func-0.wat

Enable `ref.func` global initializers

---

cranelift-wasm/src/code_translator.rs

These were sitting in my tree for some time.

Catch a few typos in comments

---

cranelift-wasm/Cargo.toml
cranelift-wasm/src/environ/dummy.rs
cranelift-wasm/src/environ/spec.rs
cranelift-wasm/src/lib.rs
cranelift-wasm/src/module_translator.rs
cranelift-wasm/src/sections_translator.rs
cranelift-wasm/src/translation_utils.rs
wasmtests/passive-data.wat
wasmtests/table-copy.wat

first.
This is part of the bulk memory and reference types proposals.

wasm: Add support for passive data and element segments

---

cranelift-reader/src/parser.rs

To fix this case (#951) that may take forever to compile:
```
function %a(){
ebb477777777:
}
```
We decide to define a maximum threshold for the number of blocks in functions.
Based on a large WASM program (https://github.com/mozilla/perf-automation/blob/master/benchmarks/wasm-misc/AngryBots.wasm),
its IR functions does not exceed 1414 blocks. A number 100 times greater (100,000 blocks) seems (currently) enough to define our maximum threshold.
To make this quick benchmark the cranelift-wasm/src/func_translator.rs file has been modified like this:
```
static mut MAX: usize = 0;
pub fn translate_from_reader<FE: FuncEnvironment + ?Sized>(...) {
[...]
builder.finalize();
// the compiler is single threaded
unsafe {
if func.dfg.num_ebbs() > MAX {
MAX = func.dfg.num_ebbs();
println!("MAX {}", …
```

Add maximum threshold for number of blocks per function #951

---

cranelift-wasm/src/environ/dummy.rs
cranelift-wasm/src/environ/spec.rs
cranelift-wasm/src/lib.rs
cranelift-wasm/src/sections_translator.rs
cranelift-wasm/src/translation_utils.rs

rename PassiveElemIndex to ElemIndex and same for PassiveDataIndex
