bytecodealliance/cranelift

.gitignore, src/libcretonne/cfg.rs, src/libcretonne/entities.rs, src/libcretonne/lib.rs
The CFG here is not associated with the Function yet though I'd planned on adding an `Option<ControlFlowGraph>` to the Function struct at a later time.
One bothersome thing here is that the relationship between `Function` and `ControlFlowGraph` is weak. To fix this I think it may be worthwhile to add a `UUID` to each `Function` created. This id could be associated with a CFG at creation and checked each time an operation is performed to ensure that we aren't operating on the wrong `Function`.
=> Control Flow Graph

src/tools/main.rs, src/tools/print_cfg.rs
The command returns parses a .cton file, builds a CFG, and prints it to
stdout in graphviz format.
=> Add a print-cfg subcommand.

lib/cretonne/meta/cretonne/__init__.py
Ran into this while building with my (somewhat unusual) configuration of having `python` refer to `python3` on my machine. `iteritems` was renamed to `items` in Python 3 (and `items` already exists in Python 2) so this code works on both versions (if being slightly more inefficient on Python 2).
=> Use `items` instead of `iteritems` for Python 3 compatibility

docs/compare-llvm.rst, docs/langref.rst, docs/metaref.rst, docs/testing.rst, lib/cretonne/meta/cretonne/base.py, lib/cretonne/meta/cretonne/entities.py
Just finished reading the docs; I've found a few typos, here's a PR fixing those.
=> Fix a few typos in the docs

lib/cretonne/meta/gen_instr.py, lib/cretonne/src/ir/instructions.rs, lib/cretonne/src/verifier.rs
for InstructionData. Use generated `is_terminator()` for `Opcode`
instead. `is_terminator`, `can_trap` and `is_branch` functions are now
public.
fix syntax error
=> remove old `is_terminating` function

docs/langref.rst, docs/regalloc.rst, docs/testing.rst
These were found by the spellchecker.
=> Fix some typos in the documentation

lib/cretonne/src/ir/layout.rs, lib/cretonne/src/ir/progpoint.rs, lib/cretonne/src/regalloc/liverange.rs
LiveRanges represent the live-in range of a value as a sorted
list of intervals. Each interval starts at an EBB and continues
to an instruction. Before this commit, the LiveRange would store
an interval for each EBB. This commit changes the representation
such that intervals continuing from one EBB to another are coalesced
into one.
Fixes #37.
=> Coalesce live range intervals in adjacent EBBs

filetests/parser/instruction_encoding.cton, lib/cretonne/meta/cdsl/ast.py, lib/cretonne/meta/cdsl/formats.py, lib/cretonne/meta/cdsl/instructions.py, lib/cretonne/meta/cdsl/isa.py, lib/cretonne/meta/cdsl/registers.py, lib/cretonne/meta/cdsl/types.py, lib/cretonne/meta/cdsl/xform.py, lib/cretonne/meta/gen_instr.py, lib/cretonne/meta/gen_registers.py, lib/cretonne/meta/isa/__init__.py, lib/cretonne/meta/srcgen.py, lib/reader/src/isaspec.rs, lib/reader/src/parser.rs
Currently only using result_registers to verify that the same number of result registers are specified as there are results, and then throwing it away. I can see they should be parsed with TargetIsa::register_info().parse_regunit() but where then should they be stored?
I'm not sure about adding find_recipe_index to TargetIsa, it seems like something that implementations would want to implement as a hashtable lookup if there are lots of recipes, so maybe is suitable in the trait?
Can we have encodings without registers and registers without encodings? Which of the following definitions would be correct?
encoding ::= "[" (encoding_literal | "-") , (result_registers | "-") "]"
or
encoding ::= "[" encoding_literal, result_registers "]" |
"[-,-]"
=> Added parsing of instruction encodings and result registers specification

filetests/parser/instruction_encoding.cton, lib/reader/src/parser.rs
Issue #24
Some work left to do, and I am currently trying to work out a bug; it seems I am not currently filling in the `function.locations` `EntityMap` properly, as some tests crash with an out-of-bounds access in `write.rs:189:write_instruction()` when trying to stringify a function.
I also want to do some more cleanup, such as possibly moving the code that fills out `function.locations` at the end of `Parser::parse_instruction` into `Parser::add_values`.
I was also going to look at parsing value locations of function arguments (issue #49), but maybe this should be another pull request.
=> Parse ValueLoc for each SSA value result of instructions

filetests/isa/riscv/abi.cton, lib/reader/src/parser.rs
Issue #49
This is pretty much complete, the only thing I wasn't sure about was when to call `Signature::compute_argument_bytes()`, so I went for only calling it if all argument locations were assigned.
=> Added parsing of argument locations for functions and signatures.

filetests/parser/branch.cton, lib/cretonne/src/write.rs
Fixes #63.
`./test-all.sh` actually reports 1 failure right now during filetests, and I think it is `traps_early.cton` that causes problems.
=> Limit type inference for controlling type variables in write.rs

lib/cretonne/meta/base/instructions.py
This is how remainder is defined in C (as of C99), C++ (as of C++11), Rust,
and WebAssembly, for example.
=> Make `srem` have the sign of the dividend.

src/filetest/legalizer.rs, src/filetest/regalloc.rs, src/utils.rs
This changes uses of `write_function` in utility code to use the more general `write!` interface, which ends up calling `write_function` internally. It seems to make sense for utility code to use the more general interface, but feel free to close this if not.
=> Use write! in utility code, rather than calling write_function directly.

check-rustfmt.sh, lib/cretonne/src/binemit/relaxation.rs, lib/cretonne/src/dominator_tree.rs, lib/cretonne/src/entity_list.rs, lib/cretonne/src/ir/builder.rs, lib/cretonne/src/ir/dfg.rs, lib/cretonne/src/ir/instructions.rs, lib/cretonne/src/ir/layout.rs, lib/cretonne/src/isa/encoding.rs, lib/cretonne/src/iterators.rs, lib/cretonne/src/legalizer/boundary.rs, lib/cretonne/src/regalloc/allocatable_set.rs, lib/cretonne/src/regalloc/diversion.rs, lib/cretonne/src/regalloc/solver.rs, lib/cretonne/src/verifier/mod.rs, lib/filecheck/src/checker.rs, lib/reader/src/lexer.rs, lib/reader/src/parser.rs, src/filetest/concurrent.rs, src/filetest/runner.rs
I was just looking around and saw that a new version of rustfmt had been released. Here's the result of updating the check-format script and run the format-all script.
I noticed it sometimes wrapped a few lines into one, which makes things slightly harder to read in some places. Are there any tweaks you'd like me to do in addition to the raw output of format-all?
=> Update rustfmt to 0.8.4

filetests/simple_gvn/basic.cton, lib/cretonne/src/ir/dfg.rs, lib/cretonne/src/ir/layout.rs, lib/cretonne/src/simple_gvn.rs
This addresses a few more items from https://github.com/stoklund/cretonne/pull/79; it resolves aliases as it iterates, and it fixes the cursor position after removing an instruction. With these changes, basic cascading optimizations now work.
=> Fix more GVN issues

lib/reader/src/lexer.rs
=> Remove unnecessary cloned() in reader::lexer::trailing_digits()

lib/cretonne/src/context.rs, lib/cretonne/src/entity_list.rs, lib/cretonne/src/entity_map.rs, lib/cretonne/src/ir/dfg.rs, lib/cretonne/src/lib.rs, lib/cretonne/src/loop_analysis.rs
* Implemented in two passes
* First pass discovers the loops headers (they dominate one of their predecessors)
* Second pass traverses the blocks of each loop
* Discovers the loop tree structure
* Offers a new LoopAnalysis data structure queried from outside the module
=> Loop analysis of the IL

filetests/licm/basic.cton, filetests/licm/complex.cton, filetests/licm/multiple-blocks.cton, filetests/licm/nested_loops.cton, lib/cretonne/src/context.rs, lib/cretonne/src/lib.rs, lib/cretonne/src/licm.rs, lib/cretonne/src/loop_analysis.rs, src/filetest/licm.rs, src/filetest/mod.rs
* Uses loop analysis to detect loop tree
* For each loop (starting with the inner ones), create a pre-header and move there loop-invariant instructions
* An instruction is loop invariant if it does not use as argument a value defined earlier in the loop
* File tests to check LICM's correctness
I'm sorry, for some reason GitHub detects conflict for the small style change implemented by 7b7bd7d.
=> LICM pass 

docs/compare-llvm.rst, docs/langref.rst, docs/regalloc.rst, docs/testing.rst, lib/cretonne/meta/base/instructions.py, lib/reader/src/parser.rs
While reading the docs, I noticed that the documentation for `_imm` instructions isn't entirely consistent. This PR fixes a few examples of this. Are you interested in fixing all the `_imm` instructions this way, or would you prefer to factor this text out somehow?
=> Documentation fixes

lib/cretonne/meta/cdsl/test_typevar.py, lib/cretonne/meta/cdsl/typevar.py, lib/cretonne/src/bitset.rs, lib/cretonne/src/ir/instructions.rs, lib/cretonne/src/lib.rs
As part of a better type inference we need to compute the image (and pre-image) of TypeSets across derivation functions. This computation across the as_bool function can result in a typeset containing disjoint intervals. E.g.:
TypeSet(..., ints=(8,16), bools=(64,64)).as_bool() = TypeSet(bools={ (8,16) , (64,64) })
This examples suggests that we need to support general sets in each component of the TypeSet datastructure. TypeSet gets lowered down to ValueTypeSet in Rust so a similar change is needed there.
In python we use the built-in set() type. In rust we make a BitSet tuple struct wrapping around a u8/u16 (can be expanded to larger types if needed).
=> Convert interval sets inside TypeSet/ValueTypeSet in general sets

lib/cretonne/meta/base/types.py, lib/cretonne/meta/cdsl/instructions.py, lib/cretonne/meta/cdsl/test_typevar.py, lib/cretonne/meta/cdsl/types.py, lib/cretonne/meta/cdsl/typevar.py, lib/cretonne/meta/cdsl/xform.py, lib/cretonne/meta/gen_instr.py
This PR only adds forward image computations of typesets. This allows us to compute the concrete typeset for any derived type var. As a result, TypeVar.singleton_type can be computed from the typeset for any type var. Therefore we can replace it with a identically named function. This (i think) takes care of the following todo in TypeVar.constrain_type():
-            # TODO: What if a.type_set becomes empty?
-            if not a.singleton_type:
-                a.singleton_type = b.singleton_type
=> Add image computation of typesets; Remove TypeVar.singleton_type

lib/cretonne/meta/cdsl/test_typevar.py, lib/cretonne/meta/cdsl/types.py, lib/cretonne/meta/cdsl/typevar.py
Add computation of inverse image of typeset across a derived function - TypeSet.map_inverse; 
Change TypeVar.constrain_type to perform a more-general computation using inverse images of TypeSets;
Tests for map_inverse;
Cleanup ValueType.get_names to with_bits form previous PR;
=> Add inverse image computation for TypeSets and generalize TypeVar.constrain_types

lib/cretonne/meta/cdsl/ast.py, lib/cretonne/meta/cdsl/test_ti.py, lib/cretonne/meta/cdsl/test_typevar.py, lib/cretonne/meta/cdsl/ti.py, lib/cretonne/meta/cdsl/typevar.py, lib/cretonne/meta/cdsl/xform.py
This PR builds on top of PRs #104 and PR #105 and fills in the blanks in type inference. Specifically:
1) TI is separated from TypeVar/XForm code in its own file (ti.py)
2) More general unification between derived type variables(tvs) that:
- normalizes derived TVs that involve bijective functions
- unifies derived tvs with bijective derivation functions by unifying one's base with the other's inverse image
3) Support for constraints between non-bijective derived tvs. This is useful for both handling equivalence between as_bool() derived tvs, as well as future use cases (e.g. width constraints in uextend, sextend, itrunc)
4) The ti code doesn't depend on having a single controlling tv
5) We add an enumerator for all concrete possible typings for an XForm. The enumerator respects …
=> Add better type inference and encapsulate it in its own file

lib/cretonne/meta/cdsl/test_ti.py, lib/cretonne/meta/cdsl/test_typevar.py, lib/cretonne/meta/cdsl/ti.py, lib/cretonne/meta/cdsl/typevar.py, lib/cretonne/meta/cdsl/xform.py
This PR addresses several comments in PR #110. Concretely:
Cleanup typos;
Remove SAMEAS;
More descriptive rank comments;
Introduce explicit sorting in free_typevars()
Move TV safety asserts in TypeVar.derived() - as per the comment in TypeEnv.normalize_tv about cancellation, whenever we create a TypeVar we must assert that there is no under/overflow. To make sure this happen _always_ move the safety checks to TypeVar.derived(), which is called along all paths.
=> Cleanup for several comments in PR #110

lib/cretonne/meta/cdsl/ast.py, lib/cretonne/meta/cdsl/test_ti.py, lib/cretonne/meta/cdsl/ti.py, lib/cretonne/meta/cdsl/xform.py, lib/cretonne/meta/gen_instr.py, lib/cretonne/meta/gen_legalizer.py, lib/cretonne/meta/test_gen_legalizer.py, lib/cretonne/src/ir/instructions.rs, lib/cretonne/src/ir/types.rs, lib/cretonne/src/legalizer/mod.rs
This PR emits runtime type checks for patters in legalizer.rs. Specifically it emits checks under 2 conditions:
1) A most-general type of a var v in a XForm(r1,r2) is more constraint then its most general type in just r1. For these cases, the fact that r1 is valid RTL is not sufficient to determine if XForm applies. We need to emit a check of the type typeof_v \in TS where TS is the typeset of v in the XForm
2) During type checking we may generate constraints between derived type vars that have non-bijective derived functions (e.g. as_bool). For those, we can't simply propagate the constraint up by constraining the root free variables, and instead must add an explicit runtime check.
In the future, we will add more  constraints. The for example we will need constraints for the following …
=> Emit runtime type checks in legalizer.rs

lib/cretonne/meta/base/instructions.py, lib/cretonne/meta/cdsl/instructions.py, lib/cretonne/meta/cdsl/test_ti.py, lib/cretonne/meta/cdsl/ti.py, lib/cretonne/meta/cdsl/types.py, lib/cretonne/meta/gen_legalizer.py, lib/cretonne/meta/test_gen_legalizer.py, lib/cretonne/src/ir/types.rs
This PR does several things:
1. Add a fix for #114 - Add `ConstrainWiderOrEqual`
2. Adds the ability for `Instructions` to have constraints, and add a `ConstrainWiderOrEqual` to `ireduce`,`{s,u}extend` and `f{promote,demote}`
3. Reduce code duplication in `TypeConstraint` subclasses
4. Modify runtime constraint checks to reject match when they encounter overflow
5. Fix a small bug in emitting constraint edges in `TypeEnv.dot()`;
=> Add fix for #114

lib/cretonne/meta/cdsl/test_ti.py, lib/cretonne/meta/cdsl/ti.py, lib/cretonne/meta/semantics/__init__.py, lib/cretonne/meta/semantics/primitives.py, lib/cretonne/meta/semantics/test_elaborate.py, lib/cretonne/meta/test_gen_legalizer.py
When unifying 2 type variables(tvs), type inference (ti) uses a heuristic partial ordering over tvs to select which is the representative. Currently derived tvs are selected over non-derived tvs in an effort to
reduce the number of free tvs. Unfortunately, this sometimes results in inferred types for XForms that express tvs in source as functions of tvs in dst. This violates a basic constraint of XForms. This was observed in the following example:
```
XForm(Rtl(x << iconst(y)),
Rtl(x1 << iconst(y),
x2 << iconst(y),
x << vconcat (x1, x2)))
```
The current ti code took T_x1 as a free tv and inferred the type of x as T_x1.double_vector(), instead of picking T_x as a free typevar and inferring the type of x1/x2 as T_x.half_vector().
In this PR we change the way we compute the partial ordering …
=> Change TV ranking to select src vars as a representative during unification

lib/cretonne/meta/base/instructions.py, lib/cretonne/meta/base/semantics.py, lib/cretonne/meta/cdsl/ast.py, lib/cretonne/meta/cdsl/test_ti.py, lib/cretonne/meta/cdsl/ti.py, lib/cretonne/meta/cdsl/xform.py, lib/cretonne/meta/semantics/elaborate.py, lib/cretonne/meta/semantics/primitives.py, lib/cretonne/meta/semantics/smtlib.py, lib/cretonne/meta/semantics/test_elaborate.py, lib/cretonne/meta/test_gen_legalizer.py
This PR adds bug fixes and machinery neccessary to express semantics of RTLs as smtlib queries for equivalence checking. In detail:
1) bug fixes in TI to make sure tvs in a dest pattern are always expressed as a function of the free tvs in the source pattern
2) cleanup - moving some routines such as apply(), is_concrete_rtl() and cleanup_concrete_rtl() from semantics/elaborate() to better suited locations in cdsl/xforms.py
3) smtlib.py - routines for emitting queries for concretely typed Rtls
4) Stricter constraints for binary conversion instructions
5) additional semantic primitives and semantics for some arithmetic instructions, sufficient to emit queries checking iadd legalizations.
=> Add more semantics and utilities to emit smtlib queries

filetests/isa/intel/binary64.cton, lib/cretonne/meta/base/instructions.py, lib/cretonne/meta/isa/intel/encodings.py, lib/cretonne/src/isa/intel/binemit.rs
Encoding recipes factored with 32 bits instructions, corresponding tests added.
=> Added Intel x86-64 encodings for 64bit loads and store instructions

lib/cretonne/src/ir/immediates.rs, lib/frontend/src/ssa.rs
This eliminates the need for unsafe code in code that uses Cretonne, a few
instances of unsafe code in Cretonne itself, and eliminates the only instance
of floating point in Cretonne.
As proposed here, this is an API change, requiring Cretonne users to update. I've prepared a patch [here](https://github.com/sunfishcode/wasm2cretonne/commit/65585485d8c9073dabda65e69d76f709394f67e1) for wasm2cretonne.
=> Avoid floating-point types in Ieee32::new and Ieee64::new.

docs/example.cton, docs/langref.rst, filetests/isa/intel/abi64.cton, filetests/isa/intel/binary32.cton, filetests/isa/intel/binary64.cton, filetests/isa/riscv/abi-e.cton, filetests/isa/riscv/abi.cton, filetests/isa/riscv/binary32.cton, filetests/isa/riscv/legalize-abi.cton, filetests/isa/riscv/parse-encoding.cton, filetests/licm/basic.cton, filetests/licm/complex.cton, filetests/parser/branch.cton, filetests/parser/call.cton, filetests/parser/instruction_encoding.cton, filetests/parser/keywords.cton, filetests/parser/rewrite.cton, filetests/parser/tiny.cton, filetests/regalloc/spill.cton, lib/cretonne/src/ir/extfunc.rs, lib/cretonne/src/ir/function.rs, lib/cretonne/src/ir/mod.rs, lib/cretonne/src/write.rs, lib/frontend/src/frontend.rs, lib/frontend/src/lib.rs, lib/reader/src/parser.rs, tests/cfg_traversal.rs
A CallConv enum on every function signature makes it possible to
generate calls to functions with different calling conventions within
the same ISA / within a single function.
The calling conventions also serve as a way of customizing Cretonne's
behavior when embedded inside a VM. As an example, the SpiderWASM
calling convention is used to compile WebAssembly functions that run
inside the SpiderMonkey virtual machine.
All function signatures must have a calling convention, so this changes
the textual IL syntax. The syntax for declaring a function signature
replaces the "signature" keyword with the calling convention.
Before:
sig1 = signature(i32, f64) -> f64
After
sig1 = native(i32, f64) -> f64
sig2 = spiderwasm(i32)
When printing functions, the signature goes between the function name …
=> Add a calling convention to all function signatures.

lib/cretonne/src/dominator_tree.rs, lib/cretonne/src/flowgraph.rs, lib/cretonne/src/verifier/mod.rs
Implemented via striding RPO numbers and renumbering in worst case.
=> Added partial recompute of dominator tree in case of Ebb splitting 

lib/cretonne/src/verifier/mod.rs
This was a blind spot in the verifier, because of it I missed a bug in the `wasm2cretonne` translation.
=> Verifier now checks it branch target ebbs are inserted in the layout

lib/cretonne/meta/base/semantics.py, lib/cretonne/meta/cdsl/ast.py, lib/cretonne/meta/cdsl/instructions.py, lib/cretonne/meta/cdsl/operands.py, lib/cretonne/meta/cdsl/test_xform.py, lib/cretonne/meta/cdsl/xform.py, lib/cretonne/meta/gen_legalizer.py, lib/cretonne/meta/semantics/__init__.py, lib/cretonne/meta/semantics/elaborate.py, lib/cretonne/meta/semantics/macros.py, lib/cretonne/meta/semantics/primitives.py, lib/cretonne/meta/semantics/smtlib.py, lib/cretonne/meta/semantics/test_elaborate.py
This PR proposes a fix for #141. Namely it:
- Adds a new `Expr` subclass `Literal`, (base class for `ConstantInt`, `Enumerator`...)
- Adds support for substitutions `Var`->`Literal`, `Literal`->`Var` in {`Ast`, `Def`,`Rtl`}.{`copy()`, `substitution()`}
- Changes `verify_semantics()` to enumerate all concrete values of enumerable immediates on top of enumerating all concrete typings.
- As a proof of concept, adds correct semantics for `icmp`, along with the necessary primitives
- Additional type checking for `Literal` kinds in `Apply.__init__()`
=> Fix for  #141

lib/cretonne/src/entity/map.rs, lib/cretonne/src/ir/entities.rs, lib/frontend/src/ssa.rs
Current measurements show that memory usage is approximately the same,
and it's about 20% faster.
=> Replace SSABuilder's variables HashMaps with EntityMaps.

lib/wasm/Cargo.toml, lib/wasm/src/code_translator.rs, lib/wasm/src/func_translator.rs, lib/wasm/src/module_translator.rs
The highlight of this patch is the removal of `translate_function_body` which has been subsumed by `FuncTranslator`.
=> Change translate_module to use FuncTranslator.

format-all.sh, test-all.sh
This avoids the need to list all the packages in test-all.sh.
=> Use --all in some scripts.

lib/reader/src/parser.rs
No current tests actually rely on this, and it's surprising.
=> Don't silently ignore argument or value locations.

lib/cretonne/src/context.rs, lib/cretonne/src/dominator_tree.rs, lib/cretonne/src/flowgraph.rs, lib/cretonne/src/legalizer/mod.rs, lib/cretonne/src/licm.rs, lib/cretonne/src/loop_analysis.rs, lib/cretonne/src/regalloc/context.rs, lib/cretonne/src/simple_gvn.rs, lib/cretonne/src/verifier/mod.rs, lib/wasm/src/func_translator.rs, src/filetest/legalizer.rs, src/filetest/licm.rs, src/filetest/regalloc.rs, src/filetest/simple_gvn.rs, src/wasm.rs
This avoids ambiguity about whose responsibility it is to run
to compute cfg, domtree, and loop_analysis data.
=> Make passes assert their dependencies consistently.

lib/reader/src/error.rs, lib/reader/src/lib.rs, src/cton-util.rs, src/wasm.rs
This implements the full parsing for `set` and `isa` commands, following the [feedback](https://github.com/stoklund/cretonne/pull/155#issuecomment-329295426).
=> Add settings and isa command-line options to cton-util wasm.

filetests/isa/intel/binary64.cton, lib/cretonne/meta/check.sh, lib/cretonne/meta/isa/intel/encodings.py, lib/cretonne/meta/isa/intel/recipes.py, lib/cretonne/meta/isa/intel/registers.py, lib/cretonne/src/isa/constraints.rs, src/filetest/binemit.rs
This isn't done yet, I was wondering what the best way is to tell that an instruction needs a REX encoding due to REX.w? Can it be done in a general way, or should this be intel-specific? For context, the tests current fail on:
FAIL filetests/isa/intel/binary64.cton: binemit(%I64): Bad machine code for inst159: v141 = bint.i64 v121
Want: 48 0f b6 cb
Got:  0f b6 cb
The way I'm currently checking constraints does feel like it could be generalised somewhat.
=> Choose compressed instruction encodings where constraints allow

README.rst, docs/langref.rst
This PR proposes that load/store/etc. become plain native unchecked memory accesses, without reliable trapping, and with full UB on OOB.
Verifiable safety may be had by using a heap_addr/stack_addr/global_addr immediately before every raw access. Bounds-check elimination optimizations may be performed by using a single heap_addr/stack_addr/global_addr for multiple accesses. Load DCE and DSE can be performed on normal load/store/etc. in the usual ways.
=> Clarify undefined behavior and notrap.

docs/langref.rst, filetests/isa/intel/allones_funcaddrs32.cton, filetests/isa/intel/allones_funcaddrs64.cton, filetests/isa/intel/binary32.cton, filetests/isa/intel/binary64.cton, filetests/isa/intel/legalize-memory.cton, filetests/parser/memory.cton, lib/cretonne/meta/base/instructions.py, lib/cretonne/meta/base/settings.py, lib/cretonne/meta/isa/intel/encodings.py, lib/cretonne/meta/isa/intel/recipes.py, lib/cretonne/src/binemit/memorysink.rs, lib/cretonne/src/binemit/mod.rs, lib/cretonne/src/ir/extfunc.rs, lib/cretonne/src/ir/extname.rs, lib/cretonne/src/ir/function.rs, lib/cretonne/src/ir/globalvar.rs, lib/cretonne/src/ir/mod.rs, lib/cretonne/src/legalizer/globalvar.rs, lib/cretonne/src/settings.rs, lib/cretonne/src/write.rs, lib/frontend/src/frontend.rs, lib/frontend/src/lib.rs, lib/reader/src/parser.rs, lib/wasm/src/environ/dummy.rs, lib/wasm/src/environ/spec.rs, lib/wasm/src/func_translator.rs, src/filetest/binemit.rs, src/filetest/compile.rs
This fixes #182. As it currently stands, it also makes several API changes that baldrdash would probably need to be updated for:
- rename `FunctionName` to `ExternalName`
- add a `reloc_globalsym` to any `RelocSink` impls (which could probably just panic since the frontend in that case wouldn't ever generate a globalsym)
- enable the `allones_funcaddrs` setting
=> Add support for symbolic global variables.

lib/cretonne/src/context.rs, lib/cretonne/src/flowgraph.rs, lib/cretonne/src/regalloc/coalescing.rs, lib/cretonne/src/regalloc/coloring.rs, lib/cretonne/src/regalloc/context.rs, lib/cretonne/src/regalloc/liveness.rs, lib/cretonne/src/regalloc/reload.rs, lib/cretonne/src/regalloc/solver.rs, lib/cretonne/src/regalloc/spilling.rs, lib/cretonne/src/topo_order.rs
This includes adding `clear()` functions to its (transitive) members.
=> Add a 'clear()' function to Context.

lib/frontend/src/frontend.rs, lib/frontend/src/lib.rs, lib/wasm/src/func_translator.rs
This has the advantage of not triggering assertion failures in the event
of abandoning a partially-built function. It has the disadvantage of
requiring users to call finalize() explicitly.
This is a followup to https://github.com/stoklund/cretonne/issues/192. Unfortunately, there isn't an obvious thing to return a state value. I looked at using the `Function` for this, but when used with `Context` which owns its `Function`, it's not possible for the `FunctionBuilder` to temporarily own it so that it can be returned. I'd be happy to implement something else if anyone has any better ideas.
=> Replace FunctionBuilder's Drop impl with a finalize function.

filetests/isa/intel/abi64.cton, filetests/isa/intel/legalize-memory.cton, filetests/parser/memory.cton, filetests/regalloc/iterate.cton, lib/cretonne/src/ir/extname.rs, lib/cretonne/src/write.rs, lib/frontend/src/frontend.rs, lib/frontend/src/lib.rs, lib/reader/src/lexer.rs, lib/reader/src/parser.rs, lib/wasm/src/environ/dummy.rs, lib/wasm/src/func_translator.rs
Implements proposal discussed in https://github.com/stoklund/cretonne/issues/194
The `LibCall` variant is not implemented. I can implement it if you'd like.
The only major change not discussed there was that TestCase is 16 ascii characters, instead of 10, in order to prevent me from having to go change the dozen or so filetests that use testcase names that are between 10 and 16 characters long. None were over 16 characters.
I removed `wat2wasm` from my PATH to get all tests to pass for this PR. I will make a separate PR next week that fixes up what appear to be some minor issues with the wasm tests.
Have a happy thanksgiving!
=> Change representation of ir::ExternalName

lib/wasm/tests/testsuite.rs, wasmtests/icall.wat
You will need `wat2wasm` installed on your machine to ensure these tests run.
I also added a few lines of code to make the filetests ignore files starting with `.` so that it doesnt try to run vim .swp files, but perhaps the correct behavior is to just ignore files that dont start with wat or wasm, instead of panicking?
We should install wat2wasm on the CI environment so this doesn't get ignored in the future - I'll open an issue so we can discuss how to do that.
=> Fix wat syntax so wasm tests pass

lib/cretonne/meta/isa/intel/recipes.py, lib/cretonne/meta/isa/riscv/recipes.py, lib/cretonne/src/binemit/mod.rs, lib/cretonne/src/isa/arm32/binemit.rs, lib/cretonne/src/isa/arm32/mod.rs, lib/cretonne/src/isa/arm64/binemit.rs, lib/cretonne/src/isa/arm64/mod.rs, lib/cretonne/src/isa/intel/binemit.rs, lib/cretonne/src/isa/intel/mod.rs, lib/cretonne/src/isa/mod.rs, lib/cretonne/src/isa/riscv/binemit.rs, lib/cretonne/src/isa/riscv/mod.rs, src/filetest/binemit.rs
Rather than use a struct-wrapped integer to encode an architecture-specific relocation type, this PR instead makes an enum that has all of the relocation types needed by all of the architectures. This way, the relocation can be made public to crate users without having to expose any of the isa binemit internals.
Common types (like `Call`, which is the same for arm32, arm64, and riscv) is given one enumeration value for each architecture that uses it, so that its easier for individual architectures to change how their relocations work without breaking others.
The enumeration has a `Display` trait that drops the architecture name, so that the output text is identical to the static string array previously used. This also allowed us to drop the `reloc_names` function from the `TargetIsa` …
=> refactor Reloc to an enum of every architecture's reloc types

filetests/isa/intel/binary64-pic.cton, lib/cretonne/meta/base/settings.py, lib/cretonne/meta/isa/intel/encodings.py, lib/cretonne/meta/isa/intel/recipes.py, lib/cretonne/src/binemit/mod.rs, lib/cretonne/src/isa/intel/binemit.rs, lib/cretonne/src/settings.rs
This PR adds support for PIC code generation to the Intel 64-bit isa.
* A boolean setting "is_pic" is added to the base settings.
* The relocation types required for PIC are added to the Reloc enum.
* Added the appropriate recipes and encodings to the intel isa.
* Added a filetest for testing the encoding of the instructions added.
=> Position-Independent Code

filetests/isa/intel/binary64-pic.cton, lib/cretonne/meta/isa/intel/recipes.py, lib/cretonne/meta/isa/riscv/recipes.py, lib/cretonne/src/binemit/memorysink.rs, lib/cretonne/src/binemit/mod.rs, src/filetest/binemit.rs, src/filetest/compile.rs
The new IntelGOTPCRel4 directly corresponds to R_X86_64_GOTPCREL, except that it also implies an implicit `- 4` to account for the difference between the end of an instruction (where the PC is considered to be in PC-relative on intel) and the immediate field. That's the right thing to do for faerie right now, as faerie currently adds the -4 [itself](https://github.com/m4b/faerie/blob/bfb3d90443efec6773aa39a93c366d2e23489bf1/src/elf.rs#L480), however it's subtle and makes Cretonne's code less consistent with x86-64 ABI documentation.
I think it makes sense to add an addend field to `reloc_external`, and use it to move the responsibility for adding addends into Cretonne.
This change breaks cretonne+faerie users at present, so we shouldn't merge this PR yet. Faerie's relocation API is [still …
=> Align IntelGOTPCRel4 with R_X86_64_GOTPCREL

src/wasm.rs
Allows to split `cton-util wasm` into two stages:
```
cton-util wasm -pt --set=is_64bit  foo.wasm > foo.cton
cton-util compile -p --set=is_64bit --isa="intel haswell" foo.cton 
```
=> Allow to print translated wasm file.

lib/cretonne/meta/cdsl/registers.py, lib/cretonne/meta/gen_registers.py, lib/cretonne/meta/isa/intel/recipes.py, lib/cretonne/meta/isa/intel/registers.py
This PR addresses #211.
The encoding used in the `ld` recipe on x64 is for zero-offsets loads. However, the encoding is invalid for `r13` and `rbp` as it has been reused for RIP-relative loads. This PR makes `r13` and `rbp` invalid registers for that recipe.
In order to do that, the internal representation of RegClass had to be changed from a range of register units to a bitmap of register units, as this becomes a non-contiguous class.
Side Note: I was hoping that this would cause the code generator to generate the longer 8-bit displacement encoding for loads from r13, but it looks like instead it copies the value into another register and then loads from that one. Not sure if it's worth trying to address that here.
=> Illegalize rbp/r13 for zero-offset loads on Intel x64

filetests/isa/intel/binary64-pic.cton, lib/cretonne/meta/isa/intel/recipes.py
Hello!
Currently the addend for PLTRel4 relocation that we output for position-independent calls has an incorrect addend. After linking this causes it to jump 4 bytes past the beginning of the PLT thunk, leading to "fun".
This PR corrects the addend and the test for it. Thanks!
=> Fix the relocation addend for PIC calls on Intel

filetests/isa/intel/legalize-memory.cton, lib/cretonne/src/legalizer/heap.rs
During the expansion of a static heap lookup Cretonne checks whether an address can be statically determined to be out of bounds, and emits an unconditional trap in place of the lookup. This is great, but the problem is that `trap` is a terminator instruction and now falls into the middle of an Ebb. And so compilation fails with: 
```
a terminator instruction was encountered before the end of ebb11
```
This patch splits the Ebb after emitting the trap. However, this breaks cfg and the domtree and probably everything else too. So, in addition, we also recompute the cfg, the domtree, and run the unreachable code elimination pass as well.
I'm sure there's a more efficient way to handle this, but it was not clear at first glance. Happy to change this to make it less brute-force.
Thanks!
=> Fix static heap oob traps

lib/cretonne/src/context.rs
This is a much simpler change that makes it obvious that a Context can be created and some arbitrary Function can be put into it. Without a constructor I wasn't sure whether there was some invariant (which is my bad, I didn't fully understand what Context was for, the docs should have been enough).
=> cretonne::Context: add for_function constructor

lib/cretonne/meta/isa/intel/recipes.py, lib/cretonne/meta/isa/intel/registers.py
I found another issue similar to the RBP/R13 issue (#211).
The encoding of R12 in dereferencing loads and stores is equivalent to the combination of bits that indicate the presence of a SIB-byte. So, Intel does the logical thing and requires that a SIB byte be appended to the instructions. 
Unfortunately, this doesn't just affect zero-offset loads and stores like the last one, but all of them. You can see what I mean below...
Zero-offset:
```
0:  41 89 18                mov    DWORD PTR [r8],ebx
3:  41 89 19                mov    DWORD PTR [r9],ebx
6:  41 89 1a                mov    DWORD PTR [r10],ebx
9:  41 89 1b                mov    DWORD PTR [r11],ebx
c:  41 89 1c 24             mov    DWORD PTR [r12],ebx
10: 41 89 5d 00             mov    DWORD PTR [r13+0x0],ebx
14: 41 89 1e …
```
=> Restrict R12 dereferencing

lib/cretonne/Cargo.toml, lib/cretonne/README.md, lib/frontend/Cargo.toml, lib/frontend/README.md, lib/frontend/src/lib.rs, lib/native/Cargo.toml, lib/native/README.md, lib/reader/Cargo.toml, lib/reader/README.md, lib/wasm/Cargo.toml, lib/wasm/README.md
This will put descriptions on the packages' crates.io pages.
=> Add minimal README.md files to published crates.

lib/wasm/src/environ/dummy.rs, src/cton-util.rs, src/wasm.rs
This implements the idea presented in #244, including recording the bytecode size of each function when it's read in the DummyEnvironment (I don't think we need it in other environment?).
I sparkled a few `\n` in the code because it visually helped me understanding parts of the code that are related to each other as well (also a nice side-effect: makes motion in vim much easier with `{` and `}`). Happy to revert these changes if you prefer the tighter formatting.
@stoklund, can you have a look please? Thanks!
=> Fixes #244: Prints the generated code/wasm bytecode size with -s

lib/wasm/src/code_translator.rs
This showed up in clippy warnings as the code for this case was
the same as for `I64Extend8S`.
=> I64Extend16S should operate on 16 bits, not 8.

lib/frontend/src/frontend.rs, lib/frontend/src/lib.rs, lib/frontend/src/variable.rs, lib/wasm/src/func_translator.rs
Hey, this is my first PR with the Cretonne project, please let me know if there's something I should do that I didn't.
I picked up issue [#266](https://github.com/Cretonne/cretonne/issues/266) and renamed ILBuilder
to `FunctionBuilderContext` as per the suggestion from the issue.
I ran `test-all.sh` and everything seems to be fine.
=> Rename `ILBuilder` to `FunctionBuilderContext`

lib/cretonne/meta/isa/intel/defs.py, lib/cretonne/meta/isa/intel/encodings.py
Addressing [issue 265](https://github.com/Cretonne/cretonne/issues/265)
I'm not sure if there are any other references to `I32` and `I64` that I missed, if there are please let me know!
=> Rename `I32` -> `X86_32` and `I64` -> `X86_64`

check-rustfmt.sh
**Disclaimer**: I'm not a bash wizard and I have no idea what I'm doing.
There are two cases:
1. It seems that grep on macOS exits as soon as it finds the first match. This makes cargo unhappy and it prints message like "failed printing to stdout: Broken pipe (os error 32)". The solution is to fully consume the output from cargo. I choose to use tee for this task.
2. When in a strict mode, bash complains that $1 is not defined (when it's actually not defined in case of omitting --install). The solution is to apply bash substitution magic: when $1 is undefined or set to null substitute it with empty string.
=> Fix check-rustfmt.sh for macOS

filetests/isa/intel/baseline_clz_ctz_popcount.cton, filetests/isa/intel/binary32.cton, filetests/isa/intel/binary64.cton, filetests/isa/intel/legalize-div-traps.cton, filetests/isa/intel/legalize-div.cton, lib/cretonne/meta/isa/intel/encodings.py
Closes #274
I think the tests are correct. I wasn't able to put the shift-immediate encoding test right next to the shift tests because of value naming (at least, without renaming all subsequent values), which is slightly annoying.
=> Implement shift-immediate encodings for x86

docs/testing.rst, filetests/dce/basic.cton, filetests/isa/intel/binary32.cton, filetests/isa/intel/binary64.cton, filetests/postopt/basic.cton, filetests/preopt/simplify.cton, filetests/regalloc/coloring-227.cton, filetests/verifier/flags.cton, lib/cretonne/meta/isa/intel/encodings.py, lib/cretonne/meta/isa/intel/recipes.py, lib/cretonne/src/context.rs, lib/cretonne/src/dce.rs, lib/cretonne/src/ir/immediates.rs, lib/cretonne/src/isa/intel/mod.rs, lib/cretonne/src/isa/mod.rs, lib/cretonne/src/lib.rs, lib/cretonne/src/postopt.rs, lib/cretonne/src/preopt.rs, lib/cretonne/src/timing.rs, lib/filetests/src/lib.rs, lib/filetests/src/test_dce.rs, lib/filetests/src/test_postopt.rs
This PR introduces new optimization passes to fold immediates into arithmetic instructions, convert compare and branch sequences to use flags values to avoid materializing boolean values in registers, and a DCE pass to clean up dead code. This reduces the number of instructions emitted in many common cases.
This fixes #269 for now. Instead of doing these optimizations in wasm folding, they are done in preopt and a new postopt pass. This means we generate more code before optimizing it away, which is unfortunate, but it keeps wasm decoding simpler for now, and it helps frontends not using the wasm decoder as well.
I don't want preopt and postopt to be passes that accumulate lots of hand-written pattern-matching code, but the code here covers a few specific common cases and is fairly …
=> Optimize immediates and compare and branch sequences

README.rst
This adds a brief blurb about Cretonne's current status, so that people looking at Cretonne have an idea of what to expect.
=> Add a status summary to the README.

filetests/isa/intel/prologue-epilogue.cton, lib/cretonne/src/isa/arm32/abi.rs, lib/cretonne/src/isa/arm32/mod.rs, lib/cretonne/src/isa/arm64/abi.rs, lib/cretonne/src/isa/arm64/mod.rs, lib/cretonne/src/isa/intel/abi.rs, lib/cretonne/src/isa/intel/mod.rs, lib/cretonne/src/isa/mod.rs, lib/cretonne/src/isa/riscv/abi.rs, lib/cretonne/src/isa/riscv/mod.rs, lib/cretonne/src/regalloc/allocatable_set.rs, lib/cretonne/src/regalloc/coloring.rs, lib/cretonne/src/regalloc/mod.rs, lib/cretonne/src/regalloc/pressure.rs, lib/cretonne/src/regalloc/register_set.rs, lib/cretonne/src/regalloc/solver.rs
Currently we save all callee-saved registers in the prologue of every function, and restore them in the epilogue. With this PR, we now only save and restore those that are actually used in the function.
I'm not particularly happy with the code in this one. I feel like I'm abusing AllocatableSet. But it appears to work and can be refactored.
Test fixes/changes forthcoming.
=> Only save callee-saved registers that are used

lib/codegen/src/binemit/memorysink.rs, lib/codegen/src/context.rs, lib/faerie/src/backend.rs, lib/simplejit/src/backend.rs, src/compile.rs
Some users have found `emit_to_memory` awkward when writing code into a `Vec<u8>`, and @eddyb pointed out that it should actually be an unsafe function, given what it does. The patch here makes `emit_to_memory` unsafe, and adds an `emit` function which provides a safe interface for the case of writing to a `Vec<u8>`.
=> Mark `emit_to_memory` as unsafe, and introduce a safe `emit`.

lib/faerie/Cargo.toml, lib/faerie/src/backend.rs, lib/faerie/src/lib.rs, lib/faerie/src/target.rs, lib/faerie/src/traps.rs, lib/module/Cargo.toml, lib/module/src/backend.rs, lib/module/src/data_context.rs, lib/module/src/lib.rs, lib/module/src/module.rs, lib/simplejit/src/backend.rs, test-no_std.sh
Defines an `enum ModuleError`, which derives `Fail`, to be used throughout `Module`. Implement `ModuleError` results at all the places that used to panic, or were otherwise unimplemented.
Exposes `Module::get_name(&self, &str) -> Option<FuncOrDataId>`, and the `FuncOrDataId` type. This is convenient for users so we don't have to do our own declaration bookkeeping.
This was spurred by a discussion about possibly adding string-name method variants (using declaration string names instead of FuncId or DataId). The `get_name` method allows the user to implement those themselves, if they are required.
=> Improvements to Modules API

lib/codegen/src/timing.rs
Fixed a minor typo in the `PassTime` struct's comments found while familiarizing myself with the codebase to work on a different issue.
=> Fix minor comment typo.

.travis.yml, lib/faerie/src/backend.rs
Exposes a new field `libcall_names: Vec<String>` in `FaerieBuilder`, and a new method `FaerieBuilder::default_libcall_names` to provide sensible default values for those libcalls.
The `FaerieTrapSink` looks up any libcall in the names provided, imports that function, and makes a link to it, instead of panicking on encountering a libcall.
=> cretonne-faerie: add a translation mechanism for LibCalls

.travis.yml, lib/codegen/meta/isa/arm32/__init__.py, lib/codegen/meta/isa/arm32/defs.py, lib/codegen/meta/isa/arm64/__init__.py, lib/codegen/meta/isa/arm64/defs.py, lib/codegen/meta/isa/riscv/__init__.py, lib/codegen/meta/isa/riscv/defs.py, lib/codegen/meta/isa/x86/__init__.py, lib/codegen/meta/isa/x86/defs.py, lib/codegen/meta/mypy.ini
The error message said `ISA` and pointed to the initialization of the `ISA` variable in __int__.py, but the trick was that the `ISA` variable in `defs.py` also needed an annotation.
This fixes #323.
=> Fixes for mypy 0.600

filetests/isa/x86/binary32-float.cton, filetests/isa/x86/binary32.cton, filetests/isa/x86/binary64-float.cton, filetests/isa/x86/binary64-pic.cton, filetests/isa/x86/binary64.cton, lib/codegen/meta/isa/x86/recipes.py
This is the analog of the HeapOutOfBounds traps emitted on other loads and stores.
I'm not 100% sure that I caught every possible case.
=> x86 recipes: emit StackOverflow trap for all sp-relative loads and stores

filetests/isa/x86/windows_fastcall_x64.cton, lib/codegen/meta/base/settings.py, lib/codegen/src/ir/extfunc.rs, lib/codegen/src/isa/x86/abi.rs, lib/native/src/lib.rs, lib/simplejit/Cargo.toml, lib/simplejit/src/backend.rs, lib/simplejit/src/lib.rs, lib/simplejit/src/memory.rs
This adds support for the windows x64 fastcall-based calling convention 
(default calling convention on Win64)
described at https://msdn.microsoft.com/en-us/library/ms235286.aspx
The state in this commit (plus minor patches for simplejit on its repository) are enough,
to run those basic examples on windows.
Tested with patched simplejit and ceilf call locally
to ensure prologue/epilogue is compatible not only in theory (very basic tests done)
- ~ensure argument registers, when required, are spilled into the "shadow store~
References #305.
=> windows fastcall (x64) call convention

docs/langref.rst, filetests/isa/x86/binary32-float.cton, filetests/isa/x86/binary32.cton, filetests/isa/x86/binary64-float.cton, filetests/isa/x86/binary64.cton, filetests/parser/tiny.cton, filetests/postopt/complex_memory_ops.cton, lib/codegen/meta/base/formats.py, lib/codegen/meta/base/instructions.py, lib/codegen/meta/base/predicates.py, lib/codegen/meta/cdsl/formats.py, lib/codegen/meta/cdsl/instructions.py, lib/codegen/meta/gen_binemit.py, lib/codegen/meta/gen_encoding.py, lib/codegen/meta/isa/x86/encodings.py, lib/codegen/meta/isa/x86/recipes.py, lib/codegen/src/isa/mod.rs, lib/codegen/src/isa/x86/binemit.rs, lib/codegen/src/isa/x86/mod.rs, lib/codegen/src/postopt.rs, lib/codegen/src/predicates.rs, lib/codegen/src/verifier/mod.rs, lib/codegen/src/write.rs, lib/reader/src/lexer.rs, lib/reader/src/parser.rs
This is a work-in-progress. I'm opening it now so I have something to refer to for feedback and help. :)
This PR is intended to address #285.
Things to do:
=> load_complex and store_complex instructions

lib/codegen/meta/constant_hash.py
Found this while I was reading through the `lib/codegen` code, figured I would open up a PR to fix it :)
=> Minor typo fix in `constant_hash` comment.

Cargo.toml, lib/codegen/src/partition_slice.rs
This function is called by `LiveValueTracker` which is used by many of the register allocation passes.
Result from compiling `tanks.wasm` show a 8% reduction in register allocation time, which translates to a 5% reduction in total compilation time.
Before:
```
$ perf stat target/release/cton-util wasm -T --set enable_verifier=0 --set is_64bit=1 --isa "x86 haswell" ../wasm-collection/misc-valid/tanks.wasm
======== ========  ==================================
Total     Self  Pass
-------- --------  ----------------------------------
1.476    0.047  Translate WASM module
1.429    1.429  Translate WASM function
7.500    0.237  Compilation passes
0.069    0.069  Control flow graph
0.101    0.101  Dominator tree
0.219    0.219  Post-legalization rewriting
0.056    0.056  Pre-legalization …
```
=> Optimize partition_slice

lib/codegen/src/fx.rs, lib/codegen/src/lib.rs, lib/codegen/src/licm.rs, lib/codegen/src/regalloc/coalescing.rs, lib/codegen/src/regalloc/live_value_tracker.rs, lib/codegen/src/scoped_hash_map.rs
This improves the performance of `VirtualCopies::filter` by using a `FxHashMap` instead of a binary search.
I also changed all the `HashMap` in the `codegen` crate to `FxHashMap` for consistency, but there is no noticeable performance improvement since 80% of the time is spent in the register allocator.
Result from compiling `sqlite.wasm` show a 16.7% reduction in coalescing time, which translates to a 9.6% reduction in total compilation time.
Before:
```
$ perf stat target/release/cton-util wasm -T --set enable_verifier=0 --set is_64bit=1 --isa x86 ../wasm-collection/misc-valid/sqlite.wasm
======== ========  ==================================
Total     Self  Pass
-------- --------  ----------------------------------
0.319    0.001  Translate WASM module
0.318    0.318  Translate WASM …
```
=> Improve coalescing performance by using a FxHashMap

lib/codegen/src/result.rs, lib/wasm/Cargo.toml, lib/wasm/src/code_translator.rs, lib/wasm/src/environ/dummy.rs, lib/wasm/src/environ/mod.rs, lib/wasm/src/environ/spec.rs, lib/wasm/src/func_translator.rs, lib/wasm/src/lib.rs, lib/wasm/src/module_translator.rs, lib/wasm/src/sections_translator.rs, src/wasm.rs
Define `WasmError` (and an accompanying `WasmResult`) to represent
errors translating WebAssembly functions. Make `translate_call` and
related functions return `WasmResult`s so that embedders have the
flexibility to reject features they don't support.
Move `InvalidInput` out of `CtonError` and into `WasmError`, where it's
now named `InvalidWebAssembly`, as it's a WebAssembly-specific error
condition. Also extend it to preserve the original error message and
bytecode offset.
@lachlansneff Does this look like it would work for your use case?
=> Allow wasm embedders to reject wasm modules with unsupported features.

lib/native/Cargo.toml
The raw-cpuid library links in a c-library to call the `cpuid` instruction unless the nightly feature is enabled. When the `core` feature is enabled, enable the "nightly" feature for `raw-cpuid` to avoid that.
=> Use "nightly" feature of raw-cpuid when possible.

filetests/isa/x86/stack-addr64.cton, filetests/isa/x86/stack-load-store64.cton, lib/codegen/meta/base/legalize.py, lib/codegen/meta/isa/x86/encodings.py, lib/codegen/meta/isa/x86/recipes.py, lib/codegen/src/legalizer/mod.rs
This provides basic implementations for the stack access instructions. More optimal sequences are possible but these should be enough to get things started.
Fixes #181. Fixes #368.
=> Implement stack_addr, stack_load, stack_store for x86-64.

filetests/isa/x86/binary32.cton, filetests/isa/x86/binary64-pic.cton, filetests/isa/x86/binary64.cton, lib/codegen/meta/isa/x86/recipes.py, lib/codegen/src/binemit/mod.rs, lib/faerie/src/backend.rs, lib/faerie/src/container.rs, lib/simplejit/src/backend.rs
This requires splitting X86PCRel4 into two separate relocations, to
distinguish the case where the instruction is a call, as Mach-O uses a
different relocation in that case.
This also makes it explicit that only x86-64 relocations are supported
currently.
=> Add support for macho relocations.

Cargo.toml, lib/codegen/src/print_errors.rs, lib/codegen/src/write.rs
example:
function %bad(i32) fast {
ebb0(v0: i32):
brnz.i32 v0, ebb1
return
^~~~~~
verifier inst1: Internal return not allowed with return_at_end=1
ebb1:
trapz.i32 v0, user6
return
}
Fixes #68
=> Adds decoration to the verifier errors.

filetests/isa/x86/binary32-float.cton, filetests/isa/x86/binary32.cton, filetests/isa/x86/binary64-float.cton, filetests/isa/x86/binary64.cton, lib/codegen/meta/isa/x86/recipes.py
In theory, pop and fill instructions should only be reading stack memory that has already been successfully written to, so they themselves should never be able to trigger `StackOverflow` traps. This reduces the amount of bookkeeping needed.
=> Pop and fill don't trigger StackOverflow.

lib/codegen/build.rs, lib/codegen/meta/check.sh, test-all.sh
Add support for finding an appropriate python command on systems which
don't have "python". Try "python3" and "python2.7".
Fixed #381.
=> Support systems which don't have a "python" command.

docs/heapex-dyn.cton, docs/heapex-sm32.cton, docs/heapex-sm64.cton, filetests/parser/memory.cton, filetests/verifier/undeclared_vmctx.cton, lib/codegen/src/verifier/mod.rs
Here's an example of what is returned by the compiler:
```cretonne
target x86_64
function %vmglobal(i64) -> i64 {
gv4 = vmctx+0
ebb0(v0: i64):
v1 = global_value.i64 gv4
return v1
}
```
Changing the parameter to `i64 vmctx` causes no reported error or panic.
=> Now diagnosing missing vmctx arguments (fixes #376)

Cargo.toml, lib/wasm/Cargo.toml
This fixes compilation on system with GCC 8.
See https://github.com/pepyakin/wabt-rs/issues/15
=> Update wabt to 0.4

src/wasm.rs
If you run the `wasm` command on a file, without a specific ISA defined, it will panic. This fixes it, and restructure the code (adds `\n`, inverts control flow to reduce indent, rename `data` into `module_binary`) in this file to make it easier to understand.
=> Reject with a plain text error when no ISA is defined with wasm

lib/codegen/meta/gen_instr.py, lib/codegen/src/simple_gvn.rs, lib/entity/src/list.rs
Currently, `EntityList` implements the `Eq` and `Hash` trait but simply panics in the implementation. The original purpose of this hack was to allow some instructions (the ones that don't use `ValueList`) to be stored in a hash table for GVN.
This PR removes the `Eq` and `Hash` implementations on `EntityList` and instead generates custom `eq` and `hash` functions for `InstructionData` which take a `ValueListPool` parameter. These functions are then used in the GVN pass when inserting the `InstructionData` into a `HashMap`.
Note: The use of a `RefCell` makes the code a bit ugly, but there is no other way to do this.
This solves the problem described in https://github.com/cretonne/cretonne/issues/366#issuecomment-398558755.
=> Make InstructionData comparable and hashable

lib/codegen/src/dominator_tree.rs, lib/codegen/src/preopt.rs, lib/wasm/src/module_translator.rs, lib/wasm/src/sections_translator.rs, src/wasm.rs
Sorry this is in a form of potpourri. These are small fixes to comments or small refactorings which make the code easier to understand, in my opinion:
- fixed typo in dominator_tree.
- simplify some control flow in preopt by playing with block expression to avoid mutable borrow of an immutably borrowed value (which justified the previous code).
- simplify to the module translator to avoid duplicate code for data sections.
- reuse and clear the Context in wasm.rs. After all, that's the first thing the comment of Context recommends to do :) And it improves the testing of the re-usability of Context.
=> Misc refactorings when looking at the wasm code

lib/codegen/src/flowgraph.rs, lib/codegen/src/ir/instructions.rs, lib/codegen/src/ir/valueloc.rs, lib/codegen/src/settings.rs
Th only one I couldn't figure out how to fix was `congruence_class`.
https://github.com/CraneStation/cranelift/blob/01de6842b1a3230db645a00f4ecf0176b5fdc65f/lib/codegen/src/regalloc/virtregs.rs#L100-L106
=> Fixed trivially_copy_pass_by_ref warnings

lib/codegen/src/print_errors.rs, lib/codegen/src/regalloc/virtregs.rs
This will fix all current clippy warnings except for the ones fixed in #408.
=> Fixed remaining clippy warnings

docs/langref.rst, filetests/parser/memory.clif, lib/codegen/src/ir/heap.rs, lib/codegen/src/ir/mod.rs, lib/codegen/src/legalizer/heap.rs, lib/reader/src/parser.rs, lib/wasm/src/environ/dummy.rs
This wasn't implemented, and if we need it in the future, it seems like
it would be better to extend the concept of global values to cover this.
This is also related to #346, adding a table concept, as it would be
extra complexity to support reserved-reg for tables as well.
=> Remove reserved_reg functionality.

filetests/verifier/type_check.clif, lib/codegen/src/print_errors.rs, lib/codegen/src/verifier/mod.rs, lib/filetests/src/runone.rs
- if the error location isn't an instruction, the error wasn't printed *and* the instructions were not printed either.
- added hints in the mismatched argument count error reporting by showing which instruction is involved.
- random fixing of new line displaying to have consistent indent when a function is printed by the verifier pretty printer.
=> Enhance Verifier error reporting

filetests/wasm/conversions.clif, lib/codegen/meta-python/base/instructions.py, lib/codegen/meta-python/isa/x86/legalize.py, lib/codegen/src/isa/x86/enc_tables.rs, lib/wasm/src/code_translator.rs
I initially thought I could factor the code more, since the behavior doesn't seem to change much with respect to the non-saturating ops. In fact, this is different enough that a different function is justified for the signed comparison; for the unsigned one, we could maybe use a boolean toggle to decide if we want a saturating operation or not. Will investigate more.
Still a work in progress; I need to test it against Baldrdash to make sure it is correct.
=> Implement wasm saturating conversions

README.md
Trying to build the documentation and needed to install python 3 so I updated it and the old https link was not working because Sphinx's settings were not correct so the link had to be changed to http.
=> Updating Sphinx link and install

lib/frontend/src/frontend.rs, lib/frontend/src/lib.rs, lib/wasm/src/code_translator.rs, lib/wasm/src/func_translator.rs
Following some reports of confusion over how to translate SSA or non-SSA "variables", improved the doc so explain better how the builder API handles them.
=> FunctionBuilder no longer Variable-parametric (and updated doc)

lib/codegen/src/print_errors.rs, lib/codegen/src/verifier/mod.rs, src/clif-util.rs
When I implemented the new verifier result, I accidentally switched two conditions in `pretty_verifier_error`, which caused errors to be incorrectly reported at the start of the body. Furthermore, valid instructions weren't printed. This fixes those issues.
PS: Also realized that disabling the "wasm" feature led to an error in "clif-util.rs", so I fixed it as well.
**Update**: I also made multiple checks non-fatal in the verifier, which means that now multiple instructions can have errors at the same time! Unless we make some strong assertions between `verify` functions, this shouldn't cause any issue in the future.
=> Improvements to error reporting

lib/codegen/src/print_errors.rs, lib/codegen/src/write.rs
Here's an example output:
```
function %vmglobal_err(i64, i64) -> i64 fast {
gv0 = globalsym %
gv1 = vmctx
^~~~ verifier gv1: undeclared vmctx reference gv1
gv2 = vmctx
^~~~ verifier gv2: undeclared vmctx reference gv2
ebb0(v0: i64, v1: i64):
v2 = global_value.i64 gv1
v3 = global_value.i64 gv2
return v1
}
```
with file
```
test compile
target x86_64
function %vmglobal_err(i64, i64) -> i64 {
gv1 = vmctx+0
gv2 = vmctx+0
ebb0(v0: i64, v1: i64):
v2 = global_value.i64 gv1
v3 = global_value.i64 gv2
return v1
}
```
=> Pretty printing preamble errors.

filetests/isa/riscv/verify-encoding.clif, filetests/verifier/type_check.clif, lib/codegen/src/verifier/mod.rs, lib/filetests/src/test_verifier.rs, src/clif-util.rs
In filetests, if multiple errors were reported in a function but only one of them was expected, no fail was reported. This fixes it.
Additionally, now that errors are correctly checked, some tests had to be fixed because more than one error were reported.
=> Fix error not reported if at least one other error expected.

filetests/isa/x86/legalize-heaps.clif, filetests/isa/x86/legalize-memory.clif, filetests/parser/memory.clif, filetests/verifier/globals.clif, filetests/verifier/heap.clif, filetests/verifier/memory.clif, lib/codegen/src/ir/globalvalue.rs, lib/codegen/src/ir/heap.rs, lib/codegen/src/legalizer/globalvalue.rs, lib/codegen/src/legalizer/heap.rs, lib/codegen/src/verifier/mod.rs, lib/reader/src/parser.rs, lib/wasm/src/environ/dummy.rs
This makes several changes:
- It adds an index_type to heap declarations, allowing heaps to specify the
type for indexing. This also anticipates 64-bit heap support.
- It adds a memory_type to deref global values, allowing deref globals to
have types other than pointers. This is used to allow the bound variable
in dynamic heaps to have type i32, to match the index type in heaps
with i32 index type.
- And, it fixes heap legalization to do the bounds check in the heap's
index type.
This is a minor yak-shave prompted in part by https://github.com/CraneStation/cranelift/issues/451, and will prepare the path for `table_addr` to take i32 indices instead of just pointer-sized indices.
=> Fix legalization of heap_addrs with 32-bit indices.

lib/faerie/src/backend.rs, lib/module/src/backend.rs, lib/module/src/module.rs, lib/simplejit/src/backend.rs
Add `publish()` function to cranelift-module's `Backend` trait, which
allows `finalize_all()` to defer making memory executable until it
has finished all of the patching it needs to do.
Fixes #468.
=> [SimpleJIT] When finalizing multiple functions, make them all executable at the end.

lib/codegen/src/ir/dfg.rs, lib/codegen/src/print_errors.rs, lib/codegen/src/write.rs, lib/reader/src/parser.rs
This is a WIP implementation for #488--AFAIK it works, but all tests pass with alias printing deleted entirely so I need to add some tests that cover this behavior.
=> Print value aliases at referrent definition

lib/filetests/src/concurrent.rs, lib/filetests/src/lib.rs, lib/filetests/src/runner.rs, lib/filetests/src/runone.rs, lib/reader/src/parser.rs, lib/reader/src/sourcemap.rs, src/clif-util.rs, src/compile.rs
Can now specify passes to be run on files from the command line.
This pass command tosses tests and targets specified at the top of the file.
=> Adds pass command to clif-util.

lib/filetests/src/lib.rs, src/clif-util.rs, src/utils.rs, src/wasm.rs
Not sure how to write a test for this, or if that is necessary, but these commands work now, when they did not before:
```
$ cargo run --bin clif-util -- compile --target x86_64-unknown-linux-gnu < filetests/wasm/control.clif
$ cargo run --bin clif-util -- wasm --target x86_64-unknown-linux-gnu < ~/path/to/test.wasm 
```
=> Some little clif-util things

src/clif-util.rs
Because of the way that the `pass` subcommand orders its arguments, the positional "single-file" input cannot be optional with a default value, because it is followed by required positional arguments. If it were optional, that would result in argument ambiguity where `clap` cannot tell if the optional positional argument is supplied, or if the given argument is the next required positional argument.
Before this commit:
```
$ cargo run --bin clif-util -- pass ./filetests/dce/basic.clif dce
Compiling cranelift-tools v0.21.0 (file:///Users/fitzgen/src/cranelift)
Finished dev [unoptimized + debuginfo] target(s) in 4.38s
Running `target/debug/clif-util pass ./filetests/dce/basic.clif dce`
thread 'main' panicked at 'Found positional argument which is not required with a lower index than a …
```
=> clif-util: fix `clif-util pass` subcommand arguments

filetests/regalloc/reload.clif, lib/codegen/src/regalloc/reload.rs
=> Update the reload pass to replace copies with fill/spill instructions

lib/entity/README.md
Summarize what cranelift-entity provides, and how it differs from
similar systems such as slotmap, which was recently highlighted in the
RustConf 2018 Closing Keynote.
=> Add more content to cranelift-entity's README.md.

lib/module/src/module.rs, lib/simplejit/examples/simplejit-minimal.rs, lib/simplejit/tests/basic.rs
Remove the ability to finalize individiual functions and data objects,
and instead just provide a way to finalize everything that's been
defined but not yet finalized. This allows SimpleJIT to share an
allocation between multiple functions without having to worry about
individual functions being finalized and needing to be published
without the other functions in the same allocation.
Users of the return values of `Module`'s `finalize_function` and
`finalize_data` should now use `get_finalized_function` and
`get_finalized_data` to obtain these values.
Fixes #468.
=> Remove `Module`'s `finalize_function` and `finalize_data`.

.rustfmt.toml, CONTRIBUTING.md, README.md
This adds a few more miscellaneous changes.
I recently learned about \<details\>, which seems like a nice way to keep the main README.md landing page a little tidier while still making additional information available.
And, I took the liberty of reorganzing the issue labels again. Unfortunately the issue labels themselves can't be changed via PR. But the basic idea is to follow the Rust repo's issue scheme, with `E-easy` etc indicating experience levels needed, and so on. I'm open to suggestions here!
=> More introductory documentation

lib/codegen/src/ir/libcall.rs
Replacing use of the `NAME` with just calling the Debug implementation makes it less prone to accidentally printing the wrong thing or panicking in case a the enum does not match up to the array.
=> Replaced LibCall's fmt::Display implementation

Cargo.toml, lib/wasm/Cargo.toml
After upgrading, errors with outdated `cmake` should gone.
=> Bump wabt version to 0.6.

filetests/isa/x86/ireduce-i16-to-i8.clif, filetests/isa/x86/isub_imm-i8.clif, filetests/isa/x86/legalize-clz-ctz-i8.clif, filetests/isa/x86/legalize-popcnt-i8.clif, filetests/isa/x86/uextend-i8-to-i16.clif, lib/codegen/meta-python/base/legalize.py, lib/codegen/meta-python/isa/x86/encodings.py, lib/frontend/src/frontend.rs
Also adds legalization for srem, irsub_imm, {u,s}extend.i16.i8
Fixes #477 cc #466
=> Add encodings for i8 and i16 copy, spill, fill, ireduce.i8.i16

docs/ir.rst, filetests/isa/x86/binary64.clif, filetests/isa/x86/legalize-br-table.clif, filetests/parser/branch.clif, filetests/verifier/type_check.clif, filetests/wasm/control.clif, lib/codegen/src/binemit/mod.rs, lib/codegen/src/dominator_tree.rs, lib/codegen/src/flowgraph.rs, lib/codegen/src/ir/function.rs, lib/codegen/src/ir/jumptable.rs, lib/codegen/src/legalizer/mod.rs, lib/codegen/src/regalloc/coloring.rs, lib/codegen/src/verifier/flags.rs, lib/codegen/src/verifier/locations.rs, lib/codegen/src/verifier/mod.rs, lib/filetests/src/test_binemit.rs, lib/frontend/src/frontend.rs, lib/frontend/src/ssa.rs, lib/frontend/src/switch.rs, lib/reader/src/parser.rs, lib/reader/src/sourcemap.rs
WebAssembly doesn't have non-dense jump tables, and higher-level users
are better served by the facilities in lib/frontend/src/switch.rs for
working with non-dense switches.
This eliminates the concept of "absent" jump table entries, which
were represented as "0" in the text format.
Also, jump table contents are now enclosed in `[` and `]`, so that
we can unambiguously display empty jump tables. Previously, empty jump
tables were displayed as if they had a single absent entry.
=> Remove the concept of non-dense jump tables.

lib/codegen/Cargo.toml, lib/codegen/src/isa/arm32/mod.rs, lib/codegen/src/isa/arm64/mod.rs, lib/codegen/src/isa/mod.rs, lib/codegen/src/isa/riscv/mod.rs, lib/codegen/src/isa/x86/mod.rs, lib/filetests/Cargo.toml
In practice, TargetIsa's emit_inst pulls in its own instantiation
of the target-specific `emit_inst` functions, which can be quite
large, and LTO doesn't eliminate them because they're held live
by TargetIsa's vtable.
Fortunately, this function is only used by tests, so we can put
it behind a feature flag.
Fixes #530.
=> Put TargetIsa's emit_inst under a "testing_hooks" feature.

lib/wasm/src/code_translator.rs, lib/wasm/src/environ/dummy.rs, lib/wasm/src/sections_translator.rs, lib/wasm/src/state.rs, lib/wasm/src/translation_utils.rs
=> Use types to represent wasm global/table/memory/signature indices

filetests/postopt/fold_offset_into_address.clif, lib/codegen/src/ir/immediates.rs, lib/codegen/src/postopt.rs
Fold the immediate into the load/store offset when possible.
I'm hoping to avoid doing too many special-case pattern matches like this, as I'm looking forward to developing a more comprehensive pattern-matching system, but it does make sense to do a few simple and common ones for now.
=> Optimize load/store with an iadd_imm operand.

lib/wasm/src/environ/spec.rs
`NormalReturns` is what we expect most users will normally want.
=> Make `FuncEnvironment::return_mode()` default to `NormalReturns`.

lib/codegen/meta/src/cdsl/types.rs, lib/codegen/meta/src/gen_types.rs
=> Use `Display` rather than having an explicit `name()` function for types.

.travis.yml, CONTRIBUTING.md, README.md, lib/bforest/src/node.rs, lib/codegen/src/context.rs, lib/codegen/src/ir/dfg.rs, lib/codegen/src/lib.rs, lib/codegen/src/timing.rs, lib/entity/src/list.rs, lib/faerie/Cargo.toml, lib/filetests/src/lib.rs, lib/filetests/src/runner.rs, lib/simplejit/Cargo.toml, lib/simplejit/src/memory.rs
We no longer need the Ubuntu LTS restriction, so now the only only
constraint I'm aware of is Firefox's policy. Fortunately, that tracks
the latest stable delayed by only two weeks. So this puts is at
Rust 1.29 now.
If anyone is aware of other important constraints that we should follow,
please bring them up!
=> Update the minimum supported Rust version to 1.29.

lib/simplejit/src/backend.rs
Not yet tested
https://lkml.org/lkml/2009/6/8/499
=> SimpleJit perf map

lib/codegen/src/print_errors.rs
extract arrow drawing code into helper
print ; at beginning of line followed by arrow and error body
=> Prefix verifier errors with ;

filetests/isa/x86/legalize-libcall.clif, fuzz/Cargo.toml, fuzz/fuzz_translate_module.rs, lib/codegen/meta-python/base/settings.py, lib/codegen/src/ir/extfunc.rs, lib/codegen/src/ir/function.rs, lib/codegen/src/ir/libcall.rs, lib/codegen/src/isa/call_conv.rs, lib/codegen/src/isa/mod.rs, lib/codegen/src/isa/x86/abi.rs, lib/codegen/src/settings.rs, lib/frontend/src/frontend.rs, lib/frontend/src/lib.rs, lib/module/src/module.rs, lib/native/src/lib.rs, lib/reader/src/parser.rs, lib/simplejit/src/backend.rs, lib/simplejit/tests/basic.rs, lib/umbrella/src/lib.rs, lib/wasm/Cargo.toml, lib/wasm/src/environ/dummy.rs, lib/wasm/src/environ/spec.rs, lib/wasm/src/func_translator.rs, lib/wasm/src/lib.rs, lib/wasm/src/sections_translator.rs, lib/wasm/tests/wasm_testsuite.rs, src/wasm.rs
`TargetFrontendConfig` is information specific to the target which is
provided to frontends to allow them to produce Cranelift IR for the
target. Currently this includes the pointer size and the default calling
convention.
The default calling convention is now inferred from the target, rather
than being a setting. cranelift-native is now just a provider of target
information, rather than also being a provider of settings, which gives
it a clearer role.
And instead of having cranelift-frontend routines require the whole
`TargetIsa`, just require the `TargetFrontendConfig`, and add a way to
get the `TargetFrontendConfig` from a `Module`.
Fixes #529.
Fixes #555.
=> Introduce a `TargetFrontendConfig` type.

lib/frontend/src/frontend.rs
Passing it by reference was an artifact of an earlier version of the
TargetFrontendConfig code, but it's no longer needed, as
TargetFrontendConfig is now a Copy type.
@bjorn3
=> Pass TargetFrontendConfig by value rather than by reference.

lib/wasm/Cargo.toml, lib/wasm/src/environ/spec.rs, lib/wasm/src/func_translator.rs, lib/wasm/src/lib.rs, lib/wasm/src/module_translator.rs, lib/wasm/src/sections_translator.rs
The new wasmparser API provides dedicated reader types for each section
type, which significantly simplifies the code.
This also changes WasmError::from_binary_reader_error into a From
trait so that we don't have to do .map_err(from_binary_reader_error)
throughout the code.
=> Update to the new wasmparser and port to the new readers API.

filetests/regalloc/multiple-returns.clif, lib/codegen/src/regalloc/spilling.rs
When one value is used multiple times for separate return values, we
need to copy it to produce a new value, so that each value can be
allocated a different register.
=> Insert copies to support a value being used as multiple return values.

filetests/regalloc/fallthrough-return.clif, lib/codegen/meta-python/base/instructions.py, lib/codegen/meta-python/cdsl/instructions.py, lib/codegen/src/regalloc/coloring.rs, lib/codegen/src/regalloc/reload.rs, lib/codegen/src/verifier/mod.rs
Add an explicit "is_ghost" property to selected instructions, and use
that to determine whether reload and coloring should visit instructions.
This allows them to visit fallthrough_return instructions and insert
fills and register moves as needed.
=> Make regalloc visit fallthrough_return instructions.

filetests/regalloc/multiple-returns.clif, lib/codegen/src/regalloc/spilling.rs
This is a followup to af2a952aabd82cf401cc664d0262b139ff92d86b. It
teaches the spilling pass to use the is_ghost() property to test whether
to visit instructions. This fixes a bug handling multiple return values
with fallthrough_return.
=> Make spilling visit fallthrough_return instructions too.

lib/module/src/module.rs
When the signature is not compatible, the previous and current signatures are now included. This is very useful when debugging this kind of error.
=> Better incompatible declaration error

lib/codegen/build.rs
This makes its output non-deterministic, making it friendlier for compilation caching tools such as [sccache](https://github.com/mozilla/sccache).
Printing out the build directory is nice to do, as Cargo tends to keep a few versions around under the target directory and it's useful to know which one is for the current build, but I wasn't able to find a better way to do that.
This is my current theory as to what's causing the significant build time regressions in mozilla-central reported here: https://bugzilla.mozilla.org/show_bug.cgi?id=1506511
=> Remove the build time and directory from cranelift-codegen-meta's output

filetests/isa/x86/binary64.clif, lib/codegen/meta-python/isa/x86/recipes.py, lib/codegen/src/isa/x86/enc_tables.rs, lib/codegen/src/print_errors.rs, lib/codegen/src/write.rs
Memory access instructions which took the GPR_ZERO_DEREF_SAFE register
class (that was removed in #552 ) should check for the need of either an
offset (r13/rbp) or the SIB byte (r12/rsp). Some load/store instructions
would already take an index, thus already contain the SIB byte in this
case (see instructions which have a comment telling that the else branch
already contains an SIB byte). Non-indexed memory accesses lacked the
SIB byte check, which this patch adds.
=> Fixes #600: Add a SIB byte when encoding a non-indexed load/store

lib/codegen/src/isa/mod.rs
In order to parallelize function compilation (`compile_and_emit` from `Context`), the trait `TargetIsa` needs to be `Sync`.
=> Make TargetIsa thread-safe

lib/wasm/src/environ/dummy.rs, lib/wasm/src/environ/spec.rs, lib/wasm/src/lib.rs, lib/wasm/src/sections_translator.rs, lib/wasm/src/translation_utils.rs
In order to support elem imported globals  in [wasmer](https://github.com/wafoundation/wasmer), we need to know where the global is being stored in the import object (that means, knowing it's `module` and `field`).
Example taken from [wasm spectests](https://github.com/WebAssembly/spec/blob/5aaea96eceb1e1a3956d7cbb499920e5b8c1109f/test/core/elem.wast#L60-L65):
```wasm
(module
(global $g (import "spectest" "global_i32") i32)
(table 1000 anyfunc)
(func $f)
(elem (get_global $g) $f)
)
```
For that to happen, `ModuleEnvironment` needs to know if a provided global is actually an import, so we are able to reference it properly when instantiating the module.
Currently, of all the WebAssembly imports (`func`, `memory`, `table`, `global`) only func is actually using the `module` and `field` …
=> Improved imports

filetests/verifier/defs_dominates_uses.clif, lib/codegen/src/print_errors.rs, lib/codegen/src/verifier/mod.rs, lib/filetests/src/test_verifier.rs
This tidies up several aspects of the verifier output. It fixes the length of the arrow to match the length of the subject, for example where it previously printed:
```
gv2 = load.i32 notrap aligned gv1
;   ^~~~ verifier gv2: base gv1 has type i32, which is not the pointer type i64
```
it now prints:
```
gv2 = load.i32 notrap aligned gv1
;   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
; error: gv2: base gv1 has type i32, which is not the pointer type i64
```
And, it tacks on a
```
; 1 verifier error detected (see above). Compilation aborted.
```
at the end, which is helpful because sometimes one gets a big IR dump and it's not immediately obvious why.
=> Make the verifier output even prettier

docs/ir.rst
This reorganizes some things in ir.rst to put all instructions not meant
for frontends to worry about in a dedicated section.
Fixes #282.
=> Document which instructions are meant for producers to use.

lib/wasm/src/sections_translator.rs, lib/wasm/src/translation_utils.rs
The spec has switched to calling the "initial" field the "minimum" field
because when linear memory is imported, it may initially be greater than
the "initial" value.
Making it u32 instead of usize will help avoid accidental host-specific
behavior.
=> Name Table and Memory's initial field `minimum` and make it u32.

lib/codegen/build.rs, lib/codegen/meta-python/cdsl/settings.py, lib/codegen/meta-python/gen_settings.py, lib/codegen/meta/src/base/mod.rs, lib/codegen/meta/src/base/settings.rs, lib/codegen/meta/src/cdsl/isa.rs, lib/codegen/meta/src/cdsl/mod.rs, lib/codegen/meta/src/cdsl/settings.rs, lib/codegen/meta/src/constant_hash.rs, lib/codegen/meta/src/gen_registers.rs, lib/codegen/meta/src/gen_settings.rs, lib/codegen/meta/src/isa/arm32/mod.rs, lib/codegen/meta/src/isa/arm64/mod.rs, lib/codegen/meta/src/isa/mod.rs, lib/codegen/meta/src/isa/riscv/mod.rs, lib/codegen/meta/src/isa/x86/mod.rs, lib/codegen/meta/src/lib.rs, lib/codegen/meta/src/srcgen.rs, lib/codegen/meta/src/unique_table.rs, lib/codegen/src/constant_hash.rs
This is almost done; it took me slightly more time than I expected because I wanted to have a nice interface for predicates and presets.
Unfortunately, because of anonymous predicates used in x86 encodings or legalization (can't remember), we can't just use this yet, because we need to migrate other build steps before we can. Maybe we could just change the code there to use named predicates instead...
=> Move settings generation from Python to Rust

filetests/isa/x86/binary64.clif, lib/codegen/meta-python/base/instructions.py, lib/codegen/meta-python/isa/x86/encodings.py, lib/codegen/meta-python/isa/x86/recipes.py
It's quite simple, and I've checked that it works in Spidermonkey (which had me add the `other_side_effects` flag so it wouldn't get removed by DCE). There weren't any other nullary recipe I could use for this, so I implemented it the simplest way; if we want more nullary instructions in the future, we can probably factor the recipe better.
=> Fixes #614: Implement a debug trap

lib/codegen/src/regalloc/coloring.rs, lib/codegen/src/regalloc/diversion.rs, lib/codegen/src/verifier/locations.rs, lib/entity/src/map.rs
Because it's hot and the number of entries can reach the 1000s, so
linear insertion and search is bad.
This reduces runtime for `sqlite` and `UE4Game-HTML5-Shipping` by 3-4%,
and a couple of other benchmarks (`sqlite`, `godot`, `clang`) by smaller
amounts.
It also increases runtime for `mono` and `tanks` by about 1%; this seems
to be due to incidental changes in which functions are inlined more than
algorithmic changes.
=> Use an `FxHashMap` in `RegDiversions`.

lib/codegen/src/write.rs
This is useful when you want to write extra information
=> Put default implementations of FuncWriter methods in a seperate method

lib/wasm/src/environ/dummy.rs, lib/wasm/src/environ/spec.rs, lib/wasm/src/sections_translator.rs, src/wasm.rs
This series of patches removes some unneeded functions from cranelift-wasm's `ModuleEnvironment`, reorders it to more closely reflect the sequence of calls that cranelift-wasm makes, and adds functions to allow implementations to use memory more efficiently.
This is an API change, requiring changes to cranelift-wasm users using `ModuleEnvironment`.
=> Simplify, reorganize, and optimize `ModuleEnvironment`

lib/faerie/src/backend.rs
cranelift-frontend now inserts libcalls for mem{cpy,set,move}
=> Remove outdated comment

lib/codegen/src/ir/trapcode.rs, lib/wasm/src/code_translator.rs
This eliminates the need for the last instance of `TrapCode::User` in cranelift-wasm, so all wasm traps have a clearly described cause.
=> Add an explicit trap code for wasm `unreachable`.

lib/module/src/module.rs
This is the least intrusive way I could find to get the necessary things for bjorn3/rustc_codegen_cranelift#166.
=> Peekable define function

lib/codegen/meta-python/gen_build_deps.py
We are facing peculiar Windows-only regressions in build times in
https://bugzilla.mozilla.org/show_bug.cgi?id=1506511 and while the build
times might just be Windows being slow, putting directories in
`rerun-if-changed` might also be causing problems.  The build only
depends on the files, anyway, so let's just say that.
=> avoid directories for cargo build dependencies

README.md
Small thing I came across while reading the README. Old link leads to `The second edition of the book is no longer distributed with Rust's documentation.`.
=> Fix link to cargo workspace documentation

cranelift-codegen/src/binemit/relaxation.rs, filetests/isa/x86/relax_branch.clif
This was previously using the following condition to decide that a block
hadn't been visited yet: either dest_offset is non-0 or the block isn't
the entry block.  Unfortunately, this didn't work when the first block
would be non-empty but wouldn't generate code at all. This uses
immutable indexing with an Option<> to check if the block's offset is
defined, instead.
=> Fix #666: Change the way we consider a block has been visited in relaxation

cranelift-codegen/src/ir/immediates.rs
fix error of `function_builder.ins().f64const(32f64)`
#677
=> add `Into` implementations for `Ieee64` and `Ieee32`, from f64 and f32

cranelift-codegen/meta/src/gen_registers.rs, cranelift-codegen/meta/src/gen_settings.rs, cranelift-codegen/meta/src/gen_types.rs, cranelift-codegen/meta/src/lib.rs, cranelift-codegen/meta/src/srcgen.rs
This does the following:
- accept both `&str` and `String` as arguments of the `Formatter::line` function, so one doesn't need to add a reference for String arguments.
- introduce the `fmtln!` macro to pass formatted strings to `Formatter::line` in an easier way. It was discussed on IRC to reuse the `writeln!` macro, but unfortunately the latter is fallible while the former isn't, so it would pollute the code by adding a lot of `?` or `unwrap/expect` which don't bring additional value (since our `Write` impl for the Formatter would always return `Ok(())`).
- the last commit I'm less sure of: I wondered if adding a `Formatter::block(text_before, |fmt| {})` function would make it easier to use the formatter (and not have to worry about block scoping). Unfortunately, in many cases we don't …
=> Meta: make the Formatter more pleasant to use

cranelift-codegen/src/ir/globalvalue.rs
It used to print `gv0 = colocated symbol u1:1` while cranelift-reader expects `gv0 = symbol colocated u1:1`.
Fixes #640
=> Fix global value colocated printing

cranelift-faerie/Cargo.toml, cranelift-faerie/src/backend.rs
Bump faerie to 0.8.0 and goblin to 0.0.21.
* Preemptible linkages are now weak symbols
* Faerie will put read-only data in .rodata for elf
=> cranelift-faerie: convert to use new extensible decl format

cranelift-wasm/src/environ/dummy.rs, cranelift-wasm/src/environ/spec.rs, cranelift-wasm/src/func_translator.rs, cranelift-wasm/src/sections_translator.rs
Making SourceLoc(u32) unique across the module.
=> Preserve global wasm module offset in SourceLoc.

publish-all.sh
The tag is named `v$version` and will thus appear in the tags/releases tabs of the repository, where we can add text explaining new features, API changes, etc.
=> Add a command to push a tag to the repository

cranelift-frontend/src/frontend.rs
It used to try to extend an `i32` to `i32`.
=> Fix emit_small_memset

cranelift-codegen/src/isa/x86/abi.rs, filetests/isa/x86/windows_fastcall_x64.clif
Previously we triggered the debug_assert for functions  returning floats.
This adds a testcase and fixes the behavior.
#691
=> windows/x64 call convention: only use XMM0 for float return values

cranelift-codegen/src/divconst_magic_numbers.rs
This gets rid of the build warnings when compiling the cranelift-codegen tests:
```
warning: function `test_magicU32` should have a snake case name
--> cranelift-codegen/src/divconst_magic_numbers.rs:249:8
|
249 |     fn test_magicU32() {
|        ^^^^^^^^^^^^^ help: convert the identifier to snake case: `test_magic_u32`
|
= note: #[warn(non_snake_case)] on by default
warning: function `test_magicU64` should have a snake case name
--> cranelift-codegen/src/divconst_magic_numbers.rs:283:8
|
283 |     fn test_magicU64() {
|        ^^^^^^^^^^^^^ help: convert the identifier to snake case: `test_magic_u64`
warning: function `test_magicS32` should have a snake case name
--> cranelift-codegen/src/divconst_magic_numbers.rs:350:8
|
350 |     fn test_magicS32() {
|        ^^^^^^^^^^^^^ help: …
```
=> Fix build warnings for cranelift-codegen tests

cranelift-codegen/src/postopt.rs, cranelift-codegen/src/regalloc/coalescing.rs, cranelift-codegen/src/regalloc/spilling.rs
Trying to fill the gaps into `SourceLoc` information (after some cranelift passes). Currently I just used [fib2_o2.wasm](https://github.com/yurydelendik/old-man-sandbox/blob/master/fibdbg/fib2_o2.wasm) to find such spots.
=> Add missing use_srcloc in postopt and regalloc passes

cranelift-codegen/src/context.rs, src/clif-util.rs, src/compile.rs, src/disasm.rs, src/wasm.rs
Both the `wasm` and `compile` commands get this new subcommand, and it defaults to false.  This means that test runs with `wasm` can request disassembly (the main reason I am doing this) while test runs with `compile` now must request it, this changes current behavior.  Discuss.
=> Add a --disasm option to clif-util `wasm` and `compile`

src/disasm.rs
When I factored the disassembler I tried to be smart about how it prints spaces, in order to avoid a formatting error in an edge condition.  But I wasn't smart enough: the space should be printed conditionally before the byte value, not after.  This fixes that.
=> Fix a disasm formatting error

cranelift-native/src/lib.rs
See #716 for discussion; an alternative solution is to add the dependency `cfg-if` and use `cfg_if!` here.
=> Fixes #716: Stub out parse_x86_cpuid in the non-x86 case

cranelift-codegen/meta/src/cdsl/types.rs, cranelift-codegen/meta/src/cdsl/typevar.rs, cranelift-codegen/meta/src/isa/x86/instructions.rs, cranelift-codegen/meta/src/shared/instructions.rs
This does a few things:
- add a `num_set!` macro to avoid repeating `NumSet::from_iter(vec![...])`.
- Move the TypeSet building code from the TypeVarBuilder into its own TypeSetBuilder structure. This doesn't change the all behavior, while it moves some code around.
- next commits add more tests, some of them were passing, but one of them helped identify two issues (that I saw when porting the legalization actions!):
- the name of derived type variables wasn't computed correctly
- nor was the type set, resulting in weird assertions triggering (e.g. when doing `TypeSet(ints=32..64).half_width().double_width()`)
I'm also pretty sure I found a bug in `gen_instr.py` which directly reads `type_set` from some typevars (it might need to use `get_typeset()` instead; this doesn't change behavior …
=> [meta] TypeVar/TypeSet tests

cranelift-codegen/src/binemit/relaxation.rs, filetests/regress/allow-relaxation-shrink.clif
Also:
- make sure to apply diversions when determining offsets for code
relaxation.
- select the smallest encoding when selecting a relaxed branch
instruction.
I didn't know where to put the test case, so I added a "regress" directory for regression tests (found by fuzzers), but I could move it to another directory. (`isa/` didn't seem quite appropriate, but other relaxation tests are there, so maybe it is)
@sunfishcode Can you have a look, please? Thanks!
=> Fix #686: Allow code shrink in relaxation if the shrinking pass hasn't run

Cargo.toml, cranelift-codegen/Cargo.toml, cranelift-faerie/Cargo.toml, cranelift-frontend/Cargo.toml, cranelift-native/Cargo.toml, cranelift-reader/Cargo.toml, cranelift-simplejit/Cargo.toml, cranelift-wasm/Cargo.toml, fuzz/Cargo.toml
This depends on https://github.com/m4b/faerie/pull/73 and will require a version bump there.
Having this would be nice for Spidermonkey/Gecko, which currently uses @glandium's clone of `target-lexicon` as the Gecko dependency (so as to have support for some ARM devices I guess).
(Build will be broken until faerie is updated)
=> Update target-lexicon to 0.4.0

cranelift-codegen/meta/src/unique_table.rs
This allows the unique sequence table to reuse the last elements of the whole table as a prefix when possible, that is:
- if we have `[A, B, C, D]` in the whole table
- and we want to insert `[C, D, E, F]` as a new sequence,
Then the `add()` function will just insert `[E, F]` and point to C's offset.
=> [meta] Optimize seq table

cranelift-codegen/meta-python/isa/x86/encodings.py, filetests/isa/x86/shrink.clif
The non-REX encoding of movzbl requires one of the ABCD registers as input.
Fixes #664 (cc @bjorn3)
I included `sextend.i32` and `uextend.i32` in the test as well, but they were already okay. I had a bit of a look at other instructions that used i8, and they all looked okay too.
=> Fix x86-64 encoding of uextend.i64.i8

cranelift-codegen/src/licm.rs, filetests/licm/load_readonly_notrap.clif, filetests/licm/reject_load_notrap.clif, filetests/licm/reject_load_readonly.clif
=> Allow readonly nontrapping loads to be hoisted by licm

cranelift-codegen/src/context.rs, cranelift-codegen/src/simple_preopt.rs, cranelift-filetests/src/test_simple_preopt.rs, filetests/simple_preopt/branch.clif, filetests/simple_preopt/simplify.clif
Fixes #606.
This PR add two optimizations to `simple_preopt.rs`. The first is to fold code where we compare against zero, then use an explicit conditional branch. For instance:
```
v1 = icmp_imm v0, 0
brz v1, ebb1
```
becomes
```
brnz v0, ebb1
```
For x86-64 this doesn't actually make much difference, as it compiles to a `test` rather than a `cmp`, which should be very near equivalent. But it does save a byte on a very common operation, so hey.
The second is reordering branches at the end of ebbs to encourage fallthroughs. As pointed out in #606, it's common for wasm code to be compiled like this:
```
brz v0, ebb1
jump ebb2
ebb1:
...
ebb2:
...
```
Which ends up being compiled as a conditional jump followed by a jump. However, we can switch those instructions by flipping the destinations …
=> Branch comparison folding and order optimizations

cranelift-codegen/src/verifier/mod.rs, filetests/verifier/jump_table.clif
edit: I also found a similar issue with the default EBB in the branch_table instruction, so there's also a test for this.
@tyler mind to have a look, please? Thanks!
=> Fixes #738: Check ebbs used in jump tables in the verifier

cranelift-codegen/meta/src/cdsl/ast.rs, cranelift-codegen/meta/src/cdsl/cpu_modes.rs, cranelift-codegen/meta/src/cdsl/inst.rs, cranelift-codegen/meta/src/cdsl/isa.rs, cranelift-codegen/meta/src/cdsl/mod.rs, cranelift-codegen/meta/src/cdsl/operands.rs, cranelift-codegen/meta/src/cdsl/type_inference.rs, cranelift-codegen/meta/src/cdsl/typevar.rs, cranelift-codegen/meta/src/cdsl/xform.rs, cranelift-codegen/meta/src/gen_inst.rs, cranelift-codegen/meta/src/gen_legalizer.rs, cranelift-codegen/meta/src/isa/arm32/mod.rs, cranelift-codegen/meta/src/isa/arm64/mod.rs, cranelift-codegen/meta/src/isa/riscv/mod.rs, cranelift-codegen/meta/src/isa/x86/legalize.rs, cranelift-codegen/meta/src/isa/x86/mod.rs, cranelift-codegen/meta/src/lib.rs, cranelift-codegen/meta/src/shared/legalize.rs, cranelift-codegen/meta/src/shared/mod.rs, cranelift-codegen/meta/src/srcgen.rs, cranelift-codegen/meta/src/unique_table.rs
This now works and passes all the tests, including the Spidermonkey tests (when Cranelift is used as the main compiler).
When selecting specific targets at compile time, it does even more than the current Python module: the latter was creating all the legalizations for all the platforms independently of the selected ISA targets. The Rust code does only create legalizations that are used for the current target.
cc @bjorn3 because more code than I expected might be shared (instruction predicates in particular), so we might need to sync.
TODO:
=> [meta] Port legalization to the Rust crate

cranelift-codegen/src/isa/x86/enc_tables.rs, filetests/isa/x86/legalize-div-traps.clif
... when the input is a constant immediate.
=> Avoid inserting checks during div/rem legalization

cranelift-faerie/src/backend.rs, cranelift-module/src/lib.rs, cranelift-module/src/module.rs
Hi! I'm working on some [changes](https://github.com/fastly/lucet/pull/136) for Lucet that need to get at the whole list of compiled functions after they've been translated to the target architecture.
This is a pair of changes that does that, and also populates `FaerieCompiledFunction` with the same kinds of data as `SimpleJITCompiledFunction`. I really just need function sizes, but I figure making them consistent keeping the code bytes in `FaerieCompiledFunction` too couldn't hurt.
=> Expose function definitions, populate FaerieCompiledFunction

cranelift-wasm/Cargo.toml, cranelift-wasm/src/code_translator.rs, cranelift-wasm/src/environ/dummy.rs, cranelift-wasm/src/environ/spec.rs, cranelift-wasm/src/func_translator.rs, cranelift-wasm/src/lib.rs, cranelift-wasm/src/state.rs
@pchickey Great idea to use `failure::Error`! It requires an `std` build because it's only defined there; I've made the `User` variant in `WasmError` defined only in this case, which is a bit weird. Any better idea?
The rest of the patch is pretty mechanical:
- I've grouped infallible getters in the `FuncEnvironment` trait (and dummy impl).
- I've removed `PartialEq` and `Eq` from `WasmError`, because 1. `failure::Error` doesn't support those, and 2. I argue that one will explicitly need to match on the possible enum values anyways most of the time. (Maybe tests might suffer from this, though?)
- Transitively propagate `WasmResult` to their callers.
- There are changes around hash maps, where instead of using `hashmap.entry(key).or_insert_with(F)` where hashmap has type `T` and F returns …
=> [wasm] Make FuncEnvironment functions fallible

cranelift-codegen/src/isa/constraints.rs
What I mean is, `ConstraintKind::Tied` forces the `tied_ops` flags to be true, but `ConstraintKind::FixedTied` does not - it only forces `fixed_ins` or `fixed_outs`, as the case may be.  (These appear only to be used in coloring, and `tied_ops` and `fixed_outs` are only used once each, while `fixed_ins` is not used at all.)
=> Clarify that FixedTied constraints are not Tied

cranelift-codegen/src/context.rs, cranelift-codegen/src/ir/dfg.rs, cranelift-codegen/src/ir/function.rs, cranelift-codegen/src/ir/mod.rs, cranelift-codegen/src/legalizer/heap.rs, cranelift-codegen/src/lib.rs, cranelift-codegen/src/print_errors.rs, cranelift-codegen/src/regalloc/context.rs, cranelift-codegen/src/regalloc/liveness.rs, cranelift-codegen/src/value_label.rs, cranelift-codegen/src/write.rs, cranelift-frontend/src/frontend.rs, cranelift-wasm/src/code_translator.rs, cranelift-wasm/src/environ/dummy.rs, cranelift-wasm/src/func_translator.rs, cranelift-wasm/src/lib.rs, cranelift-wasm/src/translation_utils.rs, cranelift-wasm/tests/wasm_testsuite.rs, fuzz/fuzz_translate_module.rs, src/clif-util.rs, src/wasm.rs
- attaches `ValueLabel` to every values that store the (wasm) variable value
- use Liveness object to recover and group ranges for particular label
- visualization of the results
TODO:
Example:
https://gist.github.com/yurydelendik/46e12a65afc63d866b8482915dfe286b#file-fib2-wasm
=> Reconstruct locations of the original source variable

cranelift-wasm/Cargo.toml, cranelift-wasm/src/environ/spec.rs
As said on IRC, using `failure::Error` requires to have the `failure/std` feature set, which adds an old version of `backtrace` as a crate dependency. In addition to supplementary compilation cost (the build is longer!), it also means that some platforms won't quite work: windows aarch64 in particular doesn't plain work.
A few options I've considered:
- go the hard, open-source way, and update `backtrace` in `failure` etc. This would be my preferred way to do things, but that implies a lot of reliance on external factors (`failure` accepting the pull request, releasing a new version etc.) and our work (on Spidermonkey) is unfortunately blocked by this. So I've removed the one use of the `failure::Error` in the code, and the `failure/std` dependency.
- instead of having a `failure::Error`, …
=> [wasm] Have the WasmError::User member be a String

cranelift-codegen/meta-python/isa/x86/encodings.py, filetests/isa/x86/binary32.clif, filetests/isa/x86/binary64.clif, filetests/isa/x86/legalize-rotate.clif
While looking at #526, I noticed that x86 encoding does not exists for rotation with immediate values.
This pull request is adding encoding for left and right rotation with immediate value, as well as test cases to check that we legalize & generate the expected bytes.
However, I have no idea if the current python rules for encoding have any checks for the validity of the immediate value range.
=> Add x86 encoding for rotr_imm and rotl_imm.

cranelift-codegen/meta/src/cdsl/ast.rs, cranelift-codegen/meta/src/cdsl/inst.rs, cranelift-codegen/meta/src/isa/x86/legalize.rs, cranelift-codegen/meta/src/shared/legalize.rs
It's neater and avoids the extra `bind` import when it's needed. @nbp I think you wanted something like this when we looked at a previous PR, so asking you for review please :)
=> [meta] bind() should be a {Bound,}Instruction method and not a static func

cranelift-codegen/meta-python/base/formats.py, cranelift-codegen/meta-python/base/instructions.py, cranelift-codegen/meta-python/isa/x86/encodings.py, cranelift-codegen/meta-python/isa/x86/recipes.py, cranelift-codegen/meta/src/shared/instructions.rs, cranelift-codegen/src/regalloc/reload.rs, cranelift-codegen/src/verifier/mod.rs
This is also https://bugzilla.mozilla.org/show_bug.cgi?id=1552737.
Cranelift currently has a tendency to create redundant copies (self-copies) of
values from a stack slot back to the same stack slot.  This generates a
pointless load and store and an unnecessary register use.  The copies are
created by `visit_inst` in regalloc/reload.rs.  They appear to occur mostly,
but not exclusively, at loop heads.  It's unclear why this happens.
This patch adds a special case to `visit_inst` to find such copies.  They are
converted into a new instruction, `copy_nop`, which takes and produces the
same SSA names, so as not to break any of the SSA invariants, but which has a
zero-length encoding, hence removing the copy at emission time.
`copy_nop`s source and destination operands must be stack slots and …
=> Cranelift: Redundant stack-slot-to-stack-slot copy removal.

cranelift-wasm/src/func_translator.rs
`https://webassembly.github.io/spec/binary/modules.html#code-section` is not found.
=> Fix url in comments

cranelift-codegen/meta-python/isa/x86/encodings.py, filetests/isa/x86/legalize-br-icmp.clif, filetests/isa/x86/relax_branch.clif, filetests/regalloc/coloring-227.clif
this is a pretty small change, and only affects codegen for opt levels below `Best`, but there's no reason I'm aware of outside padding to emit rex prefixes here even in those modes.
=> Remove rex-prefixed recipes for x86_64 e9 and eb jumps

cranelift-codegen/src/binemit/memorysink.rs, cranelift-codegen/src/binemit/mod.rs, cranelift-codegen/src/binemit/relaxation.rs, cranelift-codegen/src/context.rs, cranelift-codegen/src/isa/x86/binemit.rs, cranelift-faerie/src/backend.rs, cranelift-filetests/src/test_binemit.rs, cranelift-filetests/src/test_compile.rs, cranelift-module/src/module.rs, filetests/isa/x86/binary64.clif, src/compile.rs, src/wasm.rs
This patch generalizes the information that is available about the compiled-code vector in the following ways:
- it records the offsets to and sizes of the different sections of the compiled-code vector
(machine code, jump tables, raw bits)
- it records (by means of the existing reloc system) the locations in the code portion that need to be
fixed up if the jump tables or raw bits are moved relative to the code.
- it propagates a new structure, CodeOffsets, around where needed as a generalization of the
existing ad-hoc system for code_size / total_size.
(At the moment, there are no "raw bits" but we keep talking about needing constant pools, so I put in the trivial bits to support this, to suggest the way forward.  There are two remaining TODO comments that would need to be dealt with for …
=> Generalize information about compiled code

.travis.yml, cranelift-wasm/Cargo.toml, cranelift-wasm/src/environ/dummy.rs, cranelift-wasm/src/sections_translator.rs
Now that `try_from` is in stable Rust, we can use it here.
=> Use `try_from` instead of the cast crate.

cranelift-faerie/src/backend.rs, cranelift-simplejit/src/backend.rs
See issue #789: this reloc for jump table entries can be ignored by back-ends that don't need to split apart code and its rodata/jump tables.  This patch implements the ignoring for simplejit and faerie.
=> Handle Reloc::X86PCRelRodata4 in sundry reloc_jt

cranelift-codegen/src/binemit/memorysink.rs
The calculation for rodata_size subtraced only the jump table size from the current offset, but had to subtract the sum of all the previous sections, including the code.
=> Fix a calculation error for rodata_size in memsink

cranelift-codegen/meta-python/base/instructions.py, cranelift-codegen/meta/src/shared/instructions.rs, filetests/licm/jump-table-entry.clif
The Cranelift instruction `jump_table_entry` loads the jump table entry based on a user-controlled index value that's passed. It's possible to have LICM hoist these instructions above a loop, since they're not considered dangerous in any way. The thing is that the jump table bounds check (`brif` as generated/optimized) is not tied in any way to the `jump_table_entry` instruction, so it's not hoisted at the same time as the jump_table_entry. As a matter of fact, the entry loading may be hoisted (with the user controlled value) before the bounds check is carried out.
This PR marks "jump_table_entry" instructions as loading instructions, since they actually load from memory based on a user-controlled index, thus LICM considers them more dangerous.
=> Mark the jump_table_entry Instruction as loading

cranelift-wasm/src/sections_translator.rs
fixes a small typo I found in the doc comment of `cranelift-wasm/src/sections_translator.rs`
=> fix sections translator doc comment

README.md
Travis CI is testing 1.34, so update the README.md to match.
=> Update the Rust version badge to match what's tested in CI.

cranelift-codegen/src/verifier/mod.rs
This patch adds a verification executed by `verify_if` which checks that EBB are ending with branches with no interleaved instructions. These checks are enabled only when the environment variable `CRANELIFT_BB` is set.
While checking for branches ending an EBB is not the same as a BB, such as conditional branch + terminator, this is a first step towards moving to BB.
=> Add verification phase to migrate from EBB to BB.

cranelift-wasm/src/code_translator.rs, cranelift-wasm/src/sections_translator.rs, cranelift-wasm/src/translation_utils.rs
Panicking when seeing unexpected types is a bit harsh on embedders, instead we can properly return an Error type that can be gracefully handled by the embedder. This is for [bug 1562392](https://bugzilla.mozilla.org/show_bug.cgi?id=1562392).
=> [wasm] Don't panic when seeing unexpected types but properly fail instead

.travis.yml, README.md
Rust 1.34 gets errors like this:
```
$ cargo +1.34.0 build --release
Compiling cranelift-wasm v0.32.0 (cranelift/cranelift-wasm)
error[E0259]: the name `std` is defined multiple times
|
= note: `std` must be defined only once in the type namespace of this module
error: aborting due to previous error
For more information about this error, try `rustc --explain E0259`.
error: Could not compile `cranelift-wasm`.
To learn more, run the command again with --verbose.
```
Updating to Rust 1.35 fixes this.
=> Bump the required rust version to 1.35.

cranelift-codegen/meta/src/cdsl/ast.rs, cranelift-codegen/meta/src/cdsl/cpu_modes.rs, cranelift-codegen/meta/src/cdsl/formats.rs, cranelift-codegen/meta/src/cdsl/instructions.rs, cranelift-codegen/meta/src/cdsl/isa.rs, cranelift-codegen/meta/src/cdsl/settings.rs, cranelift-codegen/meta/src/gen_legalizer.rs
This starts at 4336356 (part 1 to be merged soon)
Things that might help review:
- f69aae6b894c7c865cf6a6cb0d4af28fd86f0243 adds a mapping between global and local transform groups (= legalization transform groups) indices. That's because all the transform groups are stored within a single array (that's the "global" index into `shared_def.transform_groups`), while when they get used by an ISA, references to transform group refer to a per-ISA array (present in the per-ISA file, e.g. `legalize-x86.rs`). This mapping is used when generating the legalization files, and later when generating encodings (and mapping into the local legalization array when no encodings are found).
- the instruction predicates are unused as of now, but get used in the next commits.
- there's no way / no need to …
=> Meta port 2: more instruction predicates + transform group mapping

cranelift-codegen/meta/src/cdsl/cpu_modes.rs, cranelift-codegen/meta/src/cdsl/encodings.rs, cranelift-codegen/meta/src/cdsl/isa.rs, cranelift-codegen/meta/src/cdsl/mod.rs, cranelift-codegen/meta/src/cdsl/recipes.rs, cranelift-codegen/meta/src/cdsl/regs.rs, cranelift-codegen/meta/src/cdsl/types.rs, cranelift-codegen/meta/src/isa/arm32/mod.rs, cranelift-codegen/meta/src/isa/arm64/mod.rs, cranelift-codegen/meta/src/isa/riscv/encodings.rs, cranelift-codegen/meta/src/isa/riscv/mod.rs, cranelift-codegen/meta/src/isa/riscv/recipes.rs, cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/mod.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs, cranelift-codegen/meta/src/shared/legalize.rs, cranelift-codegen/meta/src/shared/types.rs
This starts at b52daeb.
This tries to be very close to the Python code, minus Python meta-programming features. Recipes have been ported manually, since there aren't so many of them; encodings have been mostly automatically generated, with some manual adjustments and some manually written (before I got bored and implemented the meta-meta-Rust generator).
Things that might help review:
- Encodings and recipes might both have InstructionPredicate (e.g. predicates looking at immediate values in instructions) and/or IsaPredicates (e.g. predicates determining if a CPU feature is available or not), but they are totally unrelated, in the sense that an encoding doesn't inherit recipe predicates by default. Encodings' predicates guard against several entries in the encodings list (ENCLIST), while …
=> Meta port 3: encodings + recipes

cranelift-simplejit/src/memory.rs
Fix for https://github.com/CraneStation/cranelift/issues/826.
=> Fix mem::uninitialized depricated since 1.38

cranelift-codegen/meta/src/cdsl/instructions.rs, cranelift-codegen/meta/src/cdsl/type_inference.rs, cranelift-codegen/meta/src/gen_legalizer.rs, cranelift-codegen/src/ir/instructions.rs, cranelift-codegen/src/ir/types.rs, cranelift-codegen/src/isa/x86/enc_tables.rs, cranelift-codegen/src/legalizer/mod.rs
When debugging together the generation of splat with @abrown, I've found a few issues in the generation of legalization.
- a spurious assert I added, which doesn't hold when you have a test on a dependent type: `splat` has a test on `some_type_var.lane_of()` which must be equal to something else, and `some_type_var.lane_of` can't belong to the original set of variables, because it's not a free variable in the first place.
- second commit adds a simple alias for `ir::Types::lane_type()`, which was unused so far by the meta code, but should have been named `lane_of()` for type variable constraints. I think it makes sense to keep both names, since each has a useful meaning in different contexts.
- third commit emits type variables variables (sigh... "Rust variables for type variables"), in …
=> [meta] Legalization fixes and small improvements

cranelift-codegen/src/isa/riscv/enc_tables.rs
This is an FYI: merging so this unbreaks the build.
=> Build fix: add crates::predicates to the Riscv enc_tables file

cranelift-codegen/src/ir/dfg.rs
Nothing exciting, just was reading through. Would have pushed it immediately, but didn't want to subvert the mandatory-review policy that's just a few days old.
=> Fix an outdated comment referring to `FunctionLayout` instead of `Layout`

cranelift-codegen/meta/src/gen_encodings.rs
`length` was `usize` before in the code below, but the immediate overflows 32 bits, so do an explicit cast before the comparison.
=> Fix usize comparison in the meta crate

cranelift-codegen/meta/src/isa/riscv/encodings.rs, cranelift-codegen/meta/src/isa/riscv/recipes.rs
This adds back the stacknull recipes/encodings for copy_nop, that probably disappeared during rebasing of the meta port onto master. Hopefully there aren't too many of those...
=> [meta] Riscv: add back stacknull encodings for copy_nop;

cranelift-simplejit/Cargo.toml, cranelift-simplejit/src/memory.rs
A fix using [anonymous memory maps](https://crates.io/crates/memmap); locked behind a feature just in case, since it isn't necessary unless you are enforcing SELinux policies.
=> issue #772: added a memmap replacement to support selinux

cranelift-codegen/src/ir/function.rs, cranelift-frontend/src/frontend.rs
Hello!
Apologies about the trivial commit; just happened to see this code and thought I'd send a PR.  As far as I'm aware, there are no downsides to using the `Default` trait here (`Position::default()` still works), and it's more 'standard' in my mind.
from a quick grep there are other instances of `default` methods, if they're also just calling default, then we can do the same thing more widely.  If that's something you all are interested in I can add more to this PR tonight
=> Change Postion's default method into one from Default trait

cranelift-simplejit/src/backend.rs, cranelift-simplejit/src/memory.rs
There are warnings about unused imports on Windows.
=> Do not import libc on windows

cranelift-codegen/meta/src/cdsl/instructions.rs, cranelift-codegen/meta/src/gen_legalizer.rs, cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/instructions.rs, cranelift-codegen/meta/src/isa/x86/legalize.rs, cranelift-codegen/meta/src/isa/x86/mod.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs, cranelift-codegen/meta/src/isa/x86/settings.rs, cranelift-codegen/meta/src/shared/instructions.rs, cranelift-codegen/meta/src/shared/mod.rs, cranelift-codegen/meta/src/shared/settings.rs, cranelift-codegen/src/ir/immediates.rs, cranelift-codegen/src/isa/riscv/settings.rs, cranelift-codegen/src/isa/x86/abi.rs, cranelift-codegen/src/isa/x86/mod.rs, cranelift-codegen/src/settings.rs, filetests/isa/x86/binary32-float.clif, filetests/isa/x86/binary64-float.clif, filetests/isa/x86/insertlane.clif, filetests/isa/x86/legalize-splat.clif, filetests/isa/x86/pshufb.clif, filetests/isa/x86/pshufd.clif, filetests/isa/x86/raw_bitcast.clif, filetests/isa/x86/scalar_to_vector.clif
This is a work in progress and not ready to merge but I am opening the PR for discussion (see #803). I will highlight my top questions in the code below.
[edit] This should be ready for a real review now; I've resolved all of the discussion issues.
=> Implement splat instruction for x86

cranelift-codegen/Cargo.toml, cranelift-codegen/src/verifier/mod.rs
This allows prefixing BB-specific code with "#[cfg(feature = "basic-blocks")]", which avoids having to reference an environment variable across the codebase.
The easiest way to enable the feature locally is to add the arguments `features = ["basic-blocks"]` to the workspace Cargo.toml, where it defines the cranelift-codegen dependency. If you're just building cratelift-codegen, you can also use `cargo build --features="basic-blocks"`.
This makes it easier to add BB-specific logic across the codebase.
=> Enable basic block checks through a feature

cranelift-codegen/src/ir/function.rs, cranelift-codegen/src/verifier/mod.rs, cranelift-frontend/Cargo.toml, cranelift-frontend/src/frontend.rs
To use, enable the "basic-blocks" feature on cranelift-frontend.
The logic defining a basic block is now shared between `cranelift-frontend` and `cranelift-codegen`, hanging off the `Function` (unfortunately there's no other great place to put it -- you need `dfg` and `layout` access).
This doesn't change the FunctionBuilder interface in any way. The first step is to enable the "basic-blocks" feature, then to make it unconditional, and finally we can remove concepts like "body blocks."
=> Verify that FunctionBuilder blocks are basic blocks in debug mode

cranelift-frontend/src/frontend.rs, cranelift-wasm/Cargo.toml, cranelift-wasm/src/code_translator.rs, cranelift-wasm/src/func_translator.rs
This is a very simple transformation. Most of the work was just getting a pipeline set up so that I could actually check that the changes were working. I included some other commits, which also make error messages significantly more useful.
This changes:
```
...
@00b3 [RexOp2urm_noflags#4b6,%rcx]  v13 = bint.i32 v12
@00b6 [RexOp1r_ib#4083,%rcx]        v15 = band_imm v13, 1
@00b8 [RexOp1tjccb#74]              brz v15, ebb3 *****
@00bc [RexOp1pu_id#b8,%rcx]         v18 = iconst.i32 7
@00be [RexOp1umr#89,%rdx]           v29 = uextend.i64 v7
@00be [RexOp1ld#808b,%rbx]          v30 = load.i64 notrap aligned readonly v1
@00be [RexOp1stWithIndexDisp8#89]   store_complex v18, v30+v29+12
@00c1 [Op1jmpb#eb]                  jump ebb2
...
```
Into:
```
...
@00c9 [RexOp2urm_noflags#4b6,%rcx]  v13 = …
```
=> Generate basic blocks for Wasm `br_if` statements.

Cargo.toml
I am not sure if this is the correct way, but now `cargo build --features basic-blocks` seems to work as expected, when executed at the top-level.
=> Add basic-blocks feature flag at the top-level Cargo.toml.

filetests/licm/jump-table-entry.clif
This is a minor change which fix a recently added test case.
=> Fix licm/jump-table-entry.clif test case to work with basic blocks.

cranelift-codegen/src/cursor.rs
This adds an assertion similar to the verifier, except that it catches issues as soon as they are added to the graph instead of catching issues later on.
This assertion allow to stop all errors when they are introduced and would be useful for fixing the issue with the register allocator which inserts copy instruction.
I will not request a review yet, as this is at the moment just a convenient assertion while making progress, but we would want this assertion to be in place once all test pass and while we have not yet changed the data structure to be Basic Blocks instead of Extended Basic Blocks.
=> Assert BB-like every time an instruction is added

cranelift-wasm/src/code_translator.rs, cranelift-wasm/src/environ/spec.rs, cranelift-wasm/src/func_translator.rs, cranelift-wasm/src/lib.rs, cranelift-wasm/src/state.rs
In some circumstances we'd like to insert instructions, and update translator-internal state, based on the wasm operations being translated. This adds a pair of functions to `FuncEnvironment` to support that (and adjusts `func_translator` to call them appropriately)
=> cranelift-wasm hooks to instrument wasm operators

cranelift-wasm/src/code_translator.rs
This is a dead-simple patch. The tricky part for me was just validating it.
I was confused by [the WebAssembly specification for control instructions](https://webassembly.github.io/spec/core/syntax/instructions.html#syntax-instr-control) which specifies `if` blocks as `if resulttype instr* else instr* end`.
When an example of valid syntax is actually `if resulttype test then else`. For example:
```
(func $getCell (param $x i32) (param $y i32) (result i32)
(if (result i32)
(block (result i32)
(i32.and
(call $inRange
(i32.const 0)
(i32.const 50)
(get_local $x)
)
(call $inRange
(i32.const 0)
(i32.const 50)
(get_local $y)
)
)
)
(then
(i32.const 5)
)
(else
(i32.const 0)
)
)
)
```
The attached patch changes the generation of that code to use basic blocks (again -- the code below is after all …
=> Generate basic blocks for wasm if..then..else.

cranelift-entity/src/primary.rs, cranelift-wasm/src/translation_utils.rs
Required by https://github.com/CraneStation/wasmtime/pull/221. Version bump is needed, too.
=> Derive Hash for some types

cranelift-wasm/src/module_translator.rs
from the [WebAssembly Specifications](https://webassembly.github.io/spec/core/binary/modules.html#binary-importsec)
> The preamble is followed by a sequence of sections. Custom sections may be inserted at any place in this sequence, while other sections must occur at most once and in the prescribed order. All sections can be empty.
=> check no other sections after data section

cranelift-wasm/src/environ/spec.rs, cranelift-wasm/src/func_translator.rs, cranelift-wasm/src/lib.rs
It turned out very quickly that we did need `TranslationState` after all
=> Stateful translate operator callbacks

cranelift-wasm/src/environ/spec.rs, cranelift-wasm/src/func_translator.rs, cranelift-wasm/src/lib.rs, cranelift-wasm/src/state.rs
Followup to https://github.com/CraneStation/cranelift/pull/879, to only expose what we feel is a stable API for information in `TranslationState`
=> Hide wasm TranslationState innards

cranelift-codegen/src/simple_preopt.rs, filetests/simple_preopt/div_by_const_power_of_2.clif, filetests/simple_preopt/simplify.clif
- first commit enables more usage of `_imm` instructions, for some which didn't have it.
- second commit allows folding of binary-with-immediates chains together, whenever it's possible to easily apply the instruction to the immediates.
- third commit pattern matches `(x << N) >> N` and transforms it into an (un)signed-extended move whenever possible.
I need to measure on benchmarks if this has an effect (so far I'm seeing mostly noise, so this is hard to tell).
=> Moar simple preoptimizations

cranelift-codegen/src/simple_preopt.rs, filetests/simple_preopt/simplify.clif
when replacing BinaryImm, we use the prior arg, but later use the arg that was replaced when writing an alias if we can determine the new op is actually equivalent to a simple copy
this was found with `strlen("a")` returning 2 in some wasm downstream, but I reduced that down to the test case here.
I was surprised to see in writing the test case that runners for cases in `filetests` have a lot of variance - should `simple_preopt` and `preopt` be merged together? the cases in `preopt` ought to fail under the full `preopt` run, but are only tested with respect to only some of the constant folding done in `simple_preopt`
=> Preopt: use replaced arg after having replaced BinaryImm

cranelift-codegen/src/legalizer/mod.rs, filetests/legalizer/empty_br_table.clif
This changes adds a test case which fails when trying to legalize the a empty jump table, and the corresponding changes make the test pass.
This should fix a wasm issue reported to me by @julian-seward1 .
=> Properly legalize with empty jump tables.

cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/shared/instructions.rs, cranelift-codegen/src/legalizer/mod.rs, filetests/isa/x86/legalize-br-table.clif, filetests/licm/jump-table-entry.clif
This makes non-legalized jump table instructions operate on operands with
pointer-sized types. This means we need to extend smaller types into the
pointer-sized operand, when the two don't match.
This has the nice benefit to remove the controlling type variable from `jump_table_entry`, and now all the variables involved have the same type (both the input operands and the returned value).
@sunfishcode, assigning you for review since we discussed this offline. Thanks!
=> Simplify jump table instructions and add missing conversion

cranelift-codegen/meta/src/gen_binemit.rs, cranelift-codegen/src/binemit/shrink.rs
This is a minor change, which make use use `divert.regmove`, `divert.regspill` and `divert.regfill` only within the coloring phase of the compiler. All other phases now rely on `divert.apply`.
This is a side-effect of a change that I initially made and reverted where I attempted to split `RegDiversions` in 2, one meant to record the `EntryRegDiversions` added in #883, and another one meant to read the content of it.
The difference between the coloring phase and others, is that the coloring phase will add the `regmove` instructions, whereas others are only following what is already present in the DFG.
=> Use divert apply everywhere outside the coloring phase.

cranelift-codegen/meta/src/cdsl/recipes.rs, cranelift-codegen/meta/src/isa/x86/encodings.rs
I noticed (well, Clippy noticed) that EncodingRecipe had a default implementation of Hash, but a PartialEq implementation that didn't take name into account. So I went looking to see what made use of the Hash implementation and found a map from EncodingRecipe to EncodingRecipeNumber. It kind of looked like it was trying to detect calls to add_recipe with an equal EncodingRecipe, but a different name - except that due to the Hash implementation taking name into account, it wouldn't really have been doing that. Also, the assertion message seemed to imply that it was actually different recipes with the same name that we cared about, so I changed the code to match the assertion message.
=> Fix an assertion that wasn't doing what it said

cranelift-codegen/src/ir/entities.rs, cranelift-codegen/src/ir/mod.rs, cranelift-codegen/src/ir/stackslot.rs, cranelift-codegen/src/ir/valueloc.rs, cranelift-codegen/src/value_label.rs
While rebasing https://github.com/CraneStation/wasmtime/pull/63, found that ValueLabel and StackSlots are not marked for serialization -- this patch addresses that.
/cc @Mrowqa
=> Serialize ValueLabel and StackSlots

cranelift-wasm/src/code_translator.rs, cranelift-wasm/src/environ/dummy.rs, cranelift-wasm/src/environ/mod.rs, cranelift-wasm/src/environ/spec.rs, cranelift-wasm/src/func_translator.rs, cranelift-wasm/src/sections_translator.rs, cranelift-wasm/src/translation_utils.rs
This method in particular needs to accommodate failure because any table index other than zero is
currently invalid.
It's possible that other `ModuleEnvironment` methods would benefit from fallibility, but I didn't want to add too much noise to this PR without being sure. If y'all would prefer doing them all at once, let me know which methods would benefit and I can handle the changes.
**Update**: Per discussion in this thread, the result type has been changed for most of the other `ModuleEnvironment` functions, and along the way some panics have been transformed into `Err`s.
=> Return a `WasmResult` from `ModuleEnvironment` methods

cranelift-codegen/src/binemit/relaxation.rs, cranelift-codegen/src/context.rs, cranelift-codegen/src/flowgraph.rs, cranelift-codegen/src/ir/function.rs, cranelift-codegen/src/licm.rs, cranelift-filetests/src/test_binemit.rs, filetests/isa/x86/binary64.clif, filetests/isa/x86/legalize-br-table.clif
This adds a `fold_redundant_jumps()` pass to the branch relaxation phase. Nicolas' basic-blocks regalloc patch splits critical edges: if those edges are unused by register allocation, the blocks can be folded back up. Not doing so produces weird codegen where you jump to a jump to a jump.
For example:
Before:
```
Disassembly of 22 bytes:
0:	55                   	push	rbp
1:	48 89 e5             	mov	rbp, rsp
4:	b8 08 00 00 00       	mov	eax, 8
9:	83 ff 05             	cmp	edi, 5
c:	7f 04                	jg	0x12
e:	89 f8                	mov	eax, edi
10:	eb 02                	jmp	0x14
12:	eb fc                	jmp	0x10
14:	5d                   	pop	rbp
15:	c3                   	ret
```
After:
```
0:	55                   	push	rbp
1:	48 89 e5             	mov	rbp, rsp
4:	b8 08 00 00 00 …
```
=> WIP: Add fold_redundant_jumps() pass to the branch relaxation phase.

cranelift-codegen/meta/src/shared/settings.rs, cranelift-codegen/src/ir/libcall.rs, cranelift-codegen/src/isa/call_conv.rs, cranelift-codegen/src/legalizer/libcall.rs, cranelift-codegen/src/settings.rs
This adds up a new way to tell which calling convention should be used when expanding instruction opcodes into libcall calls. Most of the time this should match the default calling convention, but in the case of Baldrdash, which uses special thunks for libcall functions, we need to use the Baldrdash calling convention too.
This tries to be more generic by allowing more calling conventions for other libcalls; I *think* this could be useful (for emulators? for JITs which want to use a calling convention different to the host's), but I am a bit unsure about this. So maybe we could do something simpler here, and instead have a boolean setting "enable baldrdash callconv for libcalls" (but that's very ad-hoc). Opinions welcome.
=> Adds the libcall_call_conv setting and use it for libcall calls expansion

cranelift-codegen/meta/src/shared/settings.rs, cranelift-codegen/src/ir/extfunc.rs, cranelift-codegen/src/ir/libcall.rs, cranelift-codegen/src/isa/call_conv.rs, cranelift-codegen/src/isa/mod.rs, cranelift-codegen/src/isa/x86/abi.rs, cranelift-codegen/src/legalizer/libcall.rs, cranelift-reader/src/parser.rs, docs/heapex-dyn.clif, docs/heapex-sm32.clif, docs/heapex-sm64.clif, docs/ir.rst, filetests/isa/x86/abi64.clif, filetests/isa/x86/legalize-memory.clif, filetests/isa/x86/legalize-splat.clif, filetests/isa/x86/relax_branch.clif, filetests/legalizer/br_table_cond.clif, filetests/parser/call.clif, filetests/regalloc/aliases.clif, filetests/regalloc/iterate.clif, filetests/regalloc/unreachable_code.clif
The baldrdash calling convention was merely copying SystemV, adding the loading of the additional WasmTlsReg before calling into functions using this calling convention. This adds a new Baldrdash calling convention that does the same for Windows. I've preferred creating a new calling convention, rather than adding a flag in the CallConv structure, because SystemV / BaldrdashSystemV (resp WindowsFastCall) are quite similar at the moment, they're likely to diverge later, would we implement callee-saved registers, or tail calls, etc.
Also renamed baldrdash into baldrdash_system_v, to make it less error-prone.
=> Implement a Baldrdash calling convention for Windows

cranelift-codegen/src/simple_preopt.rs, filetests/simple_preopt/div_by_const_indirect.clif, filetests/simple_preopt/div_by_const_non_power_of_2.clif, filetests/simple_preopt/div_by_const_power_of_2.clif
As discussed by emails, this replaces copies in simple_preopt to use more aliasing instead. There's another `replace_with_aliases` method in the DFG data structure, but it doesn't exactly do what we want (it replaces the results of one instruction by the results of another). Arguably, this could be put in the DFG data structure too, with a different name.
=> Use aliasing instead of copying in simple_preopt

cranelift-codegen/src/binemit/memorysink.rs, cranelift-faerie/src/backend.rs, cranelift-frontend/src/frontend.rs, cranelift-wasm/src/module_translator.rs, test-all.sh
Uses rustdoc nightly to build documentation.
Checks that documentation links aren't broken using `cargo-deadlinks`.
Installs `cargo-deadlinks` if it's not already installed.
Addresses https://github.com/CraneStation/cranelift/issues/901
=> Fix broken documentation links

cranelift-codegen/meta/src/cdsl/instructions.rs, cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/legalize.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs, cranelift-codegen/meta/src/isa/x86/settings.rs, filetests/isa/x86/extractlane.clif, filetests/isa/x86/pshufb.clif, filetests/isa/x86/pshufd.clif, filetests/isa/x86/scalar_to_vector.clif
The primary commit for this is 9785535 but the following three are improvements from comments to #833 or suggested by the IDE (9a036ec).
=> Implement extractlane instruction for x86

Cargo.toml, cranelift-codegen/Cargo.toml
This is a small patch for an issue originally brought up over on the Wasmtime repository: https://github.com/CraneStation/wasmtime/issues/189
In a nutshell, `cranelift-codegen` had enabled all architecture support in its `default` feature, and, for one reason or another, it's very difficult to disable the `default` feature from within Wasmtime. This makes it hard for projects that want to pick and choose which architectures they want Wasmtime to build for.
As a result, the solution pitched was to remove all architecture support from the `default` feature and allow dependencies to enable the exact architecture support they wanted. That's what this patch hopes to achieve.
For ease of use, there is a new `all-arch` feature included that enables all architecture support -- just as …
=> Remove all default architecture support in cranelift-codegen to allow dependencies fine-grained control

Cargo.toml, cranelift-codegen/src/binemit/memorysink.rs, cranelift-codegen/src/binemit/mod.rs, cranelift-filetests/Cargo.toml, cranelift-filetests/src/function_runner.rs, cranelift-filetests/src/lib.rs, cranelift-filetests/src/test_run.rs, filetests/isa/x86/run-const.clif, src/clif-util.rs, src/run.rs
This depends on the change in #872; adds the ability to start running CLIF as a part of the build automation. As mentioned there, future commits will add a way (e.g. `fork`) to avoid crashing the test process if a test fails and a more flexible expression syntax for asserting results (e.g. `run: fn(...) == ...`).
=> Add `test run` to cranelift-filetests to allow executing CLIF

cranelift-codegen/meta/src/gen_legalizer.rs
=> Sort custom_legalizes for more deterministic generated code

cranelift-filetests/Cargo.toml, cranelift-filetests/src/function_runner.rs
#890 introduced a dependency on the `mmap` crate, which doesn't support Windows. A quick investigation showed mmap is not actively maintained, so [people mostly use the `memmap` crate](https://github.com/cgag/loc/issues/13#issuecomment-256178954). This PR switches to that, and seems to work without issues.
=> Switch from mmap to memmap to support Windows

src/clif-util.rs, src/wasm.rs
I was looking at https://github.com/CraneStation/cranelift/pull/910 and was curious why this included some formatting changes; cargo fmt --all should take care of it, right? It happens that the content of macros isn't analyzed by rustfmt (for obvious good reasons!), and so that rustfmt couldn't figure out that we have a src/wasm.rs module because of this. Just using a plain and simple cfg with feature guard made Rustfmt aware of the module, and caused new formatting changes in this file.
Two things to note:
- in src/disasm.rs, a lot of code is under cfg_if!, so it's not going to be formatted either.
- running rustfmt manually on every rs file in the tree caused formatting changes to the fuzz/ directory. There's something in the fuzz's Cargo file about not messing with the parent …
=> [clif-util] Use a simple cfg guard instead of cfg_if for the wasm module

cranelift-wasm/tests/wasm_testsuite.rs, src/clif-util.rs, src/wasm.rs
While testing out the SIMD instructions I have implemented in https://github.com/abrown/cranelift/tree/work-ahead I discovered that I needed:
- a way to tell `wabt` that SIMD instructions are allowed--this requires updating `wabt-rs` so we can pass `Features`
- a `--enable-simd` flag on `clif-util wasm` to allow me to set the allowed features
- all features enabled by default when running wasmtests (I have wasmtests that could go here but cannot add them to this PR until other PRs are merged; e.g. #855, #868)
=> Add flags to allow SIMD instructions

cranelift-filetests/src/function_runner.rs, cranelift-filetests/src/runone.rs, cranelift-reader/src/lib.rs, cranelift-reader/src/parser.rs, cranelift-reader/src/sourcemap.rs, src/bugpoint.rs, src/compile.rs, src/run.rs
This change allows adding parsing parameters more easily; e.g. a parameter is needed for setting the default calling convention for functions parsed as a part of the `run` test feature.
Previously `test run` used the parser's hard-coded CallConv::Fast as the default calling convention but with this change any test being `run` will use the default calling convention of the machine running the test. `test run` will now throw an error if the calling convention of the function does not match the host's.
=> Add options for parsing test files

cranelift-filetests/src/function_runner.rs, src/run.rs
For this test to run on Windows, the explicit calling convention must be removed so that the parser is free to use the host's calling convention.
=> Remove calling convention on FunctionRunner test

Cargo.toml, cranelift-filetests/Cargo.toml, cranelift-filetests/src/runone.rs, cranelift-reader/src/lexer.rs, cranelift-reader/src/lib.rs, cranelift-reader/src/parser.rs, cranelift-reader/src/testfile.rs
Cranelift can be compiled with feature flags which can change its output. To
accomodate changes of output related to feature flags, test file can now include
`feature "..."` and `feature ! "..."` directives in the preamble of the test
file.
The test runner would skip the test if the flag does not match the expectation
of the test case.
This PR should fix the issue #935 .
=> Add feature flags to test files.

cranelift-codegen/src/ir/constant.rs
Prior to this commit I would see warnings like the following when running `cargo +nightly doc`:
```
warning: `[ir::ConstantData]` cannot be resolved, ignoring it...
--> cranelift-codegen/src/ir/constant.rs:49:22
|
49 | /// [`ConstantData`](ir::ConstantData)).
|                      ^^^^^^^^^^^^^^^^ cannot be resolved, ignoring
|
= note: `#[warn(intra_doc_link_resolution_failure)]` on by default
= help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`
```
I believe the trick is to prepend `crate` (and not `cranelift_codegen` or a relative path) for references inside the file's own crate.
=> Fix documentation warnings in ConstantPool

.azure-pipelines.yml, ci/azure-build-release.yml, ci/azure-install-rust.yml
This should recreate what we have with Travis right now, but run in about 20-25 minutes instead of 3.5 hours.
The Windows builds are disabled right now, because [some tests currently don't work on Windows](https://dev.azure.com/tschneidereit/Cranelift/_build/results?buildId=94). We should get those enabled quickly, and then not regress Windows again :)
=> Add Azure Pipelines CI setup

cranelift-codegen/src/binemit/mod.rs, cranelift-codegen/src/binemit/relaxation.rs, cranelift-codegen/src/binemit/shrink.rs, cranelift-codegen/src/ir/function.rs, cranelift-codegen/src/regalloc/coloring.rs, cranelift-codegen/src/regalloc/diversion.rs, cranelift-codegen/src/regalloc/mod.rs, cranelift-codegen/src/value_label.rs, cranelift-codegen/src/verifier/locations.rs
This patch is a pre-requisite for #844 , which introduces `regalloc::EntryRegDiversions` as part of the `ir::Function`.
Technically we do not require `EntryRegDiversions`, but not having them implies that we would always visit all the blocks in a topological order inspired by the reverse post-order, in order to garantee that the `RegDiversions` for each basic block is recorded before the block is visited.
However, this is not possible as the order of the generated code is expected to be the same as the code within Cranelift, as implies the fact that we have `fallthrough` instructions.
Thus #844 would be changed to record the `RegDiversions` at each basic block entry on the `ir::Function::entry_diversions` field, using the `save_for_ebb` function. The `at_ebb` is used to restore the state …
=> Add EntryRegDiversions to record diversions for each block entry.

cranelift-codegen/meta/src/cdsl/regs.rs, cranelift-codegen/src/binemit/mod.rs, cranelift-codegen/src/isa/x86/binemit.rs, cranelift-codegen/src/regalloc/coloring.rs
(premises for next PR)
- first commit allows to retrieve a register like r15, which will be needed in the next PR
- second commit moves the only static function in regalloc::coloring back into the impl block, using a trick to quiet the borrow-checking gods.
- third commit just tweaks comments.
=> Random refactorings

cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/shared/instructions.rs, filetests/verifier/scalar-to-vector.clif
This makes the scalar_to_vector instruction type sane: it expects the input value to be a lane of the output value. Also removed the reference to XMM registers, because this is a shared instruction for all platforms.
cc @abrown FYI
=> [codegen] Make scalar_to_vector's output type a lane of its input type

Cargo.toml, cranelift-bforest/src/lib.rs, cranelift-codegen/Cargo.toml, cranelift-codegen/src/isa/arm32/mod.rs, cranelift-codegen/src/isa/call_conv.rs, cranelift-codegen/src/isa/mod.rs, cranelift-codegen/src/lib.rs, cranelift-entity/src/lib.rs, cranelift-faerie/Cargo.toml, cranelift-faerie/src/backend.rs, cranelift-frontend/Cargo.toml, cranelift-frontend/src/lib.rs, cranelift-module/src/lib.rs, cranelift-native/Cargo.toml, cranelift-preopt/src/lib.rs, cranelift-reader/Cargo.toml, cranelift-simplejit/Cargo.toml, cranelift-wasm/Cargo.toml, cranelift-wasm/src/lib.rs, fuzz/Cargo.toml, src/disasm.rs
Faerie 0.11.0 has an [updated dependency](https://github.com/m4b/faerie/pull/94) on string-interner 0.7.1, which fixes a [security issue in prior versions](https://github.com/Robbepop/string-interner/issues/9).
Faerie 0.11.0 depends target-lexicon 0.8.0, so the rest of this repo has been updated to use the latest version. The representation of Arm architectures has changed a little bit, simplifying some case statements. The crate no longer requires special feature flags to work as a no-std crate, so many of these flags have been removed from cargo and lib.rs files.
=> Upgrade to target-lexicon 0.8 and faerie 0.11

cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs, cranelift-codegen/meta/src/shared/instructions.rs, cranelift-codegen/meta/src/shared/legalize.rs, cranelift-codegen/src/ir/dfg.rs, filetests/isa/riscv/expand-i32.clif.bak, filetests/isa/riscv/legalize-i64.clif.bak, filetests/isa/x86/binary32.clif, filetests/isa/x86/legalize-i64.clif
Add encodings for iadd carry variants (iadd_cout, iadd_cin, iadd_carry)
for x86_32, enabling the legalization for iadd.i64 to work.
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1576675
Bug: https://github.com/CraneStation/cranelift/issues/765
/cc @bnjbvr @wingo @caitp
=> [codegen] add encodings for iadd carry variants

cranelift-codegen/src/binemit/relaxation.rs
This is a better solution than https://github.com/CraneStation/cranelift/pull/950.
It's obviously possible to do better than this, for example by folding edges that cannot possible be implicit phi nodes. The purpose of this phase is mostly to undo garbage blocks created by register allocation, so this simpler version serves that goal just fine.
=> Limit redundant jump folding to only fold parameterless target blocks

cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs, cranelift-codegen/meta/src/shared/instructions.rs, cranelift-codegen/meta/src/shared/legalize.rs, filetests/isa/x86/binary32.clif, filetests/isa/x86/legalize-i64.clif
Add encodings for isub borrow variants (isub_bout, isub_bin, isub_borrow) for x86_32, enabling the legalization for isub.i64 to work.
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1576675
Bug: https://github.com/CraneStation/cranelift/issues/765
/cc @bnjbvr @wingo @caitp
=> [codegen] add encodings for isub borrow variants

Cargo.toml, cranelift-codegen/Cargo.toml, cranelift-faerie/Cargo.toml, cranelift-frontend/Cargo.toml, cranelift-native/Cargo.toml, cranelift-reader/Cargo.toml, cranelift-simplejit/Cargo.toml, cranelift-wasm/Cargo.toml, fuzz/Cargo.toml
this fixes the compile for arm and aarch64
closes: https://github.com/CraneStation/cranelift/issues/977
I had to rewrite, rebasing this was too much git vodoo for me.
=> upgrade to latest target-lexicon 0.8.1

cranelift-codegen/meta/src/cdsl/ast.rs, cranelift-codegen/meta/src/cdsl/instructions.rs, cranelift-codegen/meta/src/cdsl/xform.rs, cranelift-codegen/meta/src/gen_encodings.rs, cranelift-codegen/meta/src/gen_inst.rs, cranelift-codegen/meta/src/isa/arm32/mod.rs, cranelift-codegen/meta/src/isa/arm64/mod.rs, cranelift-codegen/meta/src/isa/mod.rs, cranelift-codegen/meta/src/isa/riscv/encodings.rs, cranelift-codegen/meta/src/isa/riscv/mod.rs, cranelift-codegen/meta/src/isa/riscv/recipes.rs, cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/instructions.rs, cranelift-codegen/meta/src/isa/x86/legalize.rs, cranelift-codegen/meta/src/isa/x86/mod.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs, cranelift-codegen/meta/src/shared/entities.rs, cranelift-codegen/meta/src/shared/formats.rs, cranelift-codegen/meta/src/shared/immediates.rs, cranelift-codegen/meta/src/shared/instructions.rs, cranelift-codegen/meta/src/shared/legalize.rs, cranelift-codegen/meta/src/shared/mod.rs
... instead of static instances.
This is nice too: it gets the explicit passing to functions that need it (instead of global variables with hacks to make them static), erroneous lookup is impossible, jump-to-definition is better (not as good as static variables: you jump to the definition, and have to look at the constructor to see how it was formed), it doesn't require a new dependency just for the build step.
Would people like this, it'd be much easier to keep on doing this for formats and other things.
cc @abrown @sunfishcode
=> [meta] Use giant structures for Immediates/EntityRefs

cranelift-codegen/meta/src/cdsl/regs.rs, cranelift-codegen/meta/src/gen_registers.rs, cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs, cranelift-codegen/meta/src/isa/x86/registers.rs, cranelift-codegen/meta/src/shared/instructions.rs, cranelift-codegen/meta/src/shared/settings.rs, cranelift-codegen/src/isa/registers.rs, cranelift-codegen/src/isa/x86/abi.rs, cranelift-codegen/src/isa/x86/mod.rs, cranelift-codegen/src/legalizer/heap.rs, cranelift-codegen/src/regalloc/coloring.rs, cranelift-codegen/src/regalloc/register_set.rs, cranelift-codegen/src/regalloc/solver.rs, cranelift-codegen/src/settings.rs, cranelift-codegen/src/verifier/mod.rs, filetests/isa/x86/pinned-reg.clif
Based on #959. So this is very experimental, probably a bit sketchy. This allows pinning one register (r15 on x86 64 bits) so it's entirely in the control of the embedder. In particular, it tries to exclude it from register allocation. Assertions in this code plus all my tests passing make me confident it isn't horribly wrong, but it doesn't prove this is incredibly good either. (I'm a bit worried about local diversions in particular.) Also, this is not enough tested at the moment, I'll try to add more test cases and fuzz this a bit (?).
Second commit adds a second setting that enables use of the pinned register as the heap base when legalizing heap_addr instructions. If the embedder does the Right Thing, and correctly sets the heap base with set_pinned_reg, this is enough to avoid …
=> Allow pinning a certain register in Cranelift, and use it as the heap base

cranelift-codegen/src/isa/mod.rs
This removes the explicit dependency on target-lexicon for the embedder,
which can instead use the ISA's name directly. It can simplify
dependency management, in particular avoid the need for synchronizing
the target-lexicon dependencies versions.
It also tweak the error when an ISA isn't built as part of Cranelift to
be a SupportDisabled error; this was dead code before this.
=> Fixes #984: Add a isa::lookup_by_name function

cranelift-wasm/src/environ/spec.rs, cranelift-wasm/src/module_translator.rs
This commit adds a hook to the `ModuleEnvironment` trait to learn when a
custom section in a wasm file is read. This hook can in theory be used
to parse and handle custom sections as they appear in the wasm file
without having to re-iterate over the wasm file after cranelift has
already parsed the wasm file.
The `translate_module` function is now less strict in that it doesn't
require sections to be in a particular order, but it's figured that the
wasm file is already validated elsewhere to verify the section order.
=> Add a custom section hook to `ModuleEnvironment`

cranelift-codegen/Cargo.toml, cranelift-codegen/src/regalloc/virtregs.rs
Pushing on the `val_stack` vector is CL's biggest source of calls to
malloc/realloc/free, by some margin.  It accounts for about 27.7% of all heap
blocks allocated when compiling wasm_lua_binarytrees.  This change removes
pretty much all dynamic allocation by changing to a SmallVec<[Value; 8]>
instead.  A fixed size of 4 gets all the gains to be had, in testing, so 8
gives some safety margin and is harmless from a stack-use perspective: 8
Values will occupy 32 bytes.
As a bonus, this change also reduces the compiler's dynamic instruction count
by about 0.5%.
=> VirtRegs::find: use SmallVec instead of Vec for val_stack.

cranelift-frontend/Cargo.toml, cranelift-frontend/src/ssa.rs
Allocations associated with pushes to EbbHeaderBlockData::predecessors account
for 4.9% of all heap allocation (calls) in CL.  This change avoids almost all
of them by changing it to be a SmallVec<[PredBlock; 4]>.  Dynamic instruction
count falls by 0.15%.
=> EbbHeaderBlockData::predecessors: use SmallVec instead of Vec

cranelift-codegen/src/isa/mod.rs
This changes replace the inner function creation by a simple if using the `cfg!` macro.
=> Simplify isa_builder macro

cranelift-wasm/src/environ/dummy.rs, cranelift-wasm/src/environ/spec.rs, cranelift-wasm/src/module_translator.rs, cranelift-wasm/src/sections_translator.rs, cranelift-wasm/tests/wasm_testsuite.rs
This allows a `ModuleEnvironment` trait object to parse the name section of a wasm binary!
=> allow module environment to parse name section

cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs, filetests/isa/x86/run-i64.clif
Add a new recipe "rout" intended to be used by arithematic operations
that output flags, currently being used for `iadd_cout` and `isub_bout`.
Fixes: https://github.com/CraneStation/cranelift/issues/1009
/cc @wingo @caitp @sunfishcode @bnjbvr
=> [codegen] add new recipe "rout"

cranelift-codegen/src/dominator_tree.rs, cranelift-codegen/src/ir/layout.rs, cranelift-entity/src/map.rs
There are a number of places where the number of ebbs in a SecondaryMap is already known, at the same time that another SecondaryMap with Ebb keys is being built.
When this is the case, we can avoid buffer-growing reallocations by allocating the new SecondaryMap at the same initial capacity as the known capacity.
=> Avoid unnecessary reallocations in domtree::with_function()

cranelift-codegen/meta/src/shared/legalize.rs, cranelift-codegen/src/context.rs, cranelift-codegen/src/legalizer/mod.rs, cranelift-codegen/src/simple_preopt.rs, filetests/isa/x86/legalize-custom.clif, filetests/isa/x86/legalize-f64const-x64.clif, filetests/legalizer/iconst-i64.clif, filetests/simple_preopt/div_by_const_indirect.clif, filetests/simple_preopt/simplify32.clif, filetests/simple_preopt/simplify64.clif
So my current thinking about isplit/iconcat is that both should not appear post-legalization, and every isplit must have an iconcat input, so the iconcat results are used instead. This seems to make sense if isplit/iconcat are just type system artifacts.
So trying a very simple program on x86 32-bits, that is generating an i64 constant, I implemented this legalization. This could be done in the meta language if there was literal support in the legalize patterns (cc @abrown).
Now it's funny because it interacts with f64const generation on 32 bits (so the test will fail, hence the WIP status of this PR). f64const are generated by reproducing the bit pattern in an i64, then bitcasting this to a f64 register. This is wrong on 32 bits platforms, where instead we should probably legalize it …
=> Legalize i64.const by breaking it into two i32.const

cranelift-frontend/src/frontend.rs
After we add any instruction to an EBB, we can't add EBB parameters
anymore. There is an assertion in `append_ebb_param` to detect this
error, but the backtrace generated doesn't give any hint what happened.
We add an error message to the assertion so the user can understand what
is wrong.
fixes #1003
=> [frontend] Add message for pristine assertion violation

cranelift-codegen/meta/src/cdsl/instructions.rs, cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs, cranelift-codegen/src/predicates.rs, filetests/isa/x86/floating-point-zero-constants-32bit.clif, filetests/isa/x86/floating-point-zero-constants.clif, filetests/isa/x86/isub_imm-i8.clif, filetests/isa/x86/optimized-zero-constants-32bit.clif, filetests/isa/x86/optimized-zero-constants.clif
This change is pretty closely modeled after the similar change in #344, and extends xor-to-clear to integer registers as well
Couple comments for questions I have, but this looks like it does the right things to me, so if y'all say it's good, then by all means :)
=> Use 'xor r, r' to set registers to 0 instead of mov

.azure-pipelines.yml, README.md, ci/fuzzit.sh, fuzz/fuzz_reader_parse_test.rs
Proposing to enable continuous fuzzing of the good fuzzing targets. I see this was mentioned in #306 as a possible future improvement.
This patch runs both existing targets on [Fuzzit](https://fuzzit.dev/). There's [a build](https://travis-ci.org/bookmoons/cranelift/builds/577307862) under my Travis account I'm expecting to succeed.
The PR build will fail due to missing an API key. Setup is like this:
* In Fuzzit create targets `cranelift-translate-module` `cranelift-reader-parse`
* In Fuzzit settings grab an API key. In repo settings in [Travis](https://travis-ci.org/) paste it to envvar `FUZZIT_API_KEY`.
Thank you for considering.
=> Continuous fuzzing

cranelift-codegen/src/verifier/mod.rs, filetests/verifier/bitcast.clif
Bitcasting to a smaller size is invalid.
closes #854
=> [codegen] Check for downcasting in bitcast instruction

cranelift-codegen/src/verifier/mod.rs, filetests/isa/x86/extractlane-binemit.clif, filetests/verifier/simd-lane-index.clif
@bnjbvr, I thought I would resolve this issue (and I thought I had) but the filetests are giving me weird errors:
```
FAIL filetests/isa/x86/insertlane-run.clif: run(%test_insertlane_):
Verifier errors:
- inst2: The lane 16 does not index into the type f32x4
FAIL filetests/isa/x86/extractlane-run.clif: run(%test_extractlane):
Verifier errors:
- inst3: The lane 32 does not index into the type f32x4
212 tests
```
I do not see invalid lane indexes in either https://github.com/CraneStation/cranelift/blob/master/filetests/isa/x86/extractlane-run.clif or https://github.com/CraneStation/cranelift/blob/master/filetests/isa/x86/insertlane-run.clif, though.
=> Add verifier check to ensure each SIMD lane index is within bounds; fixes #1016

cranelift-codegen/meta/src/shared/legalize.rs, cranelift-codegen/src/isa/x86/enc_tables.rs, filetests/isa/x86/saturating-float-cast.clif
=> Correctly zero extend operand of fcvt_from_uint for 8ints and 16bit ints

cranelift-codegen/src/binemit/stackmap.rs
Functionality is preserved, all tests pass.
It is unclear if this method really should take `&Vec<bool>` rather than `&[bool]`. Should I make this change as well?
=> Simplify and rename `Stackmap::from_vec`

test-all.sh
Cargo doesn't exit gracefully when it receives a broken pipe, when it does it outputs as non zero exit code triggering the else branch. This doesn't happen in every case, but I can get it consistently on macOS 10.14.6 for `ensure_installed cargo-deadlinks`.
https://github.com/CraneStation/cranelift/blob/92f5c55449b5aee42b09c4436289d815d429b72f/test-all.sh#L76
This changes the condition from piping cargo's output into collecting the output into a anonymous file and providing that as an argument to grep.
=> Fixed broken pipe race condition in ensure_installed

cranelift-codegen/src/ir/entities.rs
Addresses https://github.com/CraneStation/cranelift/issues/1038
Document stackslots, funcrefs, heaps, sigrefs, and jumptables.
Also adds more inter-crate links.
I can't find a way to link to a type/function in a different crate if that crate isn't currently in scope for the code. For example, [the documentation for JumpTable](https://github.com/CraneStation/cranelift/compare/master...jyn514:doc-entity?expand=1#diff-dd78b3709a42d640a60ea2733dcdbe53R187) links to `FunctionBuilder::create_jump_table`, but the link is broken (it points to `cranelift_codegen/ir/entities/cranelift_frontend::FunctionBuilder::create_jump_table`, which is clearly wrong).
There are two ways I can think to resolve this:
1. Link directly to docs.rs like this: …
=> [WIP] Add more documentation for entities

cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/legalize.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs, cranelift-codegen/meta/src/shared/formats.rs, cranelift-codegen/meta/src/shared/immediates.rs, cranelift-codegen/meta/src/shared/instructions.rs, cranelift-codegen/src/ir/dfg.rs, cranelift-codegen/src/ir/entities.rs, cranelift-codegen/src/ir/mod.rs, cranelift-codegen/src/isa/x86/enc_tables.rs, cranelift-codegen/src/verifier/mod.rs, cranelift-codegen/src/write.rs, cranelift-reader/src/parser.rs, cranelift-serde/src/serde_clif_json.rs, cranelift-wasm/src/code_translator.rs, filetests/isa/x86/shuffle-legalize.clif, filetests/isa/x86/shuffle-run.clif, filetests/isa/x86/vconst-rodata.clif
This uses work pending review in #943 and adds some encodings for boolean comparisons in order to allow more complete testing of the `shuffle` implementation.
=> Add x86 shuffle implemention

cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/src/ir/immediates.rs, cranelift-codegen/src/write.rs, cranelift-reader/src/parser.rs, cranelift-wasm/src/code_translator.rs, cranelift-wasm/src/func_translator.rs, cranelift-wasm/src/sections_translator.rs, cranelift-wasm/src/translation_utils.rs, filetests/isa/x86/iadd-simd.clif
To support running spec tests in wasmtime, I had to modify cranelift with the following commits. This is a non-exhaustive list since some spec tests are currently failing and will likely require further changes.
=> Support running spec tests in wasmtime

cranelift-codegen/meta/src/cdsl/typevar.rs, cranelift-codegen/meta/src/shared/formats.rs, cranelift-codegen/meta/src/shared/mod.rs
These were causing compilation warnings.
=> tidy: Remove extra semicolons

cranelift-codegen/meta/src/isa/x86/encodings.rs
- `fill` attempted to use a GPR recipe, `fillSib32`, instead of its FPR equivalent, `ffillSib32` (code compiled without error but incorrect instructions were allowed, e.g. `v1 = regmove v0, %rdi -> %xmm0`
- `regmove` could be encoded with a GPR recipe, `rmov`, which hid the above incorrectness; now only FPR-to-FPR regmoves are allowed using the `frmov` recipe
=> Fix incorrect regmove and fill encodings for SIMD types

cranelift-codegen/meta/src/cdsl/ast.rs, cranelift-codegen/meta/src/cdsl/cpu_modes.rs, cranelift-codegen/meta/src/cdsl/encodings.rs, cranelift-codegen/meta/src/cdsl/isa.rs, cranelift-codegen/meta/src/cdsl/type_inference.rs, cranelift-codegen/meta/src/cdsl/xform.rs, cranelift-codegen/meta/src/constant_hash.rs, cranelift-codegen/meta/src/default_map.rs, cranelift-codegen/meta/src/gen_binemit.rs, cranelift-codegen/meta/src/gen_legalizer.rs, cranelift-codegen/meta/src/gen_registers.rs, cranelift-codegen/meta/src/gen_settings.rs, cranelift-codegen/meta/src/gen_types.rs, cranelift-codegen/meta/src/isa/riscv/encodings.rs, cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs
Removing kind from the literal field is simple enough; it just lowers the precision of the check when a literal is used in an Apply, but that seems fine.
Also an additional commit that replace a lot of pub by pub(crate), trying to help the compiler catch more unused methods/fields.
=> Remove "kind" from Literal

cranelift-wasm/Cargo.toml, cranelift-wasm/src/module_translator.rs
Uses new SectionContent api, which is simpler than matching on
SectionCode and then getting the right reader, & avoids possible panics
=> cranelift-wasm: upgrade to wasmparser 0.39.1

cranelift-codegen/meta/src/cdsl/ast.rs, cranelift-codegen/meta/src/cdsl/xform.rs, cranelift-codegen/meta/src/gen_legalizer.rs, cranelift-codegen/meta/src/shared/legalize.rs
In order to enable basic block by default (#796) , we have to reduce the legalization of `brnz.i128` to produce a temporary basic block in which the conditional jump on the second part can be produced.
This pull request changes the previous meta code to:
```rust
narrow.legalize(
def!(brnz.I128(x, ebb1, vararg)),
vec![
def!((xl, xh) = isplit(x)),
def!(brnz(xl, ebb1, vararg)),
def!(jump(ebb2, Literal::empty_vararg(&imm.vararg))),
ebb!(ebb2),
def!(brnz(xh, ebb1, vararg)),
],
);
```
Which produces the following code:
```rust
ir::Opcode::Brnz => {
// Unwrap () << brnz.i128(x, ebb1, vararg)
let (x, ebb1, vararg, predicate) = if let crate::ir::InstructionData::Branch {
destination,
ref args,
..
} = pos.func.dfg[inst] {
let func = &pos.func;
let args = args.as_slice(&func.dfg.value_lists);
( …
```
=>  Fix #1023: Update brnz.i128 legalization to use non-extended basic blocks.

cranelift-wasm/src/environ/spec.rs, cranelift-wasm/src/func_translator.rs, cranelift-wasm/src/lib.rs, cranelift-wasm/src/state.rs
`VisibleTranslationState` was a wrapper around a `TranslationState` that was meant to public API consumers outside of this crate. However, the internal `TranslationState` and all its methods were still publicly exposed! This commit simplifies and remedies the situation by combining them into a single `TranslationState` type. Most of its methods are only `pub(crate)` now, not visible to the entire world. The only methods that are `pub` are the ones that `VisibleTranslationState` exposed.
r? @sunfishcode
=> Combine `VisibleTranslationState` and `TranslationState`

cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/mod.rs, cranelift-codegen/meta/src/isa/x86/opcodes.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs
This names opcode bytes statically in meta isa/x86 encodings. The `Template::opcodes()` was changed to enforce use of such static, named bytes. As a small benefit, that also means no more owned vectors, and no more vector cloning every time you call a copy-constructor function!
I believe this caught three bugs, but I didn't want to change the bytes just in case I am mistaken. I have marked them with "FIXME" comments. In all cases, it looks like we're encoding a 32-bit form where a 64-bit form is expected (which is the 32-bit form prefixed with `0x66`).
Passes all tests locally. The tests caught one typo: I accidentally specified `ADD` as `0x09` instead of `0x01`. The test failure made that super easy to identify and fix. We have good tests :)
=> Name opcodes statically in isa/x86. Closes #1051

filetests/isa/x86/legalize-br-table-bb.clif
Follow-up of #1044 for enabling basic blocks by default.
=> Set speed-and-size optimization level for legalize-br-table-bb.clif test case.

cranelift-wasm/src/code_translator.rs
For x86 at least, the encodings for SIMD `load` and `store` already exist (added as a part of #992). This adds the WASM-to-CLIF conversion for these instructions.
=> Convert SIMD load and store to their respective CLIF instructions

cranelift-codegen/meta/src/shared/instructions.rs
Add documentation to the icmp instruction text for both signed and
unsigned overflow, making it very clear why unsigned overflow is
complicated and where to find it.
/cc @wingo @caitp
@sunfishcode @bnjbvr PTAL.
=> [codegen] add documentation for overflow

cranelift-codegen/src/isa/x86/abi.rs, filetests/isa/x86/baldrdash-table-sig-reg.clif
Fixes #1074; r10 was marked as the SignatureId parameter for call_indirect on x86 independently of 32 vs 64 bits, so we just need to tweak this to be platform specific.
=> Baldrdash: uses ECX for the WasmTableCallSigReg on x86 32-bits

cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/legalize.rs, cranelift-codegen/meta/src/isa/x86/opcodes.rs, cranelift-codegen/meta/src/shared/instructions.rs, cranelift-codegen/src/ir/immediates.rs, cranelift-codegen/src/isa/x86/enc_tables.rs, cranelift-reader/src/parser.rs, cranelift-wasm/src/code_translator.rs, filetests/isa/x86/extractlane-binemit.clif, filetests/isa/x86/simd-arithmetic-binemit.clif, filetests/isa/x86/simd-arithmetic-legalize.clif, filetests/isa/x86/simd-arithmetic-run.clif, filetests/isa/x86/simd-arithmetic.clif
Includes:
- new `ineg` instruction
- `isub` encodings
- `imul` encodings, but only for 16-bit and 32-bit
- saturating addition and subtraction with new instructions `sadd_sat`, `uadd_sat`, `ssub_sat`, `usub_sat`
- a fix for an incorrect recipe in `extractlane.t16x8`
=> Add SIMD arithmetic instructions on x86

cranelift-codegen/src/regalloc/branch_splitting.rs, filetests/regalloc/coalesce-bb.clif, filetests/regalloc/reload-208-bb.clif, filetests/regalloc/x86-regres-bb.clif, filetests/safepoint/basic-bb.clif
This patch changes the logic for the insertion of new blocks when splitting conditional branches.
Until now we added at the end or before the last block, which tend to mislead the branch predictor and resulted in bad benchmark results.
This patch change the logic to insert such edges before the destination. This has some advantages, such as when dealing with tight loop, to reduce the number of cache lines which are loaded for executing loops, as well as playing well with branch predictors.
=> Insert split-edge of conditional branches before the destination.

cranelift-codegen/src/ir/mod.rs
ReplaceBuilder is available in the public API through [`DataFlowGraph::replace`](https://docs.rs/cranelift-codegen/0.43.1/cranelift_codegen/ir/dfg/struct.DataFlowGraph.html#method.replace), however it's documentation is not available through rustdoc as the type isn't publicly importable.
=> Re-export ReplaceBuilder

src/clif-util.rs
The presence of the flag was checked in the code, so it was essentially already supported, but it was not properly configured when constructing the CLI arguments parser.
=> clif-util: Make the `-t` flag work with the `wasm` subcommand

cranelift-wasm/src/code_translator.rs, wasmtests/multi-16.wat
This commit fixes a bug where at the end of an `if..else..end`'s consequent block, we would sometimes erroneously jump to the `else` block instead of to the following destination block. Not good!
=> cranelift-wasm: Jump to the destination block at end of consequent

cranelift-wasm/Cargo.toml
This has [a bug fix](https://github.com/yurydelendik/wasmparser.rs/pull/135) for Wasm multi-value blocks that is necessary to getting the spec tests passing.
=> deps: bump wasmparser dependency to 0.39.2

cranelift-codegen/src/simple_preopt.rs, filetests/simple_preopt/fold-extended-move-wraparound.clif
Simple fuzz bug found on Spidermonkey. Wrapping around is correct and safe, here, so let's do this instead.
=> Allow wrap-around when subtracting type size to immediate in try_fold_extended_move

cranelift-codegen/src/legalizer/mod.rs, filetests/isa/x86/i128-isplit-forward-jump.clif
=> Fix isplit legalization for ebb params when jumping forward

cranelift-bforest/src/lib.rs
This removes a compile warning when compiling tests for cranelift-bforest. Andrew, PTAL :)
=> cleanup: remove spurious macro_use in cranelift-bforest;

cranelift-codegen/meta/src/shared/legalize.rs, cranelift-codegen/shared/src/condcodes.rs, cranelift-codegen/src/divconst_magic_numbers.rs, cranelift-codegen/src/legalizer/mod.rs, filetests/isa/x86/icmp-i128.clif, filetests/isa/x86/legalize-i64.clif
Add legalizations for icmp and icmp_imm with i64 operands for the narrow
legalization set, allowing 32-bit ISAs (like x86-32) to compare 64-bit
integers.
Fixes: https://github.com/bnjbvr/cranelift-x86/issues/2
/cc @wingo @caitp @bnjbvr @sunfishcode 
Will add other conditions next. I imagine that'll involve adding some methods to the `CondCodes` trait, but will take care of it.
Ref: https://searchfox.org/mozilla-central/source/js/src/jit/arm/MacroAssembler-arm-inl.h#1147-1150
=> [codegen] legalize icmp.i64 for 32-bit ISAs

cranelift-codegen/meta/src/shared/legalize.rs, filetests/isa/x86/imul-i128.clif, filetests/isa/x86/legalize-i128.clif, filetests/isa/x86/legalize-i64.clif
Add a legalization that legalizes imul.I64 for 32-bit ISAs.
Refs: https://github.com/bnjbvr/cranelift-x86/issues/4
/cc @wingo @caitp
@bnjbvr PTAL.
There's one small problem though, there's no existing way to handle carry output in `imul`. Good news? According to https://www.felixcloutier.com/x86/imul, `imul` does set the appropriate flags on x86-32 atleast, so I can just add an alternate `imul_ifcout` instruction, I guess? wdyt?
=> [codegen] legalize imul for 64-bit and 128-bit operands

cranelift-codegen/meta/src/cdsl/encodings.rs, cranelift-codegen/meta/src/cdsl/instructions.rs, cranelift-codegen/meta/src/isa/riscv/encodings.rs, cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/legalize.rs, cranelift-codegen/meta/src/shared/legalize.rs
After discussing over in https://github.com/abrown/cranelift/pull/3 (@bnjbvr, I believe I have dealt with the feedback you left there in these re-worked changes), I think this is ready for some more eyes. The purpose of the change is to make it easier to encode instructions for specific immediate values. Currently, one has to build an `InstructionPredicate` from a constructor function (e.g. `InstructionPredicate::new_is_all_zeroes_128bit`) and attach this to the `EncodingBuilder` as an encoding predicate; with this change, one could write `e.enc(inst.bind(Immediate::UInt8(0)), ...`, e.g.
This change:
- adds a `Bindable` trait and associated conversions to unify all of the `bind_any`, `bind_ref`, etc. to a single `bind` (though I have retained a helper `bind_vector` due to it having a …
=> Allow binding immediates to instructions

cranelift-codegen/src/legalizer/mod.rs
There was a compiler warning about this.
=> Cleanup: Mark ebb as unused in legalization

cranelift-wasm/src/environ/spec.rs
Spidermonkey actually makes use of the FuncTranslator API directly. Once there's ModuleTranslatorState, we should be able to use this and not have to deal with WasmTypeMap directly, but until then, it's better to make this ctor public, so we can bump the version of Cranelift there and keep on working on Spidermonkey integration.
=> [wasm] Make the WasmTypeMap constructor public

cranelift-codegen/meta/src/cdsl/ast.rs, cranelift-codegen/meta/src/cdsl/xform.rs, cranelift-codegen/meta/src/gen_legalizer.rs, cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/legalize.rs, cranelift-codegen/meta/src/isa/x86/opcodes.rs, cranelift-codegen/src/ir/immediates.rs, cranelift-wasm/src/code_translator.rs, filetests/isa/x86/simd-logical-binemit.clif, filetests/isa/x86/simd-logical-legalize.clif, filetests/isa/x86/simd-logical-rodata.clif
This makes changes to SIMD `bor`, `band`, `bxor` and `bnot`. `bnot` is the most interesting in that it required changes in https://github.com/CraneStation/cranelift/commit/bc6c1244bc5e6cf2eae323b98b66d341460de6e0 to support constants during legalization. As discussed in #1092, custom legalizations sort of stomps on the regular legalizations (e.g. see `legalize.rs`) and before this change custom legalizations were the only way to add constants to the pool.
=> Add SIMD logical operators for x86; closes #1092

cranelift-codegen/meta/src/cdsl/ast.rs, cranelift-codegen/meta/src/cdsl/instructions.rs, cranelift-codegen/meta/src/cdsl/recipes.rs, cranelift-codegen/meta/src/cdsl/type_inference.rs, cranelift-codegen/meta/src/gen_encodings.rs, cranelift-codegen/meta/src/gen_legalizer.rs, cranelift-codegen/meta/src/isa/riscv/recipes.rs, cranelift-codegen/meta/src/isa/x86/legalize.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs
- First commit avoids unwrapping several times the InstructionData for each legalization of a specific opcode. Instead, we unwrap it once and, all the legalizations can look at the fields shared in the local scope. This required renaming a few variables in legalizations definitions, so they match in an opcode's legalization group.
- Second commit avoids the dumb "if true" statement in legalization's generated code.
- Third commit does a small refactoring of how we handle `varargs` in legalizations: before/after:
<details>
```
ir::Opcode::Brnz => {
// Unwrap () << brnz.i128(x, ebb1, vararg)
let (x, ebb1, vararg, predicate) = if let crate::ir::InstructionData::Branch {
destination,
ref args,
..
} = pos.func.dfg[inst] {
let func = &pos.func;
let args = args.as_slice(&func.dfg.value_lists);
( …
```
=> Enhance generated code for legalizations

cranelift-wasm/src/state/module_state.rs
It's useful for consumers which don't want to translate a whole module,
but just need translation of functions, like Spidermonkey.
@fitzgen PTAL.
=> [wasm] Make the ModuleTranslationState ctor public

.azure-pipelines.yml
It has started breaking in ways unrelated to Cranelift, making it hard
to spot real CI failures in Cranelift. We should re-enable it at some
point, but disable it in the meanwhile.
=> [ci] Don't have cargo nightly fuzz cause failures of the whole pipeline

cranelift-wasm/src/code_translator.rs, cranelift-wasm/src/state/func_state.rs, wasmtests/if-reachability-translation-0.wat, wasmtests/if-reachability-translation-1.wat, wasmtests/if-reachability-translation-2.wat, wasmtests/if-reachability-translation-3.wat, wasmtests/if-reachability-translation-4.wat, wasmtests/if-reachability-translation-5.wat, wasmtests/if-reachability-translation-6.wat
We weren't previously keeping track of quite the right information for whether an `if .. else .. end`'s following block was reachable or not. It should be reachable if the head is reachable and either the consequent or alternative end reachable (and therefore fall through to the following block) or do an early `br_if` to it.
This commit rejiggers `ControlStackFrame::If` to keep track of reachability at the end of the consequent (we don't need to keep track of it at the end of the alternative, since that is simply `state.reachable`) and adds Wasm tests for every reachability situation we can encounter with `if .. else .. end`.
Fixes #1132
=> cranelift-wasm: Fix reachability tracking for `if .. else .. end`

cranelift-codegen/meta/src/cdsl/instructions.rs, cranelift-codegen/meta/src/gen_legalizer.rs, cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/src/ir/constant.rs, cranelift-codegen/src/ir/dfg.rs, cranelift-codegen/src/ir/immediates.rs, cranelift-codegen/src/isa/x86/enc_tables.rs, cranelift-codegen/src/predicates.rs, cranelift-codegen/src/write.rs, cranelift-reader/src/parser.rs, cranelift-wasm/src/code_translator.rs, cranelift-wasm/src/func_translator.rs
As described in more detail in #1027, this re-factoring makes it possible to use constants of various sizes in the `ConstantPool`. This may not be advisable yet due to lack of alignment, etc. but is a necessary first step. The commits in this PR could be optionally squashed together. The `V128Imm` container is retained for uses such as in `GlobalInit::V128Const` that expect a constant of a specific size.
=> Replace V128Imm functionality with ConstantData; fixes #1027

filetests/isa/x86/i128-isplit-forward-jump.clif
This fix the last test case which prevent merging #1008.
=> i128-isplit-forward-jump.clif:  brz followed by trap

Cargo.toml, cranelift-codegen/Cargo.toml, cranelift-frontend/Cargo.toml, cranelift-wasm/Cargo.toml
This patch enables by default the basic-blocks feature set.
It is enabled in the top-level directory, in order to test locally, as well as in sub-projects, such that any project which depends on Cranelift components will also benefit from it.
This PR depends on #991 and #1007 to be merged to get a green CI.
(cc @sstangl)
=> Fix #796: Enable basic-blocks by default.

cranelift-codegen/src/regalloc/coloring.rs, cranelift-codegen/src/regalloc/pressure.rs, cranelift-codegen/src/regalloc/solver.rs, filetests/regalloc/solver-fixedconflict-var-2.clif, filetests/regalloc/solver-fixedconflict-var-3.clif, filetests/regalloc/solver-fixedconflict-var.clif
See commit message for the explanation. Our fuzzers at Mozilla found several instances of this particular bug very easily, so I've added all the test cases there, after reduction with bugpoint.
Note the smallest commit (which adds tests) is the actual fix (first commit only renames things). There might be a better way to avoid this bad situation, for instance adding a new array of "vars added because of a fixed input conflicts" in the solver, but that also mean iteration on an array. Plus, this fix is conceptually simpler, even though it might be more costly for compile time. I'll do a quick check to see if it has a dramatically bad impact.
Not sure who'd be the best reviewer for this (it's unclear from looking at this history of this file, even across renamings). Trying a few ones for …
=> Check for existing variables in solver's can_add_var

filetests/regalloc/solver-fixedconflict-var-3.clif, filetests/regalloc/solver-fixedconflict-var.clif
There are two options for fixing the build:
1. Rewrite the tests so that they pass the basic-blocks verifier.
2. Make the test feature-gated on the absence of the `basic-blocks` feature.
Many tests are already disabled by `basic-blocks` (and therefore are now off by default! We need to fix that soon). I added these to the list because I think we should probably fix these tests by just allowing `trap` to be treated as, effectively, a valid jump instruction for the purposes of a terminal `BranchGroup`.
=> Fix build by marking tests as incompatible with basic-blocks. Closes #1152

cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/legalize.rs, cranelift-codegen/meta/src/isa/x86/opcodes.rs, cranelift-codegen/meta/src/shared/instructions.rs, cranelift-wasm/src/code_translator.rs, filetests/isa/x86/simd-bitwise-legalize.clif, filetests/isa/x86/simd-bitwise-run.clif, filetests/isa/x86/simd-logical-binemit.clif, filetests/isa/x86/simd-logical-run.clif
These changes add:
- an encoding for SIMD `band_not`; this is used for legalizing `bitselect` and will likely be necessary due to changes in the SIMD spec (https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md#bitwise-and-not)
- a new `bitselect` instructions to describe the specific semantics needed; `vselect` and `select` almost fit but not quite
- a legalization of `bitselect` for x86 using 3 instructions: `band`, `band_not`, and `or`
=> Add x86 SIMD band_not and bitselect

cranelift-codegen/meta/src/cdsl/ast.rs, cranelift-codegen/meta/src/cdsl/encodings.rs, cranelift-codegen/meta/src/cdsl/formats.rs, cranelift-codegen/meta/src/cdsl/instructions.rs, cranelift-codegen/meta/src/cdsl/operands.rs, cranelift-codegen/meta/src/cdsl/recipes.rs, cranelift-codegen/meta/src/cdsl/xform.rs, cranelift-codegen/meta/src/gen_binemit.rs, cranelift-codegen/meta/src/gen_inst.rs, cranelift-codegen/meta/src/gen_legalizer.rs, cranelift-codegen/meta/src/isa/arm32/mod.rs, cranelift-codegen/meta/src/isa/arm64/mod.rs, cranelift-codegen/meta/src/isa/riscv/encodings.rs, cranelift-codegen/meta/src/isa/riscv/mod.rs, cranelift-codegen/meta/src/isa/riscv/recipes.rs, cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/instructions.rs, cranelift-codegen/meta/src/isa/x86/mod.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs, cranelift-codegen/meta/src/lib.rs, cranelift-codegen/meta/src/shared/formats.rs, cranelift-codegen/meta/src/shared/instructions.rs, cranelift-codegen/meta/src/shared/mod.rs
This does what's been discussed in #955 regarding formats. Now they're static attributes of a big structure containing all of them, so there's no risk of using an incorrect format by mistake. Sorry for the last commit which is kind of big; there's some fundamental changes in there, but most of it is pretty mechanical (pass explicit format to instructions).
@abrown, are you interested in reviewing this?
=> Remove dynamic name indirections for formats

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/improvement.md, .github/pull_request_template.md, CONTRIBUTING.md
This sets up the following things:
- two issue templates, one for bug reports, one for "the rest". They include questions so as to make it easier to propose new ideas, reduce the number of back-and-forths between contributors and maintainers, and generally improve the quality of bug reports and contributions.
- a pull request template. (There is no way to add several of them.) Again, it has a few questions that may or may not be worth answering.
- This also updates the CONTRIBUTING file:
- to suggest opening more issues for new features and non-trivial work items.
- to suggest that every change, including version bumps and other tiny changes, should go through a pull request, so they don't fall under the radar of other contributors.
This set of changes has been discussed internally first, …
=> New contribution guidelines

cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/instructions.rs, cranelift-codegen/meta/src/isa/x86/legalize.rs, cranelift-codegen/meta/src/isa/x86/opcodes.rs, cranelift-codegen/meta/src/shared/instructions.rs, cranelift-wasm/src/code_translator.rs, filetests/isa/x86/simd-logical-binemit.clif, filetests/isa/x86/simd-logical-legalize.clif, filetests/isa/x86/simd-logical-run.clif
These are mainly legalization changes though I had to add a new `x86_ptest` instruction as well as the  `vany_true` and `vall_true` instructions to legalize from (see details in the commit messages). One typing question: I chose to implement `vany_true` and `vall_true` for any `TxN` type even though the spec only calls for `IxN` because there was no overhead besides generating an extra `raw_bitcast` (a noop) in `vall_true`; however, do we want to restrict these to only `IxN` types?
=> Add `all_true` and `any_true` reductions

wasmtests/embenchen_fannkuch.wat, wasmtests/embenchen_fasta.wat, wasmtests/embenchen_ifs.wat, wasmtests/embenchen_primes.wat, wasmtests/rust_fannkuch.wat
It seems important to not break translation of large, existing, realistic wasm code bases when touching the translator. I propose to add some test cases in this PR, taken from [Embenchen](https://github.com/lars-t-hansen/embenchen) or [wasm-collection](https://github.com/sunfishcode/wasm-collection/tree/master/misc-valid), so they serve as large tests for translation. They all compile in less than 2.5 seconds on my machine with `cargo run wasm`, and would have helped catching stuff like #1132.
I think a next step would be to *compile* wasm test cases in automation, since we don't do this during testing. They would serve as large integration tests, again, but they're useful to have, in addition to all the unit test cases we're adding as we improve Cranelift.
Marking as WIP, because this …
=> [wasm] Include more large tests

cranelift-module/src/module.rs
This would have been useful while debugging something in my own project.
=> Implement Debug for Linkage

cranelift-codegen/meta/src/cdsl/encodings.rs, cranelift-codegen/meta/src/cdsl/instructions.rs, cranelift-codegen/meta/src/isa/x86/encodings.rs
here. Related to #955 and already merged #1012
first. See title
=> Simplify binding of IntCC::Equals to SIMD `icmp`

cranelift-codegen/meta/src/cdsl/encodings.rs, cranelift-codegen/meta/src/cdsl/formats.rs, cranelift-codegen/meta/src/cdsl/instructions.rs, cranelift-codegen/meta/src/cdsl/operands.rs, cranelift-codegen/meta/src/cdsl/recipes.rs, cranelift-codegen/meta/src/cdsl/regs.rs, cranelift-codegen/meta/src/cdsl/settings.rs, cranelift-codegen/meta/src/cdsl/types.rs, cranelift-codegen/meta/src/cdsl/typevar.rs, cranelift-codegen/meta/src/gen_inst.rs, cranelift-codegen/meta/src/gen_legalizer.rs, cranelift-codegen/meta/src/gen_settings.rs, cranelift-codegen/meta/src/isa/x86/registers.rs, cranelift-codegen/meta/src/isa/x86/settings.rs, cranelift-codegen/meta/src/shared/entities.rs, cranelift-codegen/meta/src/shared/settings.rs, cranelift-codegen/meta/src/shared/types.rs, cranelift-codegen/meta/src/srcgen.rs, cranelift-codegen/meta/src/unique_table.rs
No issue:
- trivial renaming mentioned in a TODO of the meta code.
- finish adding "pub(crate)" declarations everywhere in the meta crate, and remove dead code.
- remove "bit vector" functionality, unused since the transition of the meta crate to rust. Note it's not the feature for emitting SIMD constants; but a different feature to model every type variable as a bit-vector.
=> Rename Operand::is_immediate + remove bitvector functionality

cranelift-faerie/Cargo.toml, cranelift-object/Cargo.toml, cranelift-simplejit/Cargo.toml
=> Don't force enable basic-blocks feature

cranelift-module/src/module.rs
Don't log inside the `.map_err` call, which resulted in only logging
function definitions on codegen errors.
=> Log function definition unconditionally

cranelift-codegen/Cargo.toml, cranelift-codegen/src/isa/mod.rs, cranelift-codegen/src/result.rs, cranelift-codegen/src/settings.rs, cranelift-codegen/src/verifier/mod.rs, cranelift-module/Cargo.toml, cranelift-module/src/module.rs, cranelift-wasm/Cargo.toml, cranelift-wasm/src/environ/spec.rs
The failure crate invents its own traits that don't use
std::error::Error (because failure predates certain features added to
Error); this prevents using ? on an error from failure in a function
using Error. The thiserror crate integrates with the standard Error
trait instead.
=> Migrate from failure to thiserror

Cargo.toml, cranelift-bforest/Cargo.toml, cranelift-codegen/Cargo.toml, cranelift-codegen/meta/Cargo.toml, cranelift-codegen/shared/Cargo.toml, cranelift-entity/Cargo.toml, cranelift-faerie/Cargo.toml, cranelift-filetests/Cargo.toml, cranelift-frontend/Cargo.toml, cranelift-module/Cargo.toml, cranelift-native/Cargo.toml, cranelift-object/Cargo.toml, cranelift-preopt/Cargo.toml, cranelift-reader/Cargo.toml, cranelift-serde/Cargo.toml, cranelift-simplejit/Cargo.toml, cranelift-umbrella/Cargo.toml, cranelift-wasm/Cargo.toml, publish-all.sh
Also, this includes a fix for building cranelift-codegen with the `byteorder` dependency.
=> Bump version to 0.48.0

cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/src/abi.rs, cranelift-codegen/src/ir/dfg.rs, cranelift-codegen/src/ir/extfunc.rs, cranelift-codegen/src/ir/function.rs, cranelift-codegen/src/ir/stackslot.rs, cranelift-codegen/src/isa/arm32/abi.rs, cranelift-codegen/src/isa/arm32/mod.rs, cranelift-codegen/src/isa/arm64/abi.rs, cranelift-codegen/src/isa/arm64/mod.rs, cranelift-codegen/src/isa/mod.rs, cranelift-codegen/src/isa/riscv/abi.rs, cranelift-codegen/src/isa/riscv/mod.rs, cranelift-codegen/src/isa/x86/abi.rs, cranelift-codegen/src/isa/x86/mod.rs, cranelift-codegen/src/legalizer/boundary.rs, cranelift-codegen/src/legalizer/mod.rs, cranelift-codegen/src/stack_layout.rs, filetests/wasm/multi-val-b1.clif, filetests/wasm/multi-val-call-indirect.clif, filetests/wasm/multi-val-f32.clif, filetests/wasm/multi-val-f64.clif, filetests/wasm/multi-val-i32.clif, filetests/wasm/multi-val-i64.clif, filetests/wasm/multi-val-mixed.clif, filetests/wasm/multi-val-reuse-ret-ptr-stack-slot.clif, filetests/wasm/multi-val-sret-slot-alignment.clif, filetests/wasm/multi-val-take-many-and-return-many.clif, filetests/wasm/multi-val-tons-of-results.clif
~~**Do not merge! This is a work-in-progress!**~~ EDIT: ready for review now :)
I'm working on supporting arbitrarily many return values (although we will need to enforce some reasonable upper bound) in cranelift functions, and therefore in Wasm as well.
The approach I've been trying is to:
* Make use of the `sret` special argument for passing in a return pointer, pointing to space allocated in the caller's stack frame for the return values.
* Introduce new `ArgumentLocation` and `ValueLocation` variants for essentially "offset `x` from this function's `sret` parameter": `*(sret + x)`.
* During legalization, we rewrite signatures, calls, and returns to introduce usage of the `sret` return pointer parameter. Specifically,
* `legalize_signature` will add the `sret` parameter and assign …
=> Many multi-value returns

Cargo.toml, cranelift-codegen/Cargo.toml, cranelift-faerie/Cargo.toml, cranelift-frontend/Cargo.toml, cranelift-native/Cargo.toml, cranelift-object/Cargo.toml, cranelift-reader/Cargo.toml, cranelift-simplejit/Cargo.toml, cranelift-wasm/Cargo.toml, fuzz/Cargo.toml
Cont'd from #1205.
For some context, see [this comment](https://github.com/CraneStation/cranelift/pull/1205#issuecomment-550266079). We need to update a bit quicker than forecast because the `faerie` update was published as a patch version, so Cargo picks it up when collecting dependencies, and this results in conflicting versions of `target-lexicon` used throughout the code.
=> update everything to target-lexicon 0.9

cranelift-codegen/Cargo.toml, cranelift-codegen/src/isa/x86/abi.rs, cranelift-codegen/src/isa/x86/unwind.rs
This PR fixes the build errors in the unwind info implementation for
the x86 ABI by changing `byteorder` to build `no_std`.
This copies two simple functions from the `WriteBytesExt` trait so that
we can easily write to a `Vec<u8>` with a particular endianness.
Fixes #1203.
cc @sunfishcode for review.
=> Fix build errors in x86 unwind info when building no_std.

cranelift-codegen/src/ir/dfg.rs, cranelift-codegen/src/ir/function.rs, cranelift-codegen/src/isa/mod.rs, cranelift-codegen/src/isa/x86/abi.rs, cranelift-codegen/src/stack_layout.rs, filetests/isa/x86/prologue-epilogue.clif, filetests/isa/x86/windows_fastcall_x64_unwind.clif
Not discussed in any issue: this is a very small optimization to not force stack frame alignment for leaf functions that don't use the stack. This spurious stack alignment would cause stack allocations that weren't needed, adding some instruction traffic.
It's a regular 1% speedup in most of embenchen benchmarks (in Spidermonkey), with `primes` showing a 6% speedup (I expect micro-architectural issues there). Leaf functions are frequent, I guess.
Requesting review from @fitzgen since he's looked at this code recently, and this PR also contains a commit that fixes a small issue I've overlooked during review of the multi-value PR.
=> Don't align the stack frame for leaf functions not using the stack

cranelift-codegen/src/isa/encoding.rs, cranelift-codegen/src/isa/x86/enc_tables.rs
In some cases, compute_size() is used to choose between various different Encodings before one has been assigned to an instruction. For x86, the REX.W bit is stored in the Encoding. To share recipes between REX/non-REX, that bit must be inspected by compute_size().
This is a simple change related to https://github.com/CraneStation/cranelift/pull/1173 and https://github.com/CraneStation/cranelift/issues/1156. The runtime REX code needs to be able to inspect the hardcoded REX.W bit, because it's not derivable directly from type information (and anyway, that's silly).
Asking review from @abrown because @bnjbvr has a lot of reviews already :)
=> Pass Encoding to compute_size() for runtime Encoding inspection. #1156

cranelift-codegen/src/isa/x86/abi.rs
> This has been discussed in issue #..., or if not, please tell us why here.
https://github.com/CraneStation/wasmtime/pull/467
> A short description of what this does, why it is needed; if the
> description becomes long, the matter should probably be discussed in an issue
> first.
Rather than trying to count number of return registers that would be used by a given set of return values, optimistically assign the return values to registers. If we later find that we can't fit them all in registers, then backtrack and introduce the use of a struct-return pointer parameter.
> This PR contains test cases, if meaningful.
Tests in wasmtime. If we compiled the wasm spec testsuite in cranelift, that would have caught the issue as well.
=> Try and assign directly to return registers; backtrack to use struct-return param

cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/opcodes.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs, cranelift-reader/src/lexer.rs, cranelift-reader/src/parser.rs, cranelift-wasm/src/code_translator.rs, filetests/isa/x86/simd-comparison-binemit.clif, filetests/isa/x86/simd-comparison-run.clif
This builds on work in #1171; wait to review until that is merged.
here: _no issue, just continued SIMD implementation_
first: _see title_
=> Add x86 SIMD float comparisons

cranelift-codegen/meta/src/isa/x86/legalize.rs, filetests/isa/x86/legalize-splat.clif
=> Bind constant vectors to vconst; fixes #1052

.github/workflows/main.yml
As discussed in #1216, fuzzing is temporarily broken. This change disables the GitHub workflow steps that run fuzzing until this changes.
=> Temporarily disable fuzzing until #1216 is resolved

cranelift-codegen/meta/src/isa/x86/recipes.rs, cranelift-codegen/shared/Cargo.toml, cranelift-codegen/shared/src/isa/mod.rs, cranelift-codegen/shared/src/isa/x86/encoding_bits.rs, cranelift-codegen/shared/src/isa/x86/mod.rs, cranelift-codegen/shared/src/lib.rs, cranelift-codegen/src/isa/x86/binemit.rs
Related to #1156 . The x86 `Encoding.bits` field is an open-coded `u16`. Probably because it was created before we had `cranelift-codegen-shared`.
This adds a `cranelift_codegen_shared::isa::x86::EncodingBits` and friends that understand how to encode and decode that `u16`. It can then be inspected by using named functions, instead of by open-coding bit extraction. We're going to have more dynamic dispatch based on those bits, and I didn't want to continue open-coding it.
I'm trying to land smaller patches now to avoid having one huge, interleaved thing at the end, because I suspect this way will be significantly easier to review.
=> Use a struct interface for creating and reading encoding bits on x86.

cranelift-codegen/meta/src/shared/legalize.rs, filetests/legalizer/popcnt-i128.clif
This PR lowers `popcnt.i128` by narrowing it to two `popcnt.i64` instructions and an addition.
=> Add legalization for popcnt.i128 via narrowing, fixes #1116

CONTRIBUTING.md
Currently these links aren't rendered because of the extra space.
=> Fix rendered links in CONTRIBUTING.md

cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/legalize.rs, cranelift-codegen/meta/src/isa/x86/opcodes.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs, cranelift-wasm/src/code_translator.rs, filetests/isa/x86/simd-arithmetic-legalize.clif, filetests/isa/x86/simd-arithmetic-run.clif, filetests/isa/x86/simd-bitwise-binemit.clif, filetests/isa/x86/simd-bitwise-run.clif
This is a follow-on PR to #1182 (wait for #1182 to merge) that adds SIMD implementations for `fabs` and `fneg`. Both of these are legalizations and to legalize `fabs` I needed the ability to do a vector shift with an immediate (i.e. `ushr_imm`) in order to create the proper mask for zeroing the FP sign bit. Because of this, I also included encodings for the x86 SIMD shift-with-immediate operations.
=> Add additional floating-point operations

cranelift-codegen/src/ir/framelayout.rs, cranelift-codegen/src/ir/function.rs, cranelift-codegen/src/ir/mod.rs, cranelift-codegen/src/isa/x86/abi.rs
here.
first.
Continuation of #679 as Yury asked I open a new PR from my fork.
This PR teaches `cranelift-codegen` to track changes to a call frame layout, on top of which we can generate unwind and debug information (as done in #902)
@bnjbvr you were looking at this most recently in #679, so I figure you might be most interested in reviewing?
=> Track frame layout changes. (cont.d)

cranelift-codegen/meta/src/cdsl/type_inference.rs, cranelift-codegen/meta/src/shared/legalize.rs, filetests/isa/x86/extend-i128-run.clif, filetests/isa/x86/extend-i128.clif, filetests/legalizer/popcnt-i128.clif
here.
first. This implements legalizations for `uextend` and `sextend` to `i128`.
Fixes #1230
=> Legalize uextend and sextend to i128

cranelift-codegen/src/verifier/mod.rs
```
ERROR cranelift_codegen::verifier        > Found verifier errors in function:
function u0:3(i64 vmctx, i8x16) -> i8x16 system_v {
ebb0(v0: i64, v1: i8x16):
@0072                               v3 = raw_bitcast.i16x8 v1
@0072                               v4 = ineg v3
@0074                               jump ebb1(v4)
ebb1(v2: i8x16):
@0074                               return v2
}
- at inst2: arg 0 (v4) has type i16x8, expected i8x16
```
The logging level can be controlled with the `RUST_LOG` environment variable but due to `env_logger` having a default log level of `ERROR` these messages will always be printed. If we don't want that, we can downgrade these logs to `WARNING` so they can optionally be turned on by something like `RUST_LOG=cranelift_codegen=warning`.
=> Log verifier errors

cranelift-codegen/meta/src/shared/legalize.rs, filetests/isa/x86/bitrev-i128-run.clif, filetests/legalizer/bitrev-i128.clif
This PR lowers bitrev.i128 by narrowing it to two bitrev.i64 instructions and an addition.
ping @bnjbvr
=> Add legalization for bitrev.i128 via narrowing, fixes #1116

cranelift-faerie/src/backend.rs, cranelift-faerie/src/traps.rs
here.
This has not been discussed because it is a trivial change.
first.
This allows using Result::unwrap_err for `Result`s with `FaerieProduct`s.
N/A
I am not sure who could review this.
=> Derive Debug for FaerieProduct

cranelift-codegen/src/ir/jumptable.rs
here.
This is a small patch, no code change.
first.
Fix a small grammar mishap in the documentation comment for `JumpTableData`.
Found this while looking into how jump tables are emitted, figured it was worth a small PR :slightly_smiling_face:
=> Fix jump table comment grammar

cranelift-object/Cargo.toml, publish-all.sh
a git version of a dependency.
N/A
I think @philipc  would be best able to review this, but I do not know if he is a member of the core team.
=> Use a published version of `object`

cranelift-codegen/src/verifier/cssa.rs, cranelift-codegen/src/verifier/flags.rs, cranelift-codegen/src/verifier/liveness.rs, cranelift-codegen/src/verifier/locations.rs, cranelift-codegen/src/verifier/mod.rs
This removes `report!`, `fatal!`, and `nonfatal!` from the verifier code and replaces them with methods on `VerifierErrors`. In order to maintain similar ease-of-use, `VerifierError` is expanded with several `From` implementations that convert a tuple to a verifier error.
=> Remove macros from verifier; fixes #1248

.github/workflows/main.yml
Fixes error: "The input 'submodules' is not supported in actions/checkout@v2"
See [these failed checks](https://github.com/bytecodealliance/cranelift/pull/1262/checks?check_run_id=332076997) and actions/checkout#81.
=> Pin actions/checkout to v1 because v2 doesn't support submodules yet

cranelift-codegen/meta/src/shared/mod.rs
This makes opcodes.rs and inst_builders.rs deterministic, fixing bad cache miss behavior for build tools like [sccache](https://github.com/mozilla/sccache), see also [this Bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1601150).
Thanks to @glandium who wrote the original commit in spirit; I've tweaked the code to use `sort_by_key` instead of `sort_by`, to make it more idiomatic.
To make sure there was no other deterministic issue, I've ran the build script once and saved the output into a given directory, then re-ran the build script a hundred times, each time comparing the output with the one from the first run. There were no differences after this, so we *should* be good (with a very low probability of being wrong). It might be worth adding a script to do so in automation, …
=> Sort the generated list of instruction formats by name

cranelift-codegen/meta/src/shared/legalize.rs, filetests/isa/x86/brz-i8-run.clif, filetests/isa/x86/brz-i8.clif, filetests/isa/x86/select-i8.clif, filetests/isa/x86/stack-load-store8.clif
first.
This adds several legalizations for small integers.
Fixes #433.
cc #466 and #1117
=> More i8 legalizations

.github/workflows/main.yml, ci/ensure_deterministic_build.sh
Not discussed in an issue, but this has happened enough times that it would be nice to address once and for all.
This introduces a script that has a high probability of failing if the
Rust source code generated by the meta crate is not consistent accross
build script runs.
It also adds a new CI job to run it on each push, on a single platform.
=> Ensure builds are deterministic in CI

cranelift-wasm/src/code_translator.rs, cranelift-wasm/src/environ/dummy.rs, cranelift-wasm/src/environ/spec.rs
I have patches that add support for bulk-memory-operations in SpiderMonkey with Cranelift. These commits are the prerequisites for those patches.
The only major change is adding extensibility points to cranelift-wasm for translating bulk-memory-operations. These will be used in SM to translate the operations into function calls which will do the actual work.
=> Add hooks for implementing bulk-memory-operations

cranelift-wasm/src/code_translator.rs, cranelift-wasm/src/environ/dummy.rs, cranelift-wasm/src/environ/mod.rs, cranelift-wasm/src/environ/spec.rs, cranelift-wasm/src/func_translator.rs, cranelift-wasm/src/lib.rs, cranelift-wasm/src/sections_translator.rs, cranelift-wasm/src/translation_utils.rs, src/clif-util.rs, src/wasm.rs
cranelift-wasm is missing conversion of wasm reftypes to cranelift IR. The PR adds capability to translate ref params and locals to IR.
Example: https://gist.github.com/yurydelendik/47b51002f998bccbcad86ace5b62d3d4
/cc @fitzgen
=> Add wasm reference/pointers translation.

cranelift-codegen/build.rs, cranelift-codegen/meta/src/cdsl/type_inference.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs, cranelift-codegen/src/binemit/memorysink.rs, cranelift-codegen/src/context.rs, cranelift-codegen/src/isa/mod.rs, cranelift-codegen/src/isa/x86/abi.rs, cranelift-codegen/src/licm.rs, cranelift-codegen/src/verifier/mod.rs, cranelift-entity/src/boxed_slice.rs
This PR removes a few needless clones and adds `# Safety` sections to docs of unsafe functions.
=> fix some clippy warnings

cranelift-wasm/src/code_translator.rs
=> Bitcast values incoming to `vall_true` and `vany_true` before use in Wasm translation

cranelift-wasm/src/code_translator.rs
=> Truncate over-large parameters to splat

cranelift-codegen/meta/src/isa/x86/recipes.rs, cranelift-codegen/shared/Cargo.toml, cranelift-codegen/shared/src/isa/x86/encoding_bits.rs, cranelift-codegen/shared/src/lib.rs, cranelift-codegen/src/isa/x86/binemit.rs
This re-factors `EncodingBits` to remove the dependency on `packed_struct`; the result is more lines of code, which is unfortunate.
=> Remove packed_struct dependency

cranelift-module/src/module.rs
first.
This removes the need for end-users of `cranelift-module` to call `module.finalize_definitions` before `module.finish` is called. It is fine for `finalize_definitions` to remain `pub` because the implementation calls `.drain()` on all relevant data, so it will never be finalized twice.
N/A, no new features.
I am not sure who should review this. r? @bnjbvr
=> [module] Finalize definitions for the end-user

cranelift-codegen/meta/src/isa/x86/encodings.rs, filetests/isa/x86/scalar_to_vector-binemit.clif, filetests/isa/x86/simd-construction-run.clif
Previously, the use of `enc_x86_64` emitted two encodings for `scalar_to_vector.i64`: a 32-bit move to an XMM register and a 64-bit move to an XMM register. Due to the ordering in `enc_x86_64`, the 32-bit move was used when legalizing `splat`, resulting in missing 4 bytes when splatting 64-bit values. This change makes 64-bit values always use the REX.W encoding, leaving lower-width values with three encodings: 32-bit, 64-bit no REX, and 64-bit with REX.W.
=> Fix `scalar_to_vector`: move not wide enough for 64-bit values

cranelift-codegen/meta/src/isa/x86/legalize.rs, filetests/isa/x86/simd-arithmetic-legalize.clif, filetests/isa/x86/simd-arithmetic-run.clif
Previously `fsub` was used but this fails when negating -0.0 and +0.0 in the SIMD spec tests; using more instructions, this change uses shifts to create a constant for flipping the most significant bit of each lane with `bxor`.
=> Fix legalization of SIMD `fneg`

cranelift-codegen/meta/src/isa/x86/legalize.rs, filetests/isa/x86/simd-comparison-legalize.clif, filetests/isa/x86/simd-comparison-run.clif
=> Fix legalization of `icmp ugt`

cranelift-codegen/meta/src/isa/x86/legalize.rs
#1278 renamed `ones` to `u128_ones`, but #1286 added a new usage of `ones`.
```
error[E0425]: cannot find value `ones` in this scope
--> cranelift-codegen/meta/src/isa/x86/legalize.rs:564:33
|
564 |                 def!(c = vconst(ones)),
|                                 ^^^^ not found in this scope
```
r? @abrown
=> Fix build failure in cranelift-codegen

cranelift-wasm/src/code_translator.rs
=> Translate Wasm's V128AndNot to CLIF's band_not

cranelift-codegen/meta/src/cdsl/recipes.rs, cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs, cranelift-codegen/shared/src/isa/x86/encoding_bits.rs, cranelift-codegen/src/isa/x86/binemit.rs, cranelift-codegen/src/isa/x86/enc_tables.rs, filetests/isa/x86/legalize-br-icmp.clif, filetests/isa/x86/relax_branch.clif, filetests/isa/x86/shrink-multiple-uses.clif, filetests/postopt/basic.clif, filetests/postopt/complex_memory_ops.clif, filetests/regalloc/coloring-227.clif, filetests/verifier/flags.clif
I understand that this is work will likely be overridden by what Chris is working on. However, I believe this is still a good idea to land, because:
1. It is a strict decrease in the number of recipes.
2. It makes more of the REX-related code explicit, and therefore visible. Removing implicit logic makes the code easier to reason about, and therefore easier to refactor later.
3. Because the recipe count decreases, there should be a small performance improvement due to faster encoding -- there are fewer options from which to select.
4. The transformation is fairly mechanical and I believe not difficult to review.
This invalidates the work in https://github.com/bytecodealliance/cranelift/pull/1173. That approach did not work because it tried to avoid using Templates. Removing templates at …
=> Add a DynRex recipe type for x86, decreasing the number of recipes

cranelift-codegen/meta/src/isa/x86/encodings.rs
=> Use explicit rex for brz and brnz encodings

cranelift-codegen/src/ir/dfg.rs, cranelift-codegen/src/ir/extfunc.rs, cranelift-wasm/src/code_translator.rs, cranelift-wasm/src/func_translator.rs, cranelift-wasm/src/state/func_state.rs, wasmtests/call-simd.wat, wasmtests/icall-simd.wat
=> Bitcasting at control flow exits

cranelift-codegen/meta/src/isa/x86/legalize.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs, filetests/isa/x86/simd-comparison-binemit.clif, filetests/isa/x86/simd-comparison-run.clif
The Intel manual uses `CMPNLT` and `CMPNLE` to denote not-less-than and not-less-than-or-equals. These were translated previously to `FloatCC::GreaterThan` and `FloatCC::GreaterThanOrEqual` but should be correctly translated to `FloatCC::UnorderedOrGreaterThanOrEqual` and `FloatCC::UnorderedOrGreaterThan`. This change adds the necessary legalizations to make use of these new encodings.
=> Fix SIMD float comparison encoding

cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/shared/instructions.rs
See #1318, this is a 3% meta crate compilation time speedup. Only code motion, no changes in behaviors, as confirmed by the diffing of the generated code folder before/after.
=> Split define encodings + start splitting instruction definitions

cranelift-codegen/src/isa/mod.rs
The `TargetIsa` trait already requires that the implementor is `Sync` to
be shared across threads, and this commit adds in an additional
restriction of `Send` to ensure that the type can be sent-by-value
across threads as well.
This is part of an effort to make various data structures in `wasmtime`
sendable/shareable across threads.
=> Require the `Send` trait for `TargetIsa`

cranelift-wasm/src/environ/dummy.rs, cranelift-wasm/src/environ/spec.rs, cranelift-wasm/src/func_translator.rs
This provides a more flexible way to allow embedding to tell
cranelift-wasm which function parameters are hidden, and which should be
translated as wasm user variables.
This replaces https://github.com/bytecodealliance/cranelift/pull/1086.
first.
=> Add a `is_wasm_parameter` method to the wasm `FuncEnvironment`.

cranelift-codegen/shared/src/isa/x86/encoding_bits.rs, cranelift-codegen/src/ir/framelayout.rs, cranelift-codegen/src/isa/x86/binemit.rs, cranelift-codegen/src/simple_gvn.rs, cranelift-wasm/src/environ/spec.rs
Prior to this I would see the following on `cargo build`:
```
$ cargo build
warning: identical conversion
--> cranelift-codegen/shared/src/isa/x86/encoding_bits.rs:63:26
|
63 |         debug_assert_eq!(u8::from(self.rrr()), 0);
|                          ^^^^^^^^^^^^^^^^^^^^ help: consider removing `u8::from()`: `self.rrr()`
|
= note: `#[warn(clippy::identity_conversion)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#identity_conversion
warning: using `clone` on a `Copy` type
--> cranelift-codegen/shared/src/isa/x86/encoding_bits.rs:64:23
|
64 |         let mut enc = self.clone();
|                       ^^^^^^^^^^^^ help: try removing the `clone` call: `self`
|
= note: `#[warn(clippy::clone_on_copy)]` on by default
= help: …
```
=> Fix clippy warnings in EncodingBits

cranelift-codegen/src/verifier/mod.rs
Fixes #1059.
This will return a verifier error if an empty ebb is found.
=> Verify that EBBs are non-empty

Cargo.toml, cranelift-wasm/Cargo.toml, cranelift-wasm/tests/wasm_testsuite.rs, src/clif-util.rs, src/utils.rs, src/wasm.rs
This commit moves the cranelift tests and tools from the `wabt` crate on
crates.io (which compiles the wabt C++ codebase) to the `wat` crate on
crates.io which is a Rust parser for the `*.wat` format. This was
motivated by me noticing that release builds on Windows are ~5 minutes
longer than Linux builds, and local timing graphs showed that `wabt-sys`
was by far the longest build step in the build process.
This commit changes the `clif-util` binary where the `--enable-simd`
flag is no longer respected with the text format as input, since the
`wat` crate has no feature gating. This was already sort of not
respected, though, since `--enable-simd` wasn't consulted for binary
inputs which `clif-util` supports as well. If this isn't ok though then
it should be ok to close this PR!
=> Try to reduce CI times with a Rust `*.wat` parser

publish-all.sh
With all the sleeps between commands, the publish script takes a few
miniutes to run, and it can be easy to forget to create the PR when it
finishes. Add a reminder to be displayed at the end of the script.
(Skipping the template because this is a simple change.)
=> Add a reminder to create the PR to the end of the publish script.

cranelift-codegen/Cargo.toml, cranelift-codegen/src/binemit/mod.rs, cranelift-codegen/src/context.rs, cranelift-codegen/src/ir/function.rs, cranelift-codegen/src/isa/mod.rs, cranelift-codegen/src/isa/x86/abi.rs, cranelift-codegen/src/isa/x86/fde.rs, cranelift-codegen/src/isa/x86/mod.rs, cranelift-codegen/src/isa/x86/unwind.rs, cranelift-filetests/Cargo.toml, cranelift-filetests/src/lib.rs, cranelift-filetests/src/test_fde.rs, cranelift-filetests/src/test_unwind.rs, filetests/isa/x86/windows_systemv_x64_fde.clif
Currently, codegen produces unwind information only for Windows platform. We need to produce this type of information for all platforms to properly produce backtrace. See https://github.com/bytecodealliance/wasmtime/pull/759
TODO (and requires feedback):
cc @peterhuene @iximeow
=> Refactor unwind; add FDE support.

cranelift-codegen/meta/src/isa/x86/settings.rs, cranelift-codegen/meta/src/shared/settings.rs, cranelift-codegen/src/ir/libcall.rs, cranelift-codegen/src/isa/x86/abi.rs, cranelift-codegen/src/legalizer/mod.rs, cranelift-codegen/src/settings.rs, filetests/isa/x86/allones_funcaddrs32.clif, filetests/isa/x86/allones_funcaddrs64.clif, filetests/isa/x86/baldrdash-table-sig-reg.clif, filetests/isa/x86/compile-vconst.clif, filetests/isa/x86/legalize-splat.clif, filetests/isa/x86/probestack-adjusts-sp.clif, filetests/isa/x86/probestack-disabled.clif, filetests/isa/x86/probestack-size.clif, filetests/isa/x86/probestack.clif, filetests/isa/x86/relax_branch.clif, filetests/isa/x86/scalar_to_vector-compile.clif, filetests/legalizer/br_table_cond.clif, filetests/legalizer/empty_br_table.clif, filetests/regalloc/unreachable_code.clif
This is a breaking API change: the following settings have been renamed:
- jump_tables_enabled -> enable_jump_tables
- colocated_libcalls -> use_colocated_libcalls
- probestack_enabled -> enable_probestack
- allones_funcaddrs -> emit_all_ones_funcaddrs
=> Renames Settings ⚠️  (fixes #976)

cranelift-codegen/src/ir/extfunc.rs, cranelift-wasm/src/environ/dummy.rs, cranelift-wasm/src/environ/spec.rs, cranelift-wasm/src/func_translator.rs, cranelift-wasm/src/state/func_state.rs
Following up on #1329, this further replaces `num_normal_params` with a function
which calls `is_wasm_parameter` to correctly count the number of wasm
parameters a function has.
=> Correctly count the number of wasm parameters.

src/run.rs
This enables `clif-util run -` to work with stdin (seems it was intended initially).
Now errors in `iterate_files` are propagated further.
Closes #1004
=> Allow 'clif-util run' to read stdin as intended

cranelift-codegen/meta/src/cdsl/instructions.rs, cranelift-codegen/meta/src/cdsl/types.rs, cranelift-codegen/meta/src/cdsl/typevar.rs, cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/src/isa/x86/fde.rs, cranelift-codegen/src/simple_gvn.rs, cranelift-filetests/src/test_fde.rs, cranelift-frontend/src/lib.rs
=> Fix remaining clippy warnings

cranelift-codegen/src/ir/extfunc.rs, cranelift-wasm/src/code_translator.rs, cranelift-wasm/src/environ/spec.rs, cranelift-wasm/src/func_translator.rs
Added in #1329 it's now possible for multiple parameters to be non-wasm
parameters, so the previous `param_types` method is no longer suitable
for acquiring all wasm-related parameters, rather then `FuncEnvironment`
must be consulted. This removes usage of `param_types()` as a method
from the wasm translation and instead adds a custom method inline for
filtering the parameters based on `is_wasm_parameter`.
=> Use `is_wasm_parameter` in translating wasm calls

cranelift-codegen/src/isa/x86/enc_tables.rs
Previously, the assertion checked for `lane > 0` when it should have been `lane >= 0`; since lane is unsigned, this half of the assertion can be entirely removed.
=> Fix incorrect assertion for `insertlane`

cranelift-frontend/src/switch.rs
This allows library users to see what entries already exist in a switch.
N/A
I am not sure who should review this PR. r? @bnjbvr
=> add `entries()` API for Switch

cranelift-codegen/src/legalizer/mod.rs, filetests/isa/riscv/legalize-icmp_imm-i64.clif
here.
This is a really small change.
first.
This fixes small bug caused by inaccurate use of parentheses in `narrow_icmp_imm`.
No tests.
@bnjbvr
=> Fix narrow_icmp_imm

cranelift-wasm/src/code_translator.rs
If/when Cranelift gains a `load_splat` instruction, the `load + splat` could be replaced with a single Cranelift `load_splat`. This change allows the `simd_load_splat.wast` spec test to pass.
=> Add temporary translation of Wasm's `load_splat` using Cranelift's `load` and `splat` instructions

cranelift-codegen/src/ir/layout.rs, cranelift-codegen/src/legalizer/split.rs, filetests/verifier/isplit-bb.clif
Closes #1159 
Given code like the following, on x86_64, which does not have i128 registers:
ebb0(v0: i64):
v1 = iconst.i128 0
v2 = icmp_imm eq v0, 1
brnz v2, ebb1
jump ebb2(v1)
It would be split to:
ebb0(v0: i64):
v1 = iconst.i128 0
v2 = icmp_imm eq v0, 1
brnz v2, ebb1
v3, v4 = isplit.i128 v1
jump ebb2(v3, v4)
But that fails basic-block invariants. This patch changes that to:
ebb0(v0: i64):
v1 = iconst.i128 0
v2 = icmp_imm eq v0, 1
v3, v4 = isplit.i128 v1
brnz v2, ebb1
jump ebb2(v3, v4)
I decided to move the `isplit` before the terminal branch group to keep the invariants simple: in that issue it was suggested that we solve this by allowing `isplit` instructions within the branch group, but in prior patches it was common need to have to inspect multiple branches in the same terminal …
=> When splitting a const, insert prior to the terminal branch group.

cranelift-codegen/meta/src/cdsl/cpu_modes.rs, cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/mod.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs, cranelift-codegen/meta/src/shared/instructions.rs, cranelift-codegen/src/binemit/stackmap.rs, cranelift-codegen/src/ir/mod.rs, cranelift-codegen/src/ir/stackslot.rs, cranelift-codegen/src/isa/stack.rs, cranelift-codegen/src/isa/x86/abi.rs, cranelift-codegen/src/stack_layout.rs, cranelift-filetests/src/test_binemit.rs, cranelift-wasm/src/code_translator.rs, cranelift-wasm/src/environ/dummy.rs, cranelift-wasm/src/environ/spec.rs, filetests/wasm/r32.clif, filetests/wasm/r64.clif
This is the Cranelift part of the work to add reference-types to Spidermonkey+Cranelift (see [bug 1574865](https://bugzilla.mozilla.org/show_bug.cgi?id=1574865)). I will post the Spidermonkey patches there soon.
I also have two additional commits that are blocked on bytecodealliance/wasmparser#168, but this is the majority of the work.
=> Improve support for reference-types

cranelift-wasm/src/code_translator.rs, cranelift-wasm/src/func_translator.rs, cranelift-wasm/src/translation_utils.rs, wasmtests/nullref.wat, wasmtests/select.wat
The reftypes proposal has introduced a typed select instruction to ensure efficient validation in the future with complex subtyping relationships. In addition, a proper 'nullref' type has been added. Both of these changes are supported in `wasmparser` but there are some additional updates needed to `cranelift-wasm`.
=> Wasm: Typed select and nullref translation

cranelift-codegen/src/ir/libcall.rs, cranelift-codegen/src/ir/mod.rs, cranelift-codegen/src/legalizer/libcall.rs
first.
Since `get_libcall_funcref` is only used internally by the verifier,
it doesn't make sense to have it be public. This will encourage users to
look elsewhere for `memcpy` (they should be looking at
https://docs.rs/cranelift-frontend/0.51.0/cranelift_frontend/struct.FunctionBuilder.html#method.emit_small_memcpy)
N/A
I am not sure who should review this PR. r? @bnjbvr
=> Make `get_libcall_funcref` `pub(crate)`

cranelift-codegen/src/isa/x86/abi.rs, cranelift-codegen/src/isa/x86/fde.rs
Fixes #1372 (discussion there)
The patch properly arranges frame layout info commands for restore and preserve state. Also, it properly serializes them in into FDE.
=> Properly preserve and restore CFA state in FDE

cranelift-module/README.md, cranelift-module/src/backend.rs, docs/index.rst
This change makes it slightly more obvious that `cranelift-object` can
be used in lieu of `cranelift-faerie`.
There are no mentions of `cranelift-object` in this documentation, and I was confused about what the difference was between `cranelift-object` and `cranelift-faerie`.  Ideally this PR makes things slightly less confusing; I would like to eliminate `cranelift-faerie` in a future PR.
=> add documentation mentions of cranelift-object where appropriate

cranelift-faerie/src/backend.rs, cranelift-module/src/backend.rs, cranelift-module/src/module.rs, cranelift-object/src/backend.rs, cranelift-simplejit/src/backend.rs
This removes the need to call `finalize_definitions` for cranelift-object. `finalize_definitions` is only intended for backends that produce finalized functions and data objects, which cranelift-object does not.
Fixes #1353 
I couldn't come up with better names for `finalize_definitions` and `finish`. I think improving the documentation is enough. I made a small improvement here for `finalize_definitions`. I think it was already pretty clear what `finish` did.
r? @iximeow 
here.
first.
=> cranelift-object: move relocation processing to `finish`

cranelift-codegen/src/ir/function.rs, cranelift-codegen/src/stack_layout.rs
=> Fix inverted result of is_leaf method

cranelift-faerie/src/backend.rs, cranelift-object/src/backend.rs
here.
This has not been discussed yet. Discussion of why this feature was implemented is in https://github.com/m4b/faerie/issues/97.
first.
This uses the new `zero_init` api for Faerie, which uses `.bss` sections to reduce the amount of space binaries take up in memory (while being generated) and on disk (when stored).
This PR does not contain new test cases. All existing test cases pass.
I am not sure who should review this.
=> Use zeroinit API for faerie and object

cranelift-codegen/meta/src/isa/x86/legalize.rs, cranelift-codegen/meta/src/isa/x86/mod.rs, cranelift-codegen/src/isa/x86/enc_tables.rs, filetests/isa/x86/legalize-custom.clif, filetests/isa/x86/legalize-i64.clif, filetests/isa/x86/legalize-ineg-x86_64.clif
- Closes #1383 
- Cranelift already has custom legalization for ineg on vector integer types, might as well add it for scalar integer types!
- This PR includes one new test case, it's relatively meager, maybe I could add cases for all the integer type variants? (i8, i16, i32, i64). Not sure if that's too much or not!
- I don't know who could review this, maybe `bnjbvr` or `bjorn3`?
I added some comments in the diff that refer to concerns I had
=> Add ineg legalization for scalar integer types

cranelift-frontend/src/frontend.rs
here. This is mostly a cleanup.
first. They share a lot of code. Also by performing all loads before all stores, the performance of the simple-raytracer cg_clif benchmark increases by 1%.
`bnjbvr`. <strike>The list of suggested reviewers on the right can help you.</strike> (no list for non members)
=> Merge emit_small_memcpy and emit_small_memmove

cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/recipes.rs, cranelift-codegen/src/isa/x86/enc_tables.rs, filetests/isa/x86/binary64.clif
__enc_32_64__: fstDisp8, fstDisp32, fld, fldDisp8, fldDisp32, fspillSib32, fregspill32, ffillSib32, fregfill32, frmov, furm, fa, fax, f_ib
__enc_32_64_maybe_isap__: r_ib_unsigned_r, fa_ib, fa, r_ib_unsigned_gpr, fcmp, icscc_fpr
__enc_both__: frurm, pfcmp, fa, furm
=> Infer REX prefix for SIMD `store` and `vconst` instructions

cranelift-codegen/meta/src/gen_legalizer.rs
After #1385 the `x86_widen` transform group triggered an unused import warning.
=> Avoid unused import warnings in generated legalizer code

cranelift-object/src/backend.rs
Since it always returned an `Ok(Self)`, there was no reason to have a
Result.
here.
This is a small change that makes cranelift easier to use. It does not affect runtime behavior. Note that this is not backwards compatible.
first.
This returns `Self` from ObjectBuilder::new instead of returning Result. Since `new()` can never fail, there's no reason to use Result.
N/A
r? @philipc
r? @bnjbvr
=> Don't return a Result for ObjectBuilder::new

cranelift-codegen/meta/src/isa/x86/legalize.rs, cranelift-codegen/meta/src/shared/instructions.rs, cranelift-wasm/Cargo.toml, cranelift-wasm/src/code_translator.rs
The Wasm SIMD spec added [integer min/max instructions](https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md#lane-wise-integer-minimum). For x86 codegen, Cranelift already had encodings for the instructions to emit (e.g. `x86_pmins`) but did not have shared instructions with which to translate the Wasm integer min/max. This change adds `[i|u]min` and `[i|u]max` to do just that and legalizes these new Cranelift instructions to the pre-existing x86 instructions. At some point we could remove the x86 instructions entirely and attach their encodings directly on `[i|u]min` and `[i|u]max`.
=> Add integer min/max instructions for Wasm SIMD

CONTRIBUTING.md, README.md
The Bytecode Alliance will be using [Zulip](https://bytecodealliance.zulipchat.com/#narrow/stream/217117-cranelift/topic/general) for instant communication. There is a cranelift stream there, and a topic for general discussions. If you don't know about zulip, think of a stream as a collection of discussions around a general topic; then there's the ability to create specific topics within a given stream. I've added links in the README and CONTRIBUTING files of this repository, as a starting point.
[README rendered](https://github.com/bnjbvr/cranelift/blob/chat-room/README.md)
Till or Dan, can you have a look, please? Thanks!
=> Replace Gitter and IRC by a Bytecode Alliance Zulip stream link

.github/workflows/main.yml
This reverts commit 589fa95a05b3bc6dfe4076ed29fa02d6f0d3d349 (#1224) to try a CI run because https://github.com/rust-lang/rust/issues/66140 was resolved.
Fixes #1216
=> Revert "Temporarily disable fuzzing until #1216 is resolved (#1224)"

cranelift-faerie/src/backend.rs, cranelift-faerie/src/traps.rs, cranelift-module/src/backend.rs, cranelift-module/src/lib.rs, cranelift-module/src/module.rs, cranelift-module/src/traps.rs, cranelift-object/src/backend.rs, cranelift-object/src/lib.rs, cranelift-object/src/traps.rs, cranelift-simplejit/src/backend.rs
=> add a "raw" function definition interface to cranelift-module

cranelift-wasm/Cargo.toml, cranelift-wasm/src/environ/spec.rs
wasmparser::BinaryReaderError now encapsulates its fields, so call the
accessors rather than destructuring to get the fields.
=> Update to wasmparser 0.51

cranelift-codegen/meta/src/isa/x86/encodings.rs, cranelift-codegen/meta/src/isa/x86/opcodes.rs, cranelift-codegen/meta/src/shared/instructions.rs, cranelift-wasm/src/code_translator.rs, filetests/isa/x86/simd-arithmetic-binemit.clif, filetests/isa/x86/simd-arithmetic-run.clif
=> Add rounding average instructions for Wasm SIMD

cranelift-object/src/backend.rs
here.
This is a minor change and is backwards compatible.
first.
This is useful for me because I name the module after the file, which
comes from the filesystem and may not be valid UTF8.
Also, this removes a needless copy in ObjectBackend::new (`.to_vec()` copies the slice).
N/A
r? @philipc
=> Allow modules to have names of arbitrary bytes
